### ISSUE TITLE
 OpenBank fails to load unless microG is disabled

### ISSUE THREAD

**Issue by captainepoch** [microg/GmsCore#1005]
Hi!

I've been running into a problem since a few version of MicroG updated (related with Conscrypt). I use OpenBank's app for my personal finances. The app won't start unless MicroG is disabled due to Conscrypt.

I was able to catch the exception because the app uploads a log to a public pastebin, so there is it:

```


time: 1578834195329
msg: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.platform.AndroidPlatform@f58e273, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
stacktrace: java.lang.RuntimeException: Unable to create application com.accountmanager.myapplication.managers.AppManager: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.platform.AndroidPlatform@f58e273, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5929)
	at android.app.ActivityThread.access$1100(ActivityThread.java:198)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6693)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.platform.AndroidPlatform@f58e273, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Unknown Source:180)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(Unknown Source:673)
	at com.accountmanager.myapplication.managers.AppManager.onCreate(Unknown Source:9373)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5924)
	... 8 more
```

It's always the same error, the only thing it changes is the time. If I disable MicroG, the app works as usual.

Thank you for MicroG and the effort you put in the project, I hope this helps in any way.

**Comment by juanro49** [comment]
I have the same problem. At the moment, I use the OpenBank application version 1.5.3 which works fine.

**Comment by captainepoch** [comment]
> 
> 
> I have the same problem. At the moment, I use the OpenBank application version 1.5.3 which works fine.

I didn't back up that version, so I have to disable microG, open the app (which is working without microG enabled), and then enable it again (the app still works).
