### ISSUE TITLE
Uber Eats crashes

### ISSUE THREAD

**Issue by 0xNeffarion** [microg/GmsCore#1006]
Uber Eats app seems to crash upon asking for a delivery and the delivery gets ready.  
So once the tracking part on the map begins, the app doesn't open up anymore until the order is finished and arrived.

System: HavocOS 3.1 (Android 10)
MicroG: 0.2.10.19430
Uber Eats: 1.236.10002.60369
Phone: OnePlus 7 Pro

Logcat:  
> FATAL EXCEPTION: main
Process: com.ubercab.eats, PID: 26509
io.reactivex.exceptions.OnErrorNotImplementedException: Inferred subscribe point: rsj.a(SourceFile:81)
at com.ubercab.rx2.java.stackelementtagging.TaggingObserver.onError(SourceFile:45)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.a(SourceFile:281)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.b(SourceFile:172)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(SourceFile:255)
at io.reactivex.android.schedulers.AsyncHandlerScheduler$ScheduledRunnable.run(SourceFile:154)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: com.mapbox.mapboxsdk.q.a: Map interactions should happen on the UI thread. Method invoked from wrong thread is latLngForPixel.
at com.mapbox.mapboxsdk.maps.NativeMapView.f(Unknown Source:53)
at com.mapbox.mapboxsdk.maps.NativeMapView.a(Unknown Source:2)
at com.mapbox.mapboxsdk.maps.w.a(Unknown Source:2)
at org.microg.gms.maps.mapbox.ProjectionImpl.fromScreenLocation(Unknown Source:17)
at com.google.android.gms.maps.internal.IProjectionDelegate$Stub.onTransact(Unknown Source:97)
at android.os.Binder.transact(Binder.java:914)
at gux.a(Unknown Source:10)
at hnb.a(Unknown Source:5)
at hmi.a(Unknown Source:4)
at jzs.fromScreenLocation(SourceFile:36)
at rsa.a(SourceFile:417)
at rsa.a(SourceFile:379)
at rsa.a(SourceFile:212)
at rsa.a(SourceFile:144)
at rsa.lambda$TGQAShvwzCt3YKJMkbnmGbDLqpk7(Unknown Source:0)
at -$$Lambda$rsa$TGQAShvwzCt3YKJMkbnmGbDLqpk7.apply(Unknown Source:4)
at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(SourceFile:63)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.e(SourceFile:407)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(SourceFile:176)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at jih.b(SourceFile:155)
at jih.lambda$ryZimIY8UyrwGUoFi5WQGjlf3cg3(Unknown Source:0)
at -$$Lambda$jih$ryZimIY8UyrwGUoFi5WQGjlf3cg3.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:919)

**Comment by captainepoch** [comment]
If you look at [Problem-Apps](https://github.com/microg/android_packages_apps_GmsCore/wiki/Problem-Apps) and go until the end of the table you'll see why Uber and Uber Eats don't work (I had the same problem).

**Comment by selurvedu** [comment]
Works for me on lastest Uber Eats 1.238.10003.61125. Though I couldn't find where is the map screen.
Regarding Uber see https://github.com/microg/android_packages_apps_GmsCore/issues/994#issuecomment-579020011

**Comment by 0xNeffarion** [comment]
@selurvedu You need to order something then wait for the carrier to pick it up for the map to open

**Comment by selurvedu** [comment]
@0xNeffarion I just tried that and the map works well for me on version `1.239.10001.61808`. I'm using Android 9, microG Installer Revived `1.0.0` from Magisk repo and microG `0.2.10.19420` from F-Droid. The map works both when Magisk Hide is enabled and disabled.

**Comment by ale5000-git** [comment]
Could some of you please update microG GmsCore and tell me if it is fixed?

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
