### ISSUE TITLE
S5 S Health issues

### ISSUE THREAD

**Issue by Pdevo** [microg/GmsCore#1014]
I have built latest vtm version of GmsCore from repo (0.2.10.19420-1-vtm db4bb56) to use S4 S-Health running map function (the mapbox version just keep app crashing making it unusable, vtm version at least doesn't fc it and I can run the app fine. I can provide further logs for mapbox) and I just have an empty map like this:

![Screenshot_2020-02-08-14-01-10](https://user-images.githubusercontent.com/16514707/74085657-a2252e80-4a7b-11ea-9d72-9e7c66a52bd9.png)

Here what i get: 

[02-08 09:31:08.705 11816:11816 D/GmsMapViewImpl]
onCreate

[02-08 09:31:08.705 11816:11816 D/GmsMapViewImpl]
GoogleMap instance created

[02-08 09:31:08.775 11816:11816 W/GmsMapView]
java.lang.NoSuchFieldException: primaryCpuAbi
	at java.lang.Class.getField(Class.java:724)
	at org.microg.gms.maps.vtm.BackendMapView.loadNativeLib()
	at org.microg.gms.maps.vtm.BackendMapView.<init>()
	at org.microg.gms.maps.vtm.BackendMap.<init>()
	at org.microg.gms.maps.vtm.GoogleMapImpl.<init>()
	at org.microg.gms.maps.vtm.GoogleMapImpl.create()
	at org.microg.gms.maps.vtm.MapViewImpl.myMap()
	at org.microg.gms.maps.vtm.MapViewImpl.getView()
	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact()
	at org.microg.gms.maps.vtm.MapViewImpl.onTransact()
	at android.os.Binder.transact(Binder.java:361)
	at com.google.android.gms.maps.internal.IMapViewDelegate$a$a.getView(Unknown Source)
	at com.google.android.gms.maps.MapView$a.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.a$3.b(Unknown Source)
	at com.google.android.gms.dynamic.a$1.a(Unknown Source)
	at com.google.android.gms.maps.MapView$b.bi(Unknown Source)
	at com.google.android.gms.maps.MapView$b.a(Unknown Source)
	at com.google.android.gms.dynamic.a.a(Unknown Source)
	at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at com.sec.android.app.shealth.plugins.exercisepro.fragment.ExerciseProStatusFragment.onCreateView(ExerciseProStatusFragment.java:313)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1478)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1877)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
	at com.sec.android.app.shealth.framework.ui.base.RootBaseActivity.onStart(RootBaseActivity.java:148)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
	at android.app.Activity.performStart(Activity.java:5461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2301)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
	at android.app.ActivityThread.access$900(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5476)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

[02-08 09:31:08.775 11816:11816 D/GmsMapView]
Loading native vtm-jni

[02-08 09:31:08.775 11816:11816 D/dalvikvm]
No JNI_OnLoad found in /system/lib/libvtm-jni.so 0x42469700, skipping init

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
ZoomControls not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:08.885 11816:11816 W/GmsMapImpl]
ZoomControls not yet supported

[02-08 09:31:08.905 11816:11816 D/GmsMapViewImpl]
onDestroy

[02-08 09:31:09.045 739:859 D/SensorService]
 [AR] -0.0 4.9 8.7

[02-08 09:31:09.045 739:859 D/SensorService]
AutoRotationSensor::process: Ar_SensorChanged oldrotation = [0], rotation = [255]

[02-08 09:31:09.045 739:908 V/WindowOrientationListener]
Rotation Sensor : x=255.0

[02-08 09:31:09.165 11816:11816 D/GmsMapViewImpl]
onCreate

[02-08 09:31:09.165 11816:11816 D/GmsMapViewImpl]
GoogleMap instance created

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
ZoomControls not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
Compass not yet supported

[02-08 09:31:09.215 11816:11816 W/GmsMapImpl]
ZoomControls not yet supported

**Comment by Pdevo** [comment]
This is fixed with the recent versions of microG and now works flawlessly now on MapLibre.
Thank you!
