### ISSUE TITLE
[IAP] de.dwd.warnapp crashes trying to purchase full version

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [microg/GmsCore#1064]
## Expected Behavior
App should not crash; in app purchase should be successful.

## Actual Behavior
App is crashing, when clicking on:

- "VOLLVERSION (1,99€)", blue button on the page showing after installation
-  "Vollversion kaufen (1,99€)" (~ Purchase full version) in the three dot menu

``` bash
2020-06-03 13:16:59.183 24158-24259/de.dwd.warnapp W/BillingClient: querySkuDetailsAsync got null sku details list
2020-06-03 13:16:59.198 24158-24158/de.dwd.warnapp D/AndroidRuntime: Shutting down VM
2020-06-03 13:16:59.199 24158-24158/de.dwd.warnapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dwd.warnapp, PID: 24158
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at de.dwd.warnapp.util.r0.a(PlanBManager.java:40)
        at de.dwd.warnapp.util.j.a(Unknown Source:4)
        at com.android.billingclient.api.BillingClientImpl$a$a.run(com.android.billingclient:billing@@2.1.0:7)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-03 13:16:59.217 24158-24158/de.dwd.warnapp I/Process: Sending signal. PID: 24158 SIG: 9

```

## Specifications

  - App version: [3.1.1 (28.09.2020)](https://play.google.com/store/apps/details?id=de.dwd.warnapp) downloaded via AuroraStore
  - microG version: 0.2.10.19420-77 (68c4e0d)
  - OS: /e/OS [(0.9-p-2020093076095-dev-FP2)](https://images.ecloud.global/dev/FP2/)
  - Device: [Fairphone 2](https://doc.e.foundation/devices/FP2/)

**Comment by Axolord** [comment]
Just tried and can confirm. 
App version: 2.5.2
microG version: 0.2.10.200475-dirty via Nanodroid
OS: Havoc 3.3 with Android 10
Devices: Redmi Note 5 Pro

**Comment by konstantingoretzki** [comment]
Can confirm this behaviour on my device.
App version: 3.0.2.3025 , downloaded via Aurora Store
microG version: 0.2.11.202414
OS: LineageOS for microG (Lineage 17.1 with Android 10)

**Comment by mar-v-in** [comment]
Buying full version of DWD works on master.
