### ISSUE TITLE
Incompatibility with netflix

### ISSUE THREAD

**Issue by flavien-perier** [microg/GmsCore#1067]
Good morning,
I'm currently using the /e/ operating system on Fairfone 3 (Android 9). When I use the Netflix application, I regularly receive a message that the MicroG application has crach.

After debugging with `adb logcat` I get the following stacktrace:

```
06-04 20:52:23.891  9479  9553 D GmsDroidguardHelper: Using cached file from /data/user/0/org.microg.gms.droidguard/app_dg_cache/717dc6b1ee3213ea2fa6198911c68c9c6cc4715c/the.apk
06-04 20:52:23.950  9479  9553 D GmsDroidguardHelper: c -> com.google.android.gms
06-04 20:52:23.926  9479  9479 W Thread-3: type=1400 audit(0.0:155): avc: denied { search } for name="vendor" dev="tmpfs" ino=4944 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=0
06-04 20:52:23.992  9479  9553 D GmsDroidguardHelper: b -> 3927303995488753452
06-04 20:52:23.926  9479  9479 W Thread-3: type=1400 audit(0.0:156): avc: denied { getattr } for name="/" dev="mmcblk0p1" ino=1 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:firmware_file:s0 tclass=filesystem permissive=0
06-04 20:52:24.036  9479  9553 E SQLiteLog: (14) cannot open file at line 36667 of [68b898381a]
06-04 20:52:24.036  9479  9553 E SQLiteLog: (14) os_unix.c:36667: (2) open(/data/user/0/org.microg.gms.droidguard/databases/dg.db) -
06-04 20:52:24.037  9479  9553 E SQLiteDatabase: Failed to open database '/data/user/0/org.microg.gms.droidguard/databases/dg.db'.
06-04 20:52:24.037  9479  9553 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at com.google.ccc.abuse.droidguard.DroidGuard.initNative(Native Method)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at com.google.ccc.abuse.droidguard.DroidGuard.init(DroidGuard.java:447)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at com.google.ccc.abuse.droidguard.DroidGuard.run(DroidGuard.java:429)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at java.lang.reflect.Method.invoke(Native Method)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at org.microg.gms.droidguard.DroidguardHelper.invoke(DroidguardHelper.java:140)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:93)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
06-04 20:52:24.037  9479  9553 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:764)
```

The only solution I've found so far is to disable MicroG when I watch a show...
Thank you in advance if you can help me.

**Comment by georgikoemdzhiev** [comment]
I experience the same on /e/. Every time I open Netflix I start seeing "microG Services Core keeps stopping" error

**Comment by entepe85** [comment]
I tried it on /e/ 0.13-2020120889008, using MicroG 0.2.14.204215-dirty-noen, and don't have any issues with Netflix.
