### ISSUE TITLE
microG Services Core crash with RemoteDroidGuard

### ISSUE THREAD

**Issue by ErnyTech** [microg/GmsCore#1104]
When trying to obtain a SafetyNET attestation, microG Services Core crashes.

```
7-18 17:09:36.510  7130  8428 D GmsDroidguardHelper: c -> com.google.android.gms
07-18 17:09:36.520   916  2103 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.droidguard.service.PING pkg=com.google.android.gms (has extras) } U=0: not found
07-18 17:09:36.530  8400  8426 E AndroidRuntime: FATAL EXCEPTION: Thread-2
07-18 17:09:36.530  8400  8426 E AndroidRuntime: Process: com.google.android.gms, PID: 8400
07-18 17:09:36.530  8400  8426 E AndroidRuntime: java.lang.IllegalArgumentException: Service not registered: org.microg.gms.droidguard.RemoteDroidGuardConnector$Connection@f4bbdab
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1756)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at org.microg.gms.droidguard.RemoteDroidGuardConnector.connectForTask(RemoteDroidGuardConnector.java:107)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at org.microg.gms.droidguard.RemoteDroidGuardConnector.guard(RemoteDroidGuardConnector.java:36)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at org.microg.gms.snet.SafetyNetClientServiceImpl$1.run(SafetyNetClientServiceImpl.java:81)
07-18 17:09:36.530  8400  8426 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

**Comment by mar-v-in** [comment]
Are you using latest release 0.2.11.202414 ?

**Comment by ErnyTech** [comment]
Yes

**Comment by mar-v-in** [comment]
I am asking because since 0.2.11.202414:
- Services Core provides support for the `com.google.android.gms.droidguard.service.PING` action, yet it claims to not find it
- RemoteDroidGuardConnector 0.1.2 is used, which has a fix for exactly the stacktrace you see.
- was released July 26, but your log is from "07-18 17:09:36", which is before the release.

**Comment by ale5000-git** [comment]
microG now pass SafetyNet.
