### ISSUE TITLE
aPager PRO: "Cannot request Google Account Access" exception

### ISSUE THREAD

**Issue by dicer** [microg/GmsCore#1157]
I'm trying to get the following app to work: https://play.google.com/store/apps/details?id=org.xcrypt.apager.android2
The app is free and the problem happens very early, so the error should be easy to reproduce:

- Installed the app via Aurora
- Open it and select "I WANT TO USE THE OLD METHOD" on the bottom of the screen
- App should now display a drop-down box with accounts to select one but doesn't
- Check log and find the following error:

```09-04 16:40:39.349  1235 17426 I ActivityManager: START u0 {flg=0x4000000 cmp=org.xcrypt.apager.android2/.ui.RegistrationActivity} from uid 10128
09-04 16:40:39.399 30921 30921 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5c62d6a
09-04 16:40:39.506  3912 27619 D SafeParcel: Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-04 16:40:39.506  3912 27619 D SafeParcel: Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-04 16:40:39.506  3912 27619 D SafeParcel: Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-04 16:40:39.506  3912 27619 D SafeParcel: Unknown field id 13 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-04 16:40:39.506  3912 27619 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='org.xcrypt.apager.android2', extras=Bundle[{}]}
09-04 16:40:39.508  3912 27619 D GmsAuthManagerSvc: onTransact [unknown]: 8, android.os.Parcel@10607d0, 16
09-04 16:40:39.508 30921 30996 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity: Cannot request Google Account Access
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity: java.io.IOException: Service unavailable.
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.zzd.zza(Unknown Source:72)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.zzd.zzb(Unknown Source:87)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.zzi.zzb(Unknown Source:5)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.zzd.zza(Unknown Source:77)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.zzd.requestGoogleAccountsAccess(Unknown Source:51)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at com.google.android.gms.auth.GoogleAuthUtil.requestGoogleAccountsAccess(Unknown Source:66)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at org.xcrypt.apager.android2.ui.RegistrationActivity.requestGoogleAccountAccess(RegistrationActivity.java:215)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at org.xcrypt.apager.android2.ui.RegistrationActivity.lambda$DQ00xTjoO-bze12GdrY5BmmvBZI(Unknown Source:0)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at org.xcrypt.apager.android2.ui.-$$Lambda$RegistrationActivity$DQ00xTjoO-bze12GdrY5BmmvBZI.run(Unknown Source:2)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at io.reactivex.Completable.subscribe(Completable.java:2309)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-04 16:40:39.542 30921 30921 E org.xcrypt.apager.android2.ui.RegistrationActivity:    at java.lang.Thread.run(Thread.java:764)
09-04 16:40:39.542  3912 27619 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@10607d0, 16
09-04 16:40:39.566  3912 27619 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@e4300e8, 16
09-04 16:40:39.566  3912 27619 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@10607d0, 16
09-04 16:40:39.574  3912 27619 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@e4300e8, 16
```

- This happens on LineageOS 16 with microg 0.2.11.202414
- I have Privacy Guard disabled for this app
- Google account is registered with microg and visible in the account settings
- In the account settings "Sign-in & security"-> "Allow apps to find accounts" is enabled
- microg selfcheck says "Permission to find accounts on device" is enabled (and everything else is checked as well)

Anything else I can check? @mar-v-in Hope you can have a look, as I need this app for getting emergency alarms. No worries, this is not the only way to get them, but it would certainly be highly appreciated

**Comment by ingerling** [comment]
Any news in this topic? @dicer did you find a workaround?
I have the same issue using lineage 17 (lineage for microg) microg 0.2.16 and earlier.
Anything I can try to help solving this?

**Comment by dicer** [comment]
No, I have no workaround. I wanted to adb backup the app from a phone 
with google play services and restore it on my microg phone, but the app 
does not allow me to do that. So I would need root on the google phone, 
which I did not have.
I'm also not sure how long that would last if the app checks again 
against the missing API.

So still waiting for a response from Marvin

**Comment by dicer** [comment]
Still doesn't work with version 0.2.16.204713

**Comment by dicer** [comment]
@mar-v-in I looked at the source code and as far as I can tell, GoogleAuthUtil.requestGoogleAccountsAccess just needs to return true. I have no idea though under which key I should put that into the bundle. How do I figure that out? Do you have any pointers for me?

**Comment by Bergmankei** [comment]
It works for me with latest beta of apager and latest microG:
https://alamos-support.atlassian.net/wiki/spaces/documentation/pages/2730786817/Inbetriebnahme+auf+Ger+ten+ohne+offizielle+Google+Dienste

**Comment by ingerling** [comment]
@Bergmankei Thanks for the hint! May be I'll try when there is a new version (assuming the current beta is stable then)

**Comment by dicer** [comment]
The provisioning seems to work for me as well on LAOS 20 with microg!
Couldn't test it yet, but looks promising. Now trying to figure out a way to purchase the webhook extension...

**Comment by dicer** [comment]
The workaround is not possible anymore. On my phone and with firefox I can now register just fine in the app though. So no need for the workaround anymore. It just works! Thanks! Closing
