### ISSUE TITLE
Can't login with google with firebase button

### ISSUE THREAD

**Issue by feduss** [microg/GmsCore#1162]
Here's the log of my app:

`09-08 18:13:46.021 I/ActivityTaskManager(1418): START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.feduss.isola_sarda_prenotazioni cmp=com.feduss.isola_sarda_prenotazioni/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10187
09-08 18:13:46.029 D/GmsMeasureSvcImpl(3183): f10: null
09-08 18:13:46.036 W/ActivityThread(30805): handleWindowVisibility: no activity for token android.os.BinderProxy@1f57503
09-08 18:13:46.038 I/ActivityTaskManager(1418): START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras)} from uid 10187
09-08 18:13:46.038 W/AuthSignInClient(30805): Could not launch sign in Intent. Google Play Service is probably being updated...
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 3 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 5 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 6 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 7 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 9 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 10 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 12 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 13 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 14 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 15 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.060 W/TAG     (30805): Google sign in failed
09-08 18:13:46.060 W/TAG     (30805): com.google.android.gms.common.api.ApiException: 17: 
09-08 18:13:46.060 W/TAG     (30805): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
09-08 18:13:46.060 W/TAG     (30805): 	at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.0.0:9)
09-08 18:13:46.060 W/TAG     (30805): 	at com.feduss.isola_sarda_prenotazioni.SplashScreenActivity.onActivityResult(SplashScreenActivity.java:380)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.Activity.dispatchActivityResult(Activity.java:8131)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
09-08 18:13:46.060 W/TAG     (30805): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-08 18:13:46.060 W/TAG     (30805): 	at android.os.Looper.loop(Looper.java:214)
09-08 18:13:46.060 W/TAG     (30805): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-08 18:13:46.060 W/TAG     (30805): 	at java.lang.reflect.Method.invoke(Native Method)
09-08 18:13:46.060 W/TAG     (30805): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-08 18:13:46.060 W/TAG     (30805): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
09-08 18:13:46.058 D/SafeParcel(3183): Unknown field id 16 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.065 D/SafeParcel(3183): Unknown field id 17 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.065 D/SafeParcel(3183): Unknown field id 18 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-08 18:13:46.065 D/SafeParcel(3183): Unknown field id 22 in com.google.android.gms.measurement.internal.AppMetadata, skipping.`

With official play services it works well.

**Comment by Natalcia** [comment]
This happens in `pl.mbank` (polish mBank app) during loading of cards list and loading never ends.
```
10-20 19:33:21.999  3522  3549 D GmsTapAndPayImpl: onTransact [unknown]: 21, android.os.Parcel@735a2c, 16
10-20 19:33:22.001  3522 20082 D GmsMeasureSvcImpl: f10: null
10-20 19:33:22.010  3522 20082 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:33:22.010  3522 20082 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:33:22.010  3522 20082 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:33:22.010  3522 20082 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:33:22.011  3522 20082 D GmsMeasureSvcImpl: f1: pl.mbank
10-20 19:33:22.259  2251  2251 D ImageWallpaper: wallpaper visibility changes to: false
10-20 19:33:22.310   693 31418 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
10-20 19:33:22.310   948   948 I cnss-daemon: nl80211 response handler invoked
10-20 19:33:22.310   948   948 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 13  received
10-20 19:33:23.038  1428 11845 D WificondControl: Scan result ready event
10-20 19:33:23.477  9169 13404 D OpenGLRenderer: endAllActiveAnimators on 0x79f6cd5500 (RippleDrawable) with handle 0x7ad6ccc380
10-20 19:33:23.521  2658  2658 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3184 
10-20 19:33:23.522  2658  2658 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1830 
10-20 19:33:23.905 20051 27714 W ConnectionTracker: Exception thrown while unbinding
10-20 19:33:23.905 20051 27714 W ConnectionTracker: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjp@848d118
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1756)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:17)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:6)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.measurement.internal.zziv.zzag(com.google.android.gms:play-services-measurement-impl@@17.5.0:10)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.measurement.internal.zziu.zza(com.google.android.gms:play-services-measurement-impl@@17.5.0:7)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:7)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-20 19:33:23.905 20051 27714 W ConnectionTracker: 	at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:9)
10-20 19:33:24.319   948   948 I cnss-daemon: nl80211 response handler invoked
10-20 19:33:24.319   948   948 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 13  received
10-20 19:33:24.320   693 31418 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
10-20 19:33:24.858   585 27774 E ResolverController: No valid NAT64 prefix (104, <unspecified>/0)
```
And it happens in `pl.vinted` when trying to view some item, of course loading never ends. 
```
10-20 19:32:10.205   693 31418 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
10-20 19:32:10.206   948   948 I cnss-daemon: nl80211 response handler invoked
10-20 19:32:10.206   948   948 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 13  received
10-20 19:32:12.087  3522  3522 D GmsWalletPaySvc: onBind: Intent { act=com.google.android.gms.wallet.service.BIND pkg=com.google.android.gms }
10-20 19:32:12.140  3522  3549 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='pl.vinted', extras=Bundle[{}]}
10-20 19:32:12.140  3522 20082 D GmsWalletPaySvc: bound by: GetServiceRequest{serviceId=WALLET, gmsVersion=12451000, packageName='pl.vinted', extras=Bundle[{}]}
10-20 19:32:12.143  3522  3549 D GmsWalletOwSvc: onTransact [unknown]: 14, android.os.Parcel@735a2c, 17
10-20 19:32:12.192  3522  3549 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.192  3522  3549 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.192  3522  3549 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.192  3522  3549 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.193  3522  3549 D GmsMeasureSvcImpl: f1: pl.vinted
10-20 19:32:12.193  3522 20082 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.193  3522 20082 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.193  3522 20082 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.193  3522 20082 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.194  3522 20082 D GmsMeasureSvcImpl: f1: pl.vinted
10-20 19:32:12.194  3522  3549 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.194  3522  3549 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.194  3522  3549 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.194  3522  3549 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
10-20 19:32:12.195  3522  3549 D GmsMeasureSvcImpl: f1: pl.vinted
```

**Comment by ale5000-git** [comment]
Could some of you please update microG GmsCore and tell me if it is fixed?

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
