### ISSUE TITLE
Dynamite barcode support for university app

### ISSUE THREAD

**Issue by Pdevo** [microg/GmsCore#1211]
Hi, I am trying to use the QR code scanner of my university app to mark attendance and book study room, a newly introduced system due to the sanitary situation. From the little I can understand, there is no Dynamite barcode support API in microG, which seems to be required by these kind of apps. 

[10-05 13:33:27.324 853:936 V/MARsPolicyManager]
updatePackagesScore PackageInfo name -- it.easystaff.unipd
[10-05 13:33:27.324 9065:9065 W/ResourcesManager]
getTopLevelResources: /data/app/it.easystaff.unipd-1/base.apk / 1.0 running in it.easystaff.unipd rsrc of package null
[10-05 13:33:27.344 853:1438 V/NetworkPolicy]
getFirewallRuleWifi UID:10214 policy:0
[10-05 13:33:27.384 9065:9065 W/DynamiteModule]
Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
[10-05 13:33:27.394 9065:9065 W/DynamiteModule]
IDynamite loader version < 2, falling back to getModuleVersion2
[10-05 13:33:27.394 9065:9065 D/GmsDynamiteLoaderImpl]
unimplemented Method: getModuleVersion for com.google.android.gms.vision.dynamite.barcode
[10-05 13:33:27.394 9065:9065 I/DynamiteModule]
Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
[10-05 13:33:27.404 9065:9065 D/BarcodeNativeHandle]
Cannot load feature, fall back to load whole module.
[10-05 13:33:27.404 9065:9065 W/DynamiteModule]
Local module descriptor class for com.google.android.gms.vision.dynamite not found.
[10-05 13:33:27.404 9065:9065 W/DynamiteModule]
IDynamite loader version < 2, falling back to getModuleVersion2
[10-05 13:33:27.404 9065:9065 D/GmsDynamiteLoaderImpl]
unimplemented Method: getModuleVersion for com.google.android.gms.vision.dynamite
[10-05 13:33:27.404 9065:9065 I/DynamiteModule]
Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
[10-05 13:33:27.414 9065:9065 E/BarcodeNativeHandle]
Error Loading module
com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
	at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
	at com.google.android.gms.internal.vision.zzg.<init>(Unknown Source)
	at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
	at com.mobe.university.qrCode.BarcodeCaptureActivity.createCameraSource(BarcodeCaptureActivity.java:173)
	at com.mobe.university.qrCode.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:102)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[10-05 13:33:27.414 9065:9065 W/BarcodeNativeHandle]
Native handle not yet available. Reverting to no-op handle.
[10-05 13:33:27.414 9065:9065 W/DynamiteModule]
Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
[10-05 13:33:27.414 9065:9065 W/DynamiteModule]
IDynamite loader version < 2, falling back to getModuleVersion2
[10-05 13:33:27.414 9065:9065 D/GmsDynamiteLoaderImpl]
unimplemented Method: getModuleVersion for com.google.android.gms.vision.dynamite.barcode
[10-05 13:33:27.414 9065:9065 I/DynamiteModule]
Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
[10-05 13:33:27.414 9065:9065 D/BarcodeNativeHandle]
Cannot load feature, fall back to load whole module.
[10-05 13:33:27.414 9065:9065 W/DynamiteModule]
Local module descriptor class for com.google.android.gms.vision.dynamite not found.
[10-05 13:33:27.414 9065:9065 W/DynamiteModule]
IDynamite loader version < 2, falling back to getModuleVersion2
[10-05 13:33:27.414 9065:9065 D/GmsDynamiteLoaderImpl]
unimplemented Method: getModuleVersion for com.google.android.gms.vision.dynamite
[10-05 13:33:27.414 9065:9065 I/DynamiteModule]
Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
[10-05 13:33:27.414 9065:9065 E/BarcodeNativeHandle]
Error Loading module
com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
	at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
	at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source)
	at com.mobe.university.qrCode.BarcodeCaptureActivity.createCameraSource(BarcodeCaptureActivity.java:178)
	at com.mobe.university.qrCode.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:102)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[10-05 13:33:27.414 9065:9065 W/Barcode-reader]
Detector dependencies are not yet available.

Since the app usage is preparatory for the university I will just have to switch back to Google GMS, so not claiming for anything, of course, would just like to know if the function would be possibly implemented in a not better defined future

**Comment by mar-v-in** [comment]
Vision Barcode API is now added via 5e39818a20032d261215420fc72e05efad4202b5.

**Comment by Pdevo** [comment]
Amazing, really appreciated!
