### ISSUE TITLE
[com.google.android.apps.books] Play Books cannot run. All available Cronet providers are disabled.

### ISSUE THREAD

**Issue by lss4** [microg/GmsCore#1248]
**Affected app**
Name: Google Play Books
Package id: com.google.android.apps.books

**Describe the bug**
As of latest microG services Play Books refuses to run, complaining about "All available Cronet providers are disabled. A provider should be enabled before it can be used." It used to work before (0.1.x), as far as I could remember.

**To Reproduce**
1. Try run Google Play Books
2. The app force closes, try running it again.
3. It'll say the app keeps crashing. Copy the [crash log URL](https://del.dog/ufomemapem.txt) and open it in the browser.

**Expected behavior**
Google Play Books should run properly.

**Screenshots**
Nothing really. The app crashes right after startup.

**System**
Android Version: 10
Custom ROM: Havoc GSI 3.8

**microG**
microG Core version: 0.2.13.203915
microG Self-Check results: All ticked. Play Store (from NanoDroid) are working (including IAP purchases).

**Additional context**
I'm using NanoDroid. Also, I'm using Bromite SystemWebView.
Not sure what this "Cronet provider" is. I googled about this error and found nothing useful.

**UPDATE**: Just found out that Play Books version 5.10.7_RC10 works with microG. These older versions can be found on APK hosting sites such as APKMirror.

**Comment by lss4** [comment]
Will leave a copy of the crash log in case that link expires.

```
time: 1603627170360
msg: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
stacktrace: java.lang.RuntimeException: Unable to resume activity {com.google.android.apps.books/com.google.android.apps.play.books.home.HomeActivity}: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
	at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(PG:8)
	at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(PG:2)
	at org.chromium.net.CronetEngine$Builder.<init>(PG:1)
	at jjo.a(Unknown Source:40)
	at znz.a(PG:1)
	at cxa.k(PG:1)
	at jkj.d(Unknown Source:23)
	at kbq.a(PG:4)
	at gd.d(PG:13)
	at fu.a(PG:157)
	at fu.c(PG:20)
	at gp.a(PG:13)
	at gp.a(PG:74)
	at fu.b(PG:57)
	at fu.a(PG:225)
	at fu.c(PG:13)
	at fu.c(PG:3)
	at fu.l(PG:6)
	at ep.onPostResume(PG:3)
	at rm.onPostResume(PG:1)
	at mgx.onPostResume(PG:1)
	at android.app.Activity.performResume(Activity.java:7983)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```

**Comment by DarkPhoenix2704** [comment]
@lss4 did it work on Previous version?

**Comment by lss4** [comment]
I think it used to work on 0.1.x versions that was shipped with NanoDroid 22.6. I remember having tried Play Books with that version before.

However, the previous versions had some issues such as location providers not working properly so I upgraded to the recent versions (Aurora Droid currently doesn't explicitly display upgrades of microG).

Not sure if the version shipped with NanoDroid was modified, but it upgraded to the current versions in microG repo without issues, so most likely not (unless NanoDroid uses the same signature as microG).

Sadly I don't think I can revert to that old version to confirm, as it was quite difficult to get everything (namely Play Store and IAP) working and it can be easily broken if not careful.

**Comment by rmachuca89** [comment]
Similar symptoms but not related to `microg` as far as I know.

Context: I just upgraded my Amazon Fire Kindle from HD 8 (7th gen) to an HD 10 (9th Gen) and all of my usual sideloaded Google Apps work except for Books.

Just having some time to learn to debug Android apps, found myself able to get the bellow stack trace:

```java
TraceHashCode: 35f2ae417c8e92281d9b546d35394027b6d52dbd    
Process: com.google.android.apps.books
hasForegroundActivities: true
Flags: 0x3cfbbe44
Package: com.google.android.apps.books v106481 (5.12.5_RC05.337333688)
Build: Amazon/maverick/maverick:7.0/PS7316/1737N:user/amz-p,release-keys
OsBuildNumber: PS7316_user_1737
OsOtaNumber: 0018824481156
Screen: ON
AlexaMode: OFF

java.lang.RuntimeException: Unable to resume activity {com.google.android.apps.books/com.google.android.apps.play.books.home.HomeActivity}: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3817)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
  at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6740)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
  at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(PG:8)
  at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(PG:2)
  at org.chromium.net.CronetEngine$Builder.<init>(PG:1)
  at jjo.a(Unknown Source:40)
  at znz.a(PG:1)
  at cxa.k(PG:1)
  at jkj.d(Unknown Source:23)
  at kbq.a(PG:4)
  at gd.d(PG:13)
  at fu.a(PG:157)
  at fu.c(PG:20)
  at gp.a(PG:13)
  at gp.a(PG:74)
  at fu.b(PG:57)
  at fu.a(PG:225)
  at fu.c(PG:13)
  at fu.c(PG:3)
  at fu.l(PG:6)
  at ep.onPostResume(PG:3)
  at rm.onPostResume(PG:1)
  at mgx.onPostResume(PG:1)
  at android.app.Activity.performResume(Activity.java:7350)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3803)
  ... 11 more
` ` `

There is a bunch of other related thread dumps but not sure if relevant. I tried factory reset from no backup and still no luck with that app only. Will be monitoring this thread and see if I can provide more context or at least see how you resolve this.

**Comment by lss4** [comment]
The thing is there are few information about this "All available Cronet providers are disabled." error. Googling about it now returns nothing but this issue.

**Comment by lss4** [comment]
Not sure if Play Books require something that microG or third-party WebView lacks.

I also have an unrooted device with stock Google stuffs in it, and Play Books app works as intended.

**Comment by lss4** [comment]
Issue still present with the most recent Play Books update, and microG version 0.2.14.

The core issue is to figure out what this **cronet** really is. Again, there's no helpful Google search results about this.

**Comment by ewlsh** [comment]
Cronet is the Chromium Network stack built for Android. It is a library for fetching resources over a Network and I believe it is already open source.

Play Services provides a version of it so apps no longer need to bundle it themselves.

This is the Android documentation on [Cronet](https://developer.android.com/guide/topics/connectivity/cronet/)

The official sample app: https://github.com/GoogleChromeLabs/cronet-sample

A project to distribute/compile cronet on Android: https://github.com/lizhangqu/cronet
A project to enable cronet in React Native: https://github.com/akshetpandey/react-native-cronet

Essentially, GmsCore would need to ship a build of cronet and implement the APIs for access.

**Comment by ewlsh** [comment]
GmsCore doesn't currently implement the Net APIs (`com.google.android.gms.net`) which is essentially just Cronet right now.

https://developers.google.com/android/reference/com/google/android/gms/net/package-summary

**Comment by lss4** [comment]
Downloaded a few versions from APKMirror and I found that version 5.10.7_RC10 works with latest microG. Guess I need to hold the update for the time being.

I'll leave this issue open for now, as I think all similar issues can be closed at once when `com.google.android.gms.net` APIs get implemented.

**Comment by lss4** [comment]
I recently updated my phone to an Android 11 GSI.

It seems with the most recent version of Play Books (5.14.3_RC03) and microG 0.2.17 the issue went away and it's working normally. Not sure which side fixed it for me.

If now Play Books works for others as well I'll close the issue.

**Comment by rmachuca89** [comment]
Same here, we should be able to close this one.

**Comment by lss4** [comment]
> Same here, we should be able to close this one.

Okay. Closing this issue for now.
