### ISSUE TITLE
FireBaseAuth not working in TIER-App

### ISSUE THREAD

**Issue by eplinux** [microg/GmsCore#1281]
Dear all,
when TIER App tries to perform a SMS-auth via FireBaseAuth, the microG overlayer appears but nothing happens. Below I attached a logcat. I stripped of the key part of the URL https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=[replaced] because I'm not sure whether it contains sensitive info.

11-25 22:24:41.221 D/GmsFirebaseAuth( 4035): onBind: Intent { act=com.google.firebase.auth.api.gms.service.START pkg=com.google.android.gms }
11-25 22:25:00.825 D/GmsFirebaseAuth( 4035): sendVerificationCode
11-25 22:25:01.168 E/Volley  ( 4035): [333] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=[replaced]
11-25 22:25:01.363 W/WindowManager( 1610): Unable to start animation, surface is null or no children.
11-25 22:25:01.470 E/Volley  ( 4035): [333] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=[replaced]
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): java.lang.RuntimeException: com.android.volley.AuthFailureError
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at org.microg.gms.firebase.auth.IdentityToolkitClient$getProjectConfig$2$2.onErrorResponse(IdentityToolkitClient.kt:58)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.Request.deliverError(Request.java:617)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at android.os.Handler.handleCallback(Handler.java:883)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at android.os.Looper.loop(Looper.java:214)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at java.lang.reflect.Method.invoke(Native Method)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): Caused by: com.android.volley.AuthFailureError
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
11-25 22:25:01.471 W/GmsFirebaseAuth( 4035): 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Comment by Romern** [comment]
See https://github.com/microg/GmsCore/issues/1198#issuecomment-722550444 . Tier banned non-android authentication.

**Comment by Acipenser** [comment]
Any news on that?

I have a similar problem in LineageOS with microG (0.2.22.212658) when I try to register in Tier.

I can type in my phone number and click on continue. It opens the browser then with a connection to `https://consumer-app-release.firebaseapp.com/__/auth/handler?apiKey=...`. After being led back to the app an error occurs :

`At the moment we can not send you a code. Please try in a few minutes.`

Everything is checked in the microG self test and I activated Cloud Massaging and Google SafetyNet.

**Comment by TonyK0s** [comment]
Just download an older version, for example i am vurrently using TIER app on 3.5.0 version, no firebase checks at all.

**Comment by Romern** [comment]
@TonyK0s I can not confirm this, I downloaded Version 3.5.0 (version code  35000461) from the play store using Aurora, but when logging in, the FirebaseAuth Dialog still appears.

**Comment by TonyK0s** [comment]
Try this one: https://apkfun.com/down_TIER-Scooter-Sharing.24991244.html

**Comment by TonyK0s** [comment]
Then clear all data and cache.

**Comment by Acipenser** [comment]
I tried version 3.5.0 from Aurora Store and APK Fun, but both are just getting stuck in an loading loop after entering the phone number. I cleared all app data and cache.

**Comment by Romern** [comment]
@TonyK0s It won't work, because both apps use FirebaseAuth, and they have to, as the API requires it, there are no alternative or old APIs. You probably have play services installed or aren't logging in, as the main view doesn't require authentification.

**Comment by ou-li** [comment]
No luck here either. :-(
I end up in the Browser:
"Unable to process request due to missing initial state..."

@Acipenser How do I clear app data (other than deleting and re-installing?)

LineageOS with MicroG 18.1 from 1/3/2022

Services Core 0.2.24.214816

Don't know if the following arre needed:
Services Framework Proxy 0.1.0
FakeStore 0.0.2
DroidGuard Helper 0.1.0

**Comment by henk23** [comment]
> I can type in my phone number and click on continue. It opens the browser then with a connection to `https://consumer-app-release.firebaseapp.com/__/auth/handler?apiKey=...`. After being led back to the app an error occurs :
> 
> `At the moment we can not send you a code. Please try in a few minutes.`

I have the exact same behavior, but have installed a Samsung Stock Android 12 with original Google Play Store. So maybe the issue is not related to MicroG after all?

**Comment by xdubx** [comment]
Same problem.

Micro g Version 0.2.29.233013-49 (1a2e94c)
Tier Version 4.0.119

Calyxos 4.14.0

**Comment by tamas646** [comment]
TIER app now seems to be working fine (at least for me).

TIER app version: 4.0.127
MicroG version: 0.2.27.223616
Android version: LOS 20 (2024-01-05 nightly)

**Comment by jomo02** [comment]
> TIER app now seems to be working fine (at least for me).
> 
> TIER app version: 4.0.127 MicroG version: 0.2.27.223616 Android version: LOS 20 (2024-01-05 nightly)

Cannot confirm that (Same TIER app, MicroG and LOS version).

**Comment by tamas646** [comment]
> Cannot confirm that (Same TIER app, MicroG and LOS version). Tried to sign up with my phone number. Did you use the Google Sign-In?

No, I didn't. I used SMS verification.
I reinstalled the app, and now it stuck at loading screen after I selected 'Other options'. :confused: 
Sorry, it was probably a false alarm.

**Comment by tamas646** [comment]
Okay, I tried it multiple times...
It seems it was just a network issue (maybe slow connection) which caused the loading screen to hang.

But now I can say for sure that SMS authentication is indeed working fine for me.

**Comment by jomo02** [comment]
I updated to lineage-21.0-20240521-microG yesterday and it's working now for me.

**Comment by mmueller-kaffeeschluerfercom** [comment]
works for me with LineageOS 21: [https://github.com/microg/GmsCore/issues/1967#issuecomment-2148361789](https://github.com/microg/GmsCore/issues/1967#issuecomment-2148361789)

**Comment by clan1995** [comment]
Отправлено с телефона
