### ISSUE TITLE
[EN] Null pointer error when using latest EN API

### ISSUE THREAD

**Issue by cgrigis** [microg/GmsCore#1300]
**Affected app**
App that uses the [DP3T SDK](https://github.com/DP-3T/dp3t-sdk-android), such as SwissCovid.

**Describe the bug**
Trying the latest  version of the SDK, I get the following exception:

```
W/ExposureNotification: provideDiagnosisKeys() with org.dpppt.android.calibration/null
D/ExposureNotification: Created instance 57843761 of database for ExposureNotificationService
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.dpppt.android.calibration, PID: 27719
    java.lang.NullPointerException: params.token must not be null
        at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$tid$1.invokeSuspend(ExposureNotificationServiceImpl.kt:224)
        at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$tid$1.invoke(Unknown Source:10)
        at org.microg.gms.nearby.exposurenotification.ExposureDatabase$Companion$with$2.invokeSuspend(ExposureDatabase.kt:917)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Indeed, the SDK now uses `provideDiagnosisKeys(DiagnosisKeyFileProvider)`, which does not set a token, while it is expected non-null in the implementation.

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version: v0.2.14.204215

EN libs bundled along with the app

**Comment by mar-v-in** [comment]
I already had the code that fixes this locally, but failed to commit it :smile:

**Comment by cgrigis** [comment]
Excellent, thanks!
