### ISSUE TITLE
Exposure Notifications cannot round a NaN value

### ISSUE THREAD

**Issue by syntech16** [microg/GmsCore#1309]
**Describe the bug / To Reproduce**
Yesterday I installed `Radar COVID 1.1.0` ([Play Store](https://play.google.com/store/apps/details?id=es.gob.radarcovid), [GitHub project](https://github.com/RadarCOVID/radar-covid-android)) and activated Exposure Notifications in microG. 

I don't know if I'll be able to reproduce the crash again, but after waking up today and unlocking the phone, a crash dialog appeared.

**System**
Device: OnePlus 5T (ONEPLUS A5010, dumpling)
Android Version: 11
Custom ROM: MSM-Xtended XR-v2.0
microG version: 0.2.14.204215

**Additional context**

I think these are the relevant logs. I've saved the complete logs from `adb logcat -d > logcat.log`, in case anything else is needed.

```
12-13 11:21:14.586  4098  4098 E AndroidRuntime: FATAL EXCEPTION: main
12-13 11:21:14.586  4098  4098 E AndroidRuntime: Process: com.google.android.gms, PID: 4098
12-13 11:21:14.586  4098  4098 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot round NaN value.
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$1.invokeSuspend(ExposureNotificationServiceImpl.kt:284)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$1.invoke(Unknown Source:10)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureDatabase$Companion$with$2.invokeSuspend(ExposureDatabase.kt:917)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-13 11:21:14.586  4098  4098 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by mar-v-in** [comment]
Updating to 0.2.15 should fix this.
