### ISSUE TITLE
microg is constantly dying in the background.

### ISSUE THREAD

**Issue by reyis4402** [microg/GmsCore#1333]
when i turn on services running in developer options microg 0 process runs with 1 service. And the process starts over and over again. In addition, location services are not among the services that work.
Microg latest version 
![Screenshot_20201223-134824](https://user-images.githubusercontent.com/60405617/102994042-f36cce00-4526-11eb-8921-2fff36294ac2.png)

**Comment by reyis4402** [comment]
Android versions 11 arrowos official

**Comment by mar-v-in** [comment]
Can you please provide:
- logcat
- version of microG used
- result of microG Self-Check.

**Comment by token0** [comment]
My microG is force closing frequently. 
V 0.2.16.204713
All checks passing
GmsCore.apk installed in priv-app via Magisk module.

I'm getting this message:
![image](https://user-images.githubusercontent.com/4627595/103445656-d0a58c80-4c7f-11eb-99e5-c407b98132fa.png)


```
#######RuntimeEnvironmentInformation#######
crash time=2020-12-28 17:19:11.558
model=E5823
android version=7.1.1(25)
brand=Sony
manufacturer=Sony
board=msm8994
hardware=qcom
device=E5823
version name=0.2.16.204713
supported ABIs=arm64-v8a & armeabi-v7a & armeabi
display=32.4.A.1.54
#######ForceCloseCrashLog#######
java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@d6cd10c with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3407)
 at android.app.ActivityThread.-wrap21(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:241)
 at android.app.ActivityThread.main(ActivityThread.java:6274)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
 at androidx.legacy.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:126)
 at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3390)
```
