### ISSUE TITLE
GCM connections never last for more than 1 minute. Is this normal?

### ISSUE THREAD

**Issue by lss4** [microg/GmsCore#1340]
**Describe the bug**
It seems microG's GCM is not stable. In my case, it disconnects once every 60 seconds and recovers about 5 seconds later.

The Status' "Connected since x seconds ago" never went beyond 1 minute for me.

Setting different ping intervals doesn't help, either. It seems the "Automatic" option is already setting an interval higher than 1 minute so I might be having a different issue than #1011.

I haven't gotten a logcat yet, but a hint about what kind of log messages to look for is greatly appreciated.

**To Reproduce**
1. Go to microG settings
2. Click on Google Cloud Messaging
3. Check Status
4. The Status would say "Connected since xxx seconds ago", but when it reaches 1 minute, it becomes Disconnected and about 5 seconds later it becomes Connected again.

**Expected behavior**
Unless this being a normal behavior, the Connected status should stay for long enough, disconnections should not be frequent.

**Screenshots**
No screenshots for as it's self-explanatory.

**System**
Android Version: 10
Custom ROM: Havoc GSI 3.8 running on Razer Phone 2 (with arter97 r14)

**Additional context**
I noticed I'm receiving messages very late (can be as much as 10-15 minutes), unless I put that particular app in the foreground before I set the phone to sleep. Maybe this is related.

**Comment by mar-v-in** [comment]
- What does google device registration display as last registration time? Does it show an android id?
- Can you check your logcat for entries with `GmsGcmMcs`?

**Comment by lss4** [comment]
> * What does google device registration display as last registration time? Does it show an android id?
> * Can you check your logcat for entries with `GmsGcmMcs`?

At present, Last Registration date is 2 days ago (which should be the current uptime, as the last time I rebooted my phone was for updating Magisk canary).

GmsGcmMcs related logcats, scattered in many places... It seems the API returned something that microG doesn't seem to understand (Unknown message). 

```
12-28 00:06:00.079  4653  9914 W GmsGcmMcsInput: mcsTag: -1 mcsSize: -1
12-28 00:06:00.080  4653  9914 D GmsGcmMcsSvc: Teardown initiated, reason: null message
12-28 00:06:00.082  4653  9914 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
12-28 00:06:05.118  4653  4653 D GmsGcmMcsSvc: Connection is not enabled or dead.
12-28 00:06:05.120  4653  4653 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
12-28 00:06:05.126  4653  8782 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
12-28 00:06:05.128  4653  8782 D GmsGcmMcsSvc: Connection is not enabled or dead.
12-28 00:06:05.129  4653  8782 D GmsGcmMcsSvc: Starting MCS connection...
12-28 00:06:05.223   975 13245 E ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
12-28 00:06:05.240  4653  8782 D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
12-28 00:06:05.241  4653  8782 D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
12-28 00:06:05.817  4653  8782 D GmsGcmMcsSvc: Scheduling heartbeat in 856 seconds...
12-28 00:06:05.817  4653 13250 D GmsGcmMcsSvc: Sending login request...
12-28 00:06:05.821  4653 13250 D GmsGcmMcsOutput: Outgoing message: LoginRequest{id=android-29, domain=mcs.android.com, user=4265168237195047870, resource=4265168237195047870, auth_token=8990266584421796352, device_id=android-3b30ebe9f54a33be, setting=[Setting{name=new_vc, value=1}], adaptive_heartbeat=false, use_rmq2=true, auth_service=ANDROID_ID, network_type=1}
12-28 00:06:05.821  4653 13250 D GmsGcmMcsOutput: Write MCS version code: 41
12-28 00:06:06.137  4653 13247 D GmsGcmMcsInput: Reading from MCS version: 41
12-28 00:06:06.138  4653 13247 D GmsGcmMcsInput: Incoming message: LoginResponse{id=android-29, jid=user@firebase.com/notifications, last_stream_id_received=1, server_timestamp=1609085161145}
12-28 00:06:06.138  4653 13247 D GmsGcmMcsSvc: Logged in
12-28 00:06:06.141  4653 13247 D GmsGcmMcsInput: Incoming message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
12-28 00:06:06.141  4653 13247 W GmsGcmMcsSvc: Unknown message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
12-28 00:07:05.919  4653 13247 W GmsGcmMcsInput: mcsTag: -1 mcsSize: -1
12-28 00:07:05.920  4653 13247 D GmsGcmMcsSvc: Teardown initiated, reason: null message
12-28 00:07:05.922  4653 13247 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
12-28 00:07:10.944  4653  4653 D GmsGcmMcsSvc: Connection is not enabled or dead.
12-28 00:07:10.945  4653  4653 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
12-28 00:07:10.952  4653  8782 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
12-28 00:07:10.963  4653  8782 D GmsGcmMcsSvc: Connection is not enabled or dead.
12-28 00:07:10.964  4653  8782 D GmsGcmMcsSvc: Starting MCS connection...
12-28 00:07:11.058  4653  8782 D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
12-28 00:07:11.058  4653  8782 D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
12-28 00:07:12.069  4653  8782 D GmsGcmMcsSvc: Scheduling heartbeat in 856 seconds...
12-28 00:07:12.069  4653 16683 D GmsGcmMcsSvc: Sending login request...
12-28 00:07:12.071  4653 16683 D GmsGcmMcsOutput: Outgoing message: LoginRequest{id=android-29, domain=mcs.android.com, user=4265168237195047870, resource=4265168237195047870, auth_token=8990266584421796352, device_id=android-3b30ebe9f54a33be, setting=[Setting{name=new_vc, value=1}], adaptive_heartbeat=false, use_rmq2=true, auth_service=ANDROID_ID, network_type=1}
12-28 00:07:12.071  4653 16683 D GmsGcmMcsOutput: Write MCS version code: 41
```

**Comment by mar-v-in** [comment]
The unknown message is probably fine, I've seen it happening without any issues.
The actual issue probably is `GmsGcmMcsInput: mcsTag: -1 mcsSize: -1` which shows the TCP connection was closed unexpectedly, pretty much 1 minute after it was created. This looks like a close from outside, so could be because of a firewall or something. Are you seeing this on Wi-Fi, mobile network or both? It can also be caused by a local firewall or battery optimizer feature.

**Comment by lss4** [comment]
Okay. I'm mostly testing this on Wi-Fi but it shouldn't really matter as that's happening regardless. I did disable battery optimizations for microG stuffs, so not sure what else might be causing the issue. I think I'll just look for possible causes myself for the time being...

**Comment by TheLastGimbus** [comment]
I also had some *very weird* problems with GCM (because of which I've opened #1337 (whoa what a cool number)) - I couldn't link them to doze mode, but GCM just randomly disconnected, and never connected back until I manually disabled and enabled it (sometimes, even that/killing the app/rebooting phone didn't help)

I decided to manually disable all random apps that were registered and allow only those which I *really* want - we will see how that will help

 By the way, the dialog to allow GCM per app is unredable in dark mode - text is white, but the background is also still white

**Comment by TheLastGimbus** [comment]
Okay, so it didn't help - I still have the issue that connection is randomly disconnected, and never connects back

I tried collecting some logs, but all I've got from logcat is this:
```
2020-12-30 00:15:48.012 com.google.android.gms D/GmsGcmMcsSvc: Connection is not enabled or dead.
2020-12-30 00:15:48.840 com.google.android.gms D/GmsGcmMcsSvc: Connection is not enabled or dead.
2020-12-30 00:15:48.911 com.google.android.gms D/GmsGcmMcsSvc: Connection is not enabled or dead.
2020-12-30 00:15:48.952 com.google.android.gms D/GmsGcmMcsSvc: Connection is not enabled or dead.
```
and so on...

Self-test is all green and checked, all battery optimisations are disabled, I have Lineage 17 without any fancy "battery optimising apps"

Status just says "disconnected", and turning it off/on fixes it :+1: - instantly connects without a problem

I can send you full `bugreport.zip` if you want...

**Comment by lss4** [comment]
The issue still persists on Android 11 GSI with latest microG. GCM connections still cannot last more than 1 minute...

I just tried explicitly unblocking `mtalk.google.com` with AdAway and nothing really happened. However, I don't think this is relevant as before I moved to microG, real GApps worked on the device without any issue and I never explicitly unblocked `mtalk.google.com` before... so it's either GCM doesn't have major use of it or that my AdAway (plus other router/hosts/proxy) configurations never blocked it in the first place.

Additionally, typing the secret code `*#*#2432546#*#*` in the phone does nothing. I need to look for relevant logs in a recorded logcat file from Matlog Libre for now.

**Comment by TheLastGimbus** [comment]
I disabled `mtalk.google.com`, and I though it helped, but maybe it was only a placebo. Meanwhile, I collected some logs tailored to GCM when MicroG crashed (which it does very frequently now :disappointed: ):

```
E/AndroidRuntime(11618): FATAL EXCEPTION: main
E/AndroidRuntime(11618): Process: com.google.android.gms:persistent, PID: 11618
E/AndroidRuntime(11618): java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@7a7ee7b with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11618): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
E/AndroidRuntime(11618): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
E/AndroidRuntime(11618): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
E/AndroidRuntime(11618): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11618): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11618): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11618): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11618): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(11618): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
E/AndroidRuntime(11618): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11618): 	at androidx.legacy.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:126)
E/AndroidRuntime(11618): 	at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
E/AndroidRuntime(11618): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
E/AndroidRuntime(11618): 	... 8 more
E/AndroidRuntime(11654): FATAL EXCEPTION: main
E/AndroidRuntime(11654): Process: com.google.android.gms:persistent, PID: 11654
E/AndroidRuntime(11654): java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@d08e4f1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11654): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
E/AndroidRuntime(11654): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
E/AndroidRuntime(11654): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
E/AndroidRuntime(11654): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11654): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11654): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11654): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11654): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(11654): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
E/AndroidRuntime(11654): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11654): 	at androidx.legacy.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:126)
E/AndroidRuntime(11654): 	at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
E/AndroidRuntime(11654): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
E/AndroidRuntime(11654): 	... 8 more
E/AndroidRuntime(11816): FATAL EXCEPTION: main
E/AndroidRuntime(11816): Process: com.google.android.gms:persistent, PID: 11816
E/AndroidRuntime(11816): java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@d08e4f1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11816): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
E/AndroidRuntime(11816): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
E/AndroidRuntime(11816): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
E/AndroidRuntime(11816): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11816): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11816): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11816): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(11816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
E/AndroidRuntime(11816): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
E/AndroidRuntime(11816): 	at androidx.legacy.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:126)
E/AndroidRuntime(11816): 	at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
E/AndroidRuntime(11816): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
E/AndroidRuntime(11816): 	... 8 more
```

**Comment by ex-git** [comment]
Having similar issues with latest Calyxos and LOS with microG preconfigured. GCM connections won't stay. It works for one or two minutes. Sometimes it show connected but push message will never show. Already tried manually checkin or all possible methods that I could find. I was testing using Signal and Slack from other devices. I am using Pixel 4.  @mar-v-in  @ale5000-git

**Comment by lss4** [comment]
> Having similar issues with latest Calyxos and LOS with microG preconfigured. GCM connections won't stay. Push notification works for one or two minutes. Sometimes it show connected but push message will never show. Already tried manually checkin or all possible methods that I could find. I was testing using Signal and Slack from other devices. I am using Pixel 4. @mar-v-in @ale5000-git

The issue still happens on all devices I own. With microG GCM connection cannot stay and as a result messages may arrive much later than usual.

A workaround for the time being would be to disable the battery optimization for the apps in question. This way the apps can stay in the background and all push notifications from them will arrive on time (probably via other means than GCM).
