### ISSUE TITLE
crash in backrgound + exposure checks seem to not complete anymore

### ISSUE THREAD

**Issue by Bubu** [microg/GmsCore#1343]
Maybe related to #1339 or #1338?

I got no exposure updates since yesterday evening 8pm. And now I got a microG crash in the background.

Before yesterday the exposures were checked multiple times a day, I didn't change anything since then :thinking: 

```
12-27 12:36:34.620 30873 30873 E AndroidRuntime: Process: com.google.android.gms:persistent, PID: 30873
12-27 12:36:34.620 30873 30873 E AndroidRuntime: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:766)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at com.google.android.gms.nearby.exposurenotification.internal.IDiagnosisKeyFileSupplier$Stub$Proxy.isAvailable(IDiagnosisKeyFileSupplier.java:168)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$1.invokeSuspend(ExposureNotificationServiceImpl.kt:292)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$1.invoke(Unknown Source:10)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at org.microg.gms.nearby.exposurenotification.ExposureDatabase$Companion$with$2.invokeSuspend(ExposureDatabase.kt:1035)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-27 12:36:34.620 30873 30873 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Bubu** [comment]
CCTG Test (where you can manually trigger download and check) works sucessfully. :thinking:

**Comment by Bubu** [comment]
Exposure check ran successfully again now. So it seems like this was one (or two)-off crash?

**Comment by mar-v-in** [comment]
https://github.com/microg/GmsCore/commit/91c8e43ab947482f7c3ab55eca53d4f476f591bc handles the case when the app is stopped while providing diagnosis keys and will have it continue with what it got until that point. Next run will add the missing keys so that should be fine.
Also I made sure that issues in processing API calls don't lead to crashes in the persistent process.
