### ISSUE TITLE
Bug: microg crashing

### ISSUE THREAD

**Issue by UltraBlackLinux** [microg/GmsCore#1354]
Hey there,
I just got this crash twice in a row:
```
FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 29806
java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
	at org.microg.gms.firebase.auth.IdentityToolkitClient$request$2$2.onErrorResponse(IdentityToolkitClient.kt:42)
	at com.android.volley.Request.deliverError(Request.java:617)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

Los 17.1
gmscore 0.2.13.23915-dirty since nanolx hasn't updated the nanodroid packages yet...

Thanks!

**Comment by Ammako** [comment]
> gmscore 0.2.13.23915-dirty since nanolx hasn't updated the nanodroid packages yet...

Just commenting to let you know that the update happened yesterday, so you could upgrade and check if it helps anything.

**Comment by UltraBlackLinux** [comment]
@Ammako 
Yeah I saw thar, but he was months late. I switched to the magisk module, that's available via the module browser..
