### ISSUE TITLE
[com.zhiliaoapp.musically] TikTok crashes on sign in/up

### ISSUE THREAD

**Issue by 532910** [microg/GmsCore#1364]
**Affected app**
Name: TikTok
Package id: [e.g. com.zhiliaoapp.musically]

**Describe the bug**

**To Reproduce**
1. Install TikTok
2. Try to sign up or sigh in.

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version: 0.2.15.204713
microG Self-Check results: All ticked

**Additional context**

```
E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                                          E AndroidRuntime: Process: com.zhiliaoapp.musically, PID: 15828                                                                                                                  E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle null                                                                                    E AndroidRuntime:       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)                                                                       E AndroidRuntime:       at android.app.Activity.startIntentSenderForResultInner(Activity.java:5473)                                                                              E AndroidRuntime:       at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
E AndroidRuntime:       at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(SourceFile:117637130)                                                               E AndroidRuntime:       at androidx.core.app.b.a(SourceFile:134479878)
E AndroidRuntime:       at androidx.fragment.app.FragmentActivity.startIntentSenderFromFragment(SourceFile:134479926)                                                            E AndroidRuntime:       at androidx.fragment.app.FragmentActivity$a.a(SourceFile:134414350)
E AndroidRuntime:       at androidx.fragment.app.Fragment.startIntentSenderForResult(SourceFile:117702671)                                                                       E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.sms.a.c(SourceFile:393326)                                                                                     E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.sms.a.a(SourceFile:16908290)
E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.v2.ui.a.w.onViewCreated(SourceFile:33882201)                                                                   E AndroidRuntime:       at androidx.fragment.app.h.a(SourceFile:1471)                                                                                                            E AndroidRuntime:       at androidx.fragment.app.i.a(Unknown Source:0)                                                                                                           E AndroidRuntime:       at androidx.fragment.app.h.c(SourceFile:17301542)                                                                                                        E AndroidRuntime:       at androidx.fragment.app.h.a(SourceFile:1852)                                                                                                            E AndroidRuntime:       at androidx.fragment.app.a.f(SourceFile:393378)                                                                                                          E AndroidRuntime:       at androidx.fragment.app.h.b(SourceFile:67698726)                                                                                                        E AndroidRuntime:       at androidx.fragment.app.h.a(SourceFile:2411)                                                                                                            E AndroidRuntime:       at androidx.fragment.app.h.b(SourceFile:34078808)                                                                                                        E AndroidRuntime:       at androidx.fragment.app.h.b(SourceFile:2243)                                                                                                            E AndroidRuntime:       at androidx.fragment.app.a.e(SourceFile:196614)                                                                                                          E AndroidRuntime:       at androidx.fragment.app.l.finishUpdate(SourceFile:16908292)                                                                                             E AndroidRuntime:       at com.ss.android.ugc.aweme.views.e.finishUpdate(SourceFile:16908290)                                                                                    E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.populate(SourceFile:17301922)                                                                                     E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.populate(SourceFile:65538)                                                                                        E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.onMeasure(SourceFile:34013397)                                                                                    E AndroidRuntime:       at com.ss.android.ugc.aweme.views.RtlViewPager.onMeasure(SourceFile:33816618)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)                                                                                                            E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)                                                                                   E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)                                                                          E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)                                                                                    E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)                                                                                          E AndroidRuntime:       at android.view.View.measure(View.java:25086)                                                                                                            E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)                                                                          E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)                                                                                    E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)                                                                                          E AndroidRuntime:       at android.view.View.measure(View.java:25086)                                                                                                            E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)                                                                                   E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)                                                                                            E AndroidRuntime:       at android.view.View.measure(View.java:25086)                                                                                                            E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)                                                                                   E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)                                                                                            E AndroidRuntime:       at android.view.View.measure(View.java:25086)                                                                                                            E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E AndroidRuntime:       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
E AndroidRuntime:       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
E AndroidRuntime:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
E AndroidRuntime:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
E AndroidRuntime:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
E AndroidRuntime:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
E AndroidRuntime:       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
E AndroidRuntime:       at android.view.Choreographer.doFrame(Choreographer.java:726)
E AndroidRuntime:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
E AndroidRuntime:       at android.os.Handler.handleCallback(Handler.java:883)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:100)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:214)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:7356)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940
```

```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.zhiliaoapp.musically, PID: 7399
E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle null
E AndroidRuntime:       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
E AndroidRuntime:       at android.app.Activity.startIntentSenderForResultInner(Activity.java:5473)
E AndroidRuntime:       at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
E AndroidRuntime:       at androidx.fragment.app.c.startIntentSenderForResult(FragmentActivity.java:117637130)
E AndroidRuntime:       at androidx.core.app.b.a(ActivityCompat.java:134479878)
E AndroidRuntime:       at androidx.fragment.app.c.startIntentSenderFromFragment(FragmentActivity.java:134479926)
E AndroidRuntime:       at androidx.fragment.app.c$a.a(FragmentActivity.java:134414350)
E AndroidRuntime:       at androidx.fragment.app.Fragment.startIntentSenderForResult(Fragment.java:117702671)
E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.d.a.c(GooglePhoneHintHelper.java:393326)
E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.d.a.a(GooglePhoneHintHelper.java:16842754)
E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.v2.ui.a.u.m(PhoneLoginFragment.kt:262181)
E AndroidRuntime:       at com.ss.android.ugc.aweme.account.login.v2.ui.a.u.onViewCreated(PhoneLoginFragment.kt:34013476)
E AndroidRuntime:       at androidx.fragment.app.i.a(FragmentManager.java:1471)
E AndroidRuntime:       at androidx.fragment.app.i.a(FragmentManager.java:31)
E AndroidRuntime:       at androidx.fragment.app.i.c(FragmentManager.java:17301542)
E AndroidRuntime:       at androidx.fragment.app.i.a(FragmentManager.java:1852)
E AndroidRuntime:       at androidx.fragment.app.a.f(BackStackRecord.java:393378)
E AndroidRuntime:       at androidx.fragment.app.i.b(FragmentManager.java:67698726)
E AndroidRuntime:       at androidx.fragment.app.i.a(FragmentManager.java:2411)
E AndroidRuntime:       at androidx.fragment.app.i.b(FragmentManager.java:34078808)
E AndroidRuntime:       at androidx.fragment.app.i.b(FragmentManager.java:2243)
E AndroidRuntime:       at androidx.fragment.app.a.e(BackStackRecord.java:196614)
E AndroidRuntime:       at androidx.fragment.app.l.finishUpdate(FragmentStatePagerAdapter.java:16908292)
E AndroidRuntime:       at com.ss.android.ugc.aweme.views.g.finishUpdate(DelegatingFragmentPagerAdapter.java:16908290)
E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:17301922)
E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:65538)
E AndroidRuntime:       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:34013397)
E AndroidRuntime:       at com.ss.android.ugc.aweme.views.RtlViewPager.onMeasure(RtlViewPager.java:33816618)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E AndroidRuntime:       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E AndroidRuntime:       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
E AndroidRuntime:       at android.view.View.measure(View.java:25086)
E AndroidRuntime:       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
E AndroidRuntime:       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
E AndroidRuntime:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
E AndroidRuntime:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
E AndroidRuntime:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
E AndroidRuntime:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
E AndroidRuntime:       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
E AndroidRuntime:       at android.view.Choreographer.doFrame(Choreographer.java:726)
E AndroidRuntime:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
E AndroidRuntime:       at android.os.Handler.handleCallback(Handler.java:883)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:100)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:214)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:7356)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by Alanon202** [comment]
I believe this issue and similar issues with other apps, are caused by updates to Play Services and how they handle logging in when also offering google log in options. The solution I’ve found is to use an older version of the app (for TikTok specifically I used version 14.4.5). So far I’ve had good luck with every app I’ve tried.

So, use a sufficiently old version to log in, then upgrade it and it will stick. As long as you back up the app, or never clear all data (you can still clean the cache), you’ll be good. This isn’t really a solution, more of a workaround, but I’m not sure that a real solution will ever be possible. Hope this helps.

**Comment by 532910** [comment]
I wasn't able to login with 14.4.5, but 9.0.0 did the trick. Thank you!

**Comment by adil192** [comment]
TikTok now blocks you logging in from old versions of the app, but I could log in (on the latest version: 20.0.4) after installing the modded play store through NanoDroid.

**Comment by brxken128** [comment]
This issue is still very much a problem and sadly none of these "fixes" have worked for me on 20.9.2.

Downgrading the APK (to something **extremely low**, signing in and installing a newer version worked but resulted in many issues (such as tiktok.com links not being recognized by the app) and even font issues.

It's not just TikTok that has an issue like this, and it's the main reason why I (unfortunately) can't commit to fully using this project.
