### ISSUE TITLE
[microG 0.1.0gf64bf6] frequent crash messages

### ISSUE THREAD

**Issue by herrdeh** [microg/GmsCore#1380]
**Affected app**
Name: all
Package id: all

**Describe the bug**
Several times a day, I get a crash message. It seems to happen more likely with RAM-consuming apps acting.

**To Reproduce**
Cannot be reproduces reliably.

**Function**
Function seems to be fine - no problems could be notified.

**System**
Android Version: 7.1.2
Custom ROM: LineageOS 14.1

**microG**
microG Core version: 0.1.0-10-gf64bf6 and 0.1.0-4-g0ca6fb2
microG Self-Check results: All ticked - exept SMS, which is not activated

**Additional context**
Phone is LG G3 - *1GB of RAM only*. My guess is I could be a "short-of RAM"-problem.

**Comment by nift4** [comment]
There is no such version of GmsCore, did you mean DroidGuard Helper?

**Comment by DarkPhoenix2704** [comment]
@herrdeh There is no problem with Microg . It is due to low ram on your device. Also can you please close this issue

**Comment by herrdeh** [comment]
@nift4: You're right - wrong line I copied from. I corrected version numbers above.
@DarkPhoenix2704: I downgraded to see whether with 0.2.15 crashes still occur. And I tried to reduce RAM consuming apps - which is not so easy these days. 
Will report back.

**Comment by nift4** [comment]
One thing is sure: microG should *not* crash on low RAM (except android's lowmemorykiller is broken and there is an OutOfMemoryException). That's a bug. Logcat would be best.

**Comment by DarkPhoenix2704** [comment]
@herrdeh Can you provide a valid logcat

**Comment by herrdeh** [comment]
I will ASAP. At the moment, the downgrade experiment made my location services disfunctional; I asked for help at [xda-devs](https://forum.xda-developers.com/t/app-microg-gmscore-lightweight-free-software-clone-of-google-play-services.3217616/post-84417413).

**Comment by herrdeh** [comment]
Sorry for the delayed reply. I couldnt make microG work again, only using "nanodroid" helped in the end. Now I tried to collect logcats (was not familiar with "alogcat" before), but these bits are quite small, I doubt they are useful. I tried to find out how I can produce longer logs, but failed. So have a look....

[alogcat.2021-02-10-12-24-54+0100.txt](https://github.com/microg/GmsCore/files/5977168/alogcat.2021-02-10-12-24-54%2B0100.txt)
[alogcat.2021-02-10-12-25-04+0100.txt](https://github.com/microg/GmsCore/files/5977169/alogcat.2021-02-10-12-25-04%2B0100.txt)
[alogcat.2021-02-10-12-41-09+0100.txt](https://github.com/microg/GmsCore/files/5977170/alogcat.2021-02-10-12-41-09%2B0100.txt)
[alogcat.2021-02-10-13-19-41+0100.txt](https://github.com/microg/GmsCore/files/5977171/alogcat.2021-02-10-13-19-41%2B0100.txt)
[alogcat.2021-02-10-18-41-25+0100.txt](https://github.com/microg/GmsCore/files/5977172/alogcat.2021-02-10-18-41-25%2B0100.txt)
[alogcat.2021-02-11-06-47-55+0100.txt](https://github.com/microg/GmsCore/files/5977173/alogcat.2021-02-11-06-47-55%2B0100.txt)
[alogcat.2021-02-11-07-39-44+0100.txt](https://github.com/microg/GmsCore/files/5977174/alogcat.2021-02-11-07-39-44%2B0100.txt)
[alogcat.2021-02-11-12-09-09+0100.txt](https://github.com/microg/GmsCore/files/5977175/alogcat.2021-02-11-12-09-09%2B0100.txt)
[alogcat.2021-02-12-09-00-46+0100.txt](https://github.com/microg/GmsCore/files/5977176/alogcat.2021-02-12-09-00-46%2B0100.txt)
[alogcat.2021-02-13-15-48-58+0100.txt](https://github.com/microg/GmsCore/files/5977177/alogcat.2021-02-13-15-48-58%2B0100.txt)
[alogcat.2021-02-14-08-53-11+0100.txt](https://github.com/microg/GmsCore/files/5977178/alogcat.2021-02-14-08-53-11%2B0100.txt)

**Comment by herrdeh** [comment]
Crashes still happen several times a day which is annoying. Are these logcat files useful? - In case not, please let me know how to provide better ones.

**Comment by token0** [comment]
I get this same error frequently:

**PackageName:** 
com.google.android.gms

**Description:** 
java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@fd809f1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference

[system_app_crash@1615376764715.txt](https://github.com/microg/GmsCore/files/6115669/system_app_crash%401615376764715.txt)

**Comment by nift4** [comment]
Those logs are trash. They are aLogCat-scoped (only logs from the recording app because it's too old). Use MatLog Libre and give it root.

**Comment by herrdeh** [comment]
@nift4 
Thank you. I ever felt as if alogcat cannot provide useful things. I tried as you advised, after a crash message occuring I switched to MatLog and saved the file - hope this was the thing to do...

I'm uploading last 2 minutes before crash message from each log, hope that's now good... Please let me know if I should do anything else.


[log1.txt](https://github.com/microg/GmsCore/files/6137114/log1.txt)
[LOG2.TXT](https://github.com/microg/GmsCore/files/6137115/LOG2.TXT)
[LOG3.TXT](https://github.com/microg/GmsCore/files/6137116/LOG3.TXT)

**Comment by nift4** [comment]
Interesting part of log1:

```03-12 13:09:46.798 E/AndroidRuntime(30986): FATAL EXCEPTION: main
03-12 13:09:46.798 E/AndroidRuntime(30986): Process: com.google.android.gms:persistent, PID: 30986
03-12 13:09:46.798 E/AndroidRuntime(30986): java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@aa6c86e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3368)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.os.Looper.loop(Looper.java:154)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at java.lang.reflect.Method.invoke(Native Method)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
03-12 13:09:46.798 E/AndroidRuntime(30986): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at androidx.legacy.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:126)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
03-12 13:09:46.798 E/AndroidRuntime(30986): 	... 9 more```

**Comment by herrdeh** [comment]
Do you need more logs?

**Comment by nift4** [comment]
I'm not an developer. You need to ask @mar-v-in

**Comment by nift4** [comment]
I can tell it's an problem with an app trying to register for push notifications.

**Comment by mar-v-in** [comment]
Should be fixed as of ecfe3da3f7573e3d66a1ad9c12e8a08bbeae307b

**Comment by herrdeh** [comment]
Das klingt super - freu' mich sehr!
Sounds great - I'm looking forward!

Cheers,
Wolf

**Comment by ale5000-git** [comment]
The logcat point to KDE Connect and Threema.
Does it still crash even with KDE Connect disabled?

Relevant part:
```
[05-11 15:54:58.728 1572:1761 E/AndroidRuntime]
*** FATAL EXCEPTION IN SYSTEM PROCESS: android.fg
java.lang.IllegalStateException: android.os.ServiceSpecificException: Operation not permitted (code 1)
	at com.android.server.NetworkManagementService.setAppOnInterfaceLocked(NetworkManagementService.java:1604)
	at com.android.server.NetworkManagementService.updateAppOnInterfaceCallback(NetworkManagementService.java:1543)
	at com.android.server.NetworkManagementService.access$500(NetworkManagementService.java:125)
	at com.android.server.NetworkManagementService$1.lambda$onLinkPropertiesChanged$0$NetworkManagementService$1(NetworkManagementService.java:405)
	at com.android.server.-$$Lambda$NetworkManagementService$1$cEe7AIGZabKkElb0YvNi_jszJbI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)
Caused by: android.os.ServiceSpecificException: Operation not permitted (code 1)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.net.INetd$Stub$Proxy.bandwidthRemoveRestrictAppOnInterface(INetd.java:3991)
	at com.android.server.NetworkManagementService.setAppOnInterfaceLocked(NetworkManagementService.java:1594)
	... 9 more

[05-11 15:54:58.819 0:0 E/[20210511_15:54:58.819192]@0 binder_alloc]
1572: binder_alloc_buf, no vma

[05-11 15:54:58.821 18014:26194 E/AndroidRuntime]
FATAL EXCEPTION: Thread-27
Process: org.kde.kdeconnect_tp, PID: 18014
DeadSystemException: The system died; earlier logs will point to the root cause

[05-11 15:54:58.823 6751:25808 E/AndroidRuntime]
FATAL EXCEPTION: AsyncTask #123
Process: ch.threema.app, PID: 6751
DeadSystemException: The system died; earlier logs will point to the root cause
```

**Comment by ale5000-git** [comment]
@hubbty: your problem is probably different, maybe it is better open a separate issue.

**Comment by hubbty** [comment]
Thank you @ale5000-git !  I normally run KDE connect only while I want to use it and force stop it afterwards. Threema on the other hand runs all the time. There are a few additonal FATAL EXCEPTIONS in logcat (what I understand related to Silence aka smssecure) but I did not notice another soft crash (or how you might call it) in the meantime. So maybe its not worth to open a new issue.

I am a bit concerned to install that nightly. If this would not work somehow, how could I get back to the latest version? Via F-Droid? It usually does not allow downgrades  and I assume, it would consider this to be a downgrade.

**Comment by ale5000-git** [comment]
The nightly is done by mar-v-in so it has the same signature of official stable microG.
I'm not sure about downgrades (you can possibly do it with adb) but you can simply update to the new stable when get released.

**Comment by hubbty** [comment]
I installed the nightly (0.2.19.211515-1) and since then there has no "soft crash" occurred. But there ist still a hell of lot of error messages (I guess most of them not related to microG).

**Comment by ale5000-git** [comment]
I suggest to open a new issue and post the full logcat since it is a different issue and mostly noone will read this one that is closed.
