### ISSUE TITLE
[com.santander.app] ClassNotFoundException com.google.android.gms.analytics.AnalyticsService

### ISSUE THREAD

**Issue by grote** [microg/GmsCore#1417]
**Affected app**
Name: Santander banking app
Package id: com.santander.app

**Describe the bug**
When opening a section of the app, it reproducibly crashes.

**To Reproduce**
Needs an account with that bank.

**System**
Android Version: 11
Custom ROM: CalyxOS
**microG**
microG Core version: [e.g. 0.2.17.204714-14]
microG Self-Check results: All ticked

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.santander.app, PID: 25884
    java.lang.RuntimeException: Unable to create service com.google.android.gms.analytics.AnalyticsService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.analytics.AnalyticsService" on path: DexPathList[[zip file "/data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/base.apk"],nativeLibraryDirectories=[/data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/lib/arm64, /data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
        at android.app.ActivityThread.access$1500(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.analytics.AnalyticsService" on path: DexPathList[[zip file "/data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/base.apk"],nativeLibraryDirectories=[/data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/lib/arm64, /data/app/~~OJXGm2BXYcGSOCFdp0OPEA==/com.santander.app-PJXehZ_MOv-KXaEeMCFdzA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
        at android.support.v4.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4177)
        at android.app.ActivityThread.access$1500(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by Sapiosenses** [comment]
microG does not support the Google Analytics APIs. This is by design.

I haven't personally seen a case where an app crashed over it, but in any case apps will not get Google Analytics data if installed on a ROM using microG instead of Gapps.

https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status

**Comment by grote** [comment]
Seems to be related to [background dispatching on apps running on non-Google Play devices](https://developers.google.com/analytics/devguides/collection/android/v4/dispatch#background) which the developers of this app probably forgot to add.

A good solution would then be to make the app think that play services is available so it tries the normal non-working dispatching.

**Comment by grote** [comment]
Here's a Google Analytics example app that does register the proper service, but could be used for testing [with the service removed](https://github.com/googleanalytics/cute-pets-example-android-app/blob/0cf68647c41aa239de3b989ba63c312b7ddf3e8d/app/src/main/AndroidManifest.xml#L40).

**Comment by grote** [comment]
Unfortunately, the test app works. Even when using the same version of the analytics library and the service removed from the manifest:

```
W/GAv4: AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.

E/GAv4: Successfully bound to service but never got onServiceConnected callback
```

The app itself logs this when starting:

```
2021-06-07 17:16:54.576 18225-18358/com.santander.app I/GAv4: GoogleAnalytics.setLogger() is deprecated. To enable debug logging, please run:
    adb shell setprop log.tag.GAv4 DEBUG
2021-06-07 17:16:59.595 18225-18367/com.santander.app E/GAv4: Successfully bound to service but never got onServiceConnected callback
2021-06-07 17:16:59.612 18225-18367/com.santander.app E/GAv4: Job execution failed: java.lang.IllegalArgumentException: No such service ComponentInfo{com.santander.app/com.google.android.gms.analytics.AnalyticsJobService}
```

which is a clue, because MicroG currently does not have a `.gms.analytics.AnalyticsJobService`.

**Comment by Sapiosenses** [comment]
> Seems to be related to [background dispatching on apps running on non-Google Play devices](https://developers.google.com/analytics/devguides/collection/android/v4/dispatch#background) which the developers of this app probably forgot to add.
> 
> A good solution would then be to make the app think that play services is available so it tries the normal non-working dispatching.

I am not familiar with the details because I'm not a coder.

But one of the core microG functions is to spoof the existence of Google Play services so apps that are written to rely on them can still launch and (depending on various details) still run to one extent or the other.

But you could be right about that particular function.
