### ISSUE TITLE
[com.pedidosya] Attempting to view the delivery location crashes Mapbox (pixelRatio may not be <= 0)

### ISSUE THREAD

**Issue by PABLEXWorld** [microg/GmsCore#1453]
**Affected app**
Name: PedidosYa
Package id: com.pedidosya

**Describe the bug**
After a delivery is requested through the app, you can view the location of the delivery as it makes its way to the destination. Attempting to do so crashes under Mapbox with the following traceback: 
FATAL EXCEPTION: main
java.lang.Error: pixelRatio may not be <= 0
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddImages(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.addImages(NativeMapView.java:933)
at com.mapbox.mapboxsdk.maps.Style.addImage(Style.java:379)
at com.mapbox.mapboxsdk.maps.Style.addImage(Style.java:319)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl$registerBitmap$1$1.invoke(BitmapDescriptorFactory.kt:78)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl$registerBitmap$1$1.invoke(BitmapDescriptorFactory.kt:33)
at org.microg.gms.maps.mapbox.GoogleMapKt.runOnMainLooper(GoogleMap.kt:65)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl$registerBitmap$1.onStyleLoaded(BitmapDescriptorFactory.kt:77)
at com.mapbox.mapboxsdk.maps.MapboxMap.getStyle(MapboxMap.java:119)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl.registerBitmap(BitmapDescriptorFactory.kt:76)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl.fromBitmap(BitmapDescriptorFactory.kt:156)
at com.google.android.gms.maps.model.internal.IBitmapDescriptorFactoryDelegate$Stub.onTransact(IBitmapDescriptorFactoryDelegate.java:139)
at org.microg.gms.maps.mapbox.model.BitmapDescriptorFactoryImpl.onTransact(BitmapDescriptorFactory.kt:167)
at android.os.Binder.transact(Binder.java:1043)
at com.google.android.gms.internal.maps.zza.zza(SourceFile:4)
at com.google.android.gms.internal.maps.zzg.zza(SourceFile:18)
at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(SourceFile:1)
at com.pedidosya.location.view.maps.model.BitmapDescriptorFactory.fromBitmap(SourceFile:2)
at com.pedidosya.orderstatus.businesslogic.handlers.map.OrderStatusMap.addMarkerIcon(SourceFile:3)
at com.pedidosya.orderstatus.businesslogic.handlers.map.OrderStatusMap.drawWayPoints(SourceFile:7)
at com.pedidosya.orderstatus.view.fragments.OrderStatusMapFragment.handleMapConnectionState(SourceFile:33)
at com.pedidosya.orderstatus.view.fragments.OrderStatusMapFragment.access$handleMapConnectionState(SourceFile:1)
at com.pedidosya.orderstatus.view.fragments.OrderStatusMapFragment$onViewCreated$1.invoke(SourceFile:2)
at com.pedidosya.orderstatus.view.fragments.OrderStatusMapFragment$onViewCreated$1.invoke(SourceFile:1)
at com.pedidosya.chat.kotlinextensions.ViewModelFatoryExtensionsKt$observe$1.onChanged(SourceFile:1)
 at androidx.lifecycle.LiveData.considerNotify(SourceFile:6)
at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:8)
at androidx.lifecycle.LiveData.setValue(SourceFile:4)
at androidx.lifecycle.MutableLiveData.setValue(SourceFile:1)
at androidx.lifecycle.LiveData$1.run(SourceFile:5)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**To Reproduce**
1. Pick a restaurant.
2. Request anything.
3. After you succesfully send it, there's only one button displayed that opens the crashing map screen.
4. If you don't press Back to interrupt the loading and go back to the main screen, you'll crash here.

**Expected behavior**
The map is expected to load.

**System**
Android Version: 11
Custom ROM: crDroid 7.4
Device: Xiaomi Mi A2 (jasmine_sprout)

**microG**
microG Core version: 0.2.18.204714
microG Self-Check results: All ticked

**Comment by PABLEXWorld** [comment]
No longer reproducible. Both PedidosYa and microg have since been updated, and this crash no longer occurs.
