### ISSUE TITLE
com.lwcx.lw061 NPE com.google.android.gms.maps.internal.IUiSettingsDelegate.setMyLocationButtonEnabled

### ISSUE THREAD

**Issue by grote** [microg/GmsCore#1482]
**Affected app**
Name: Eachine Pro
Package id: com.lwcx.lw061

**Describe the bug**
Start the app and get a crash.

**To Reproduce**
1. Start app
2. Select either indoor or outdoor mode
3. Crash

**Expected behavior**
App should not crash and does not on a stock Google phone with play services.

**System**
Android Version: 11
Custom ROM: CalyxOS

**Additional context**

```
05-27 11:52:16.940  2380  2380 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lwcx.lw061/com.lewei.multiple.main.LW93MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IUiSettingsDelegate.setMyLocationButtonEnabled(boolean)' on a null object reference
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-27 11:52:16.940  2380  2380 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IUiSettingsDelegate.setMyLocationButtonEnabled(boolean)' on a null object reference
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.google.android.gms.maps.UiSettings.setMyLocationButtonEnabled(Unknown Source:2)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.lewei.map.GooglesMap.initMap(GooglesMap.java:404)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.lewei.map.GooglesMap.<init>(GooglesMap.java:200)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at com.lewei.multiple.main.LW93MainActivity.onCreate(LW93MainActivity.java:614)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8000)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7984)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
05-27 11:52:16.940  2380  2380 E AndroidRuntime:        ... 11 more
```

**Comment by grote** [comment]
[`getUiSettings()`](https://github.com/microg/GmsCore/blob/ad12bd5de4970a6607a18e37707fab9f444593a7/play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt#L426) gets called before [Mapbox returned its map asynchrousously](https://github.com/microg/GmsCore/blob/ad12bd5de4970a6607a18e37707fab9f444593a7/play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt#L554). So we get `null` instead of `UiSettings`. 

Best solution would be to decouple the interfaces, so we can always provide them. We probably would have to replay them once map box is ready. Or maybe one could use a call back flow with a suspend function and wait until mapbox is ready.
