### ISSUE TITLE
[com.spotlightsix.zentimerlite2]  Insight Timer doesn't work on Lineage 18.1

### ISSUE THREAD

**Issue by rehork** [microg/GmsCore#1496]
**Affected app**
Name: Insight Timer
Package id: com.spotlightsix.zentimerlite2

**Describe the bug**
Cannot launch Insight Timer application on Android 11 with MicroG installed

**To Reproduce**
1. Install Insight Timer application (e.g. ver. 15.14.1)
2. Launch the application
3. See an error: "**The version of the Google Play services installed on this device is not authentic**"

**Expected behavior**
The application should start without errors and also it should be possible to sign in to an own profile.

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**microG**
microG Core version: [e.g. 0.2.20.212158]
microG Self-Check results: [All ticked]

**Additional context**
Other applications (e.g Spotify or internet radio applications which need G Play services) working fine without errors. With the Insight Timer issue exists. Also On Lineage 17.1 with the same version of MicroG (installed in the same way), everything works as expected. In the past it was similar issues with this application which were eventually solved. 

**Logcat**
07-01 22:02:34.099  4617  5625 E AndroidRuntime: FATAL EXCEPTION: grpc-okhttp-0
07-01 22:02:34.099  4617  5625 E AndroidRuntime: Process: com.spotlightsix.zentimerlite2, PID: 4617
07-01 22:02:34.099  4617  5625 E AndroidRuntime: java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=firestore.googleapis.com/216.58.215.74,port=443,localPort=35267]
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.r.e.a(SourceFile:7)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.r.e.d(SourceFile:1)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.j$a.a(SourceFile:11)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.j$a.b(SourceFile:1)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.m.a(SourceFile:8)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.i1.h$d.run(SourceFile:17)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at k.c.h1.y1.run(SourceFile:2)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 22:02:34.099  4617  5625 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-01 22:02:34.317  4617  4617 W Appboy v12.0.0 .bo.app.b4: Email address is not valid: 
07-01 22:02:34.335  4617  5636 W FirebaseInstanceId: Failed to find package android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
07-01 22:02:34.338  4617  5636 W Metadata: Failed to find package android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
07-01 22:02:34.338  4617  5636 E Metadata: Google Play services missing or without correct permission.
07-01 22:02:34.497  4617  4617 W GooglePlayServicesUtil: com.spotlightsix.zentimerlite2 requires the Google Play Store, but it is missing.
07-01 22:02:34.500  4617  5547 W FA      : setCurrentScreen cannot be called with the same class and name
07-01 22:02:34.646  4617  4617 W Appboy v12.0.0 .com.appboy.support.CustomAttributeValidationUtils: Custom attribute key cannot be blocklisted attribute: device_language.
07-01 22:02:34.646  4617  4617 W Appboy v12.0.0 .bo.app.b4: Custom attribute key cannot be null.
07-01 22:02:34.674  2269  2269 W Choreographer: Frame time is 0.030781 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
07-01 22:02:34.982  1226  3106 W ActivityTaskManager:   Force finishing activity com.spotlightsix.zentimerlite2/co.insight.timer2.LauncherActivity
07-01 22:02:35.031  1226  2274 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10039?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
07-01 22:02:35.046   349   349 E lowmemorykiller: Error writing /proc/4617/oom_score_adj; errno=22
07-01 22:02:35.085   349   349 E lowmemorykiller: Error writing /proc/4617/oom_score_adj; errno=22
07-01 22:02:35.119  1226  3106 W InputDispatcher: Attempted to unregister already unregistered input channel '76412ab com.spotlightsix.zentimerlite2/co.insight.timer2.LauncherActivity (server)'
07-01 22:02:35.130  1226  2360 W WindowManager: Failed looking up window session=Session{b258b1c 4617:u0a10072} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5443 com.android.server.wm.WindowState$DeathRecipient.binderDied:2818 android.os.IBinder$DeathRecipient.binderDied:305 
07-01 22:02:35.135  1226  1413 W ActivityManager: setHasOverlayUi called on unknown pid: 4617
07-01 22:02:35.549  5656  5656 E x.zentimerlite: Not starting debugger since process cannot load the jdwp agent.
07-01 22:02:35.683  5656  5656 W ComponentDiscovery: Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
07-01 22:02:35.791  5656  5680 E FirebaseInstanceId: Google Play services missing or without correct permission.
07-01 22:02:35.828  5656  5681 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
07-01 22:02:35.828  5656  5681 W DynamiteModule: Failed to retrieve remote module version.
07-01 22:02:35.830  5656  5681 E DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
07-01 22:02:35.843  5656  5681 E DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
07-01 22:02:35.921  5656  5696 W GooglePlayServicesUtil: com.spotlightsix.zentimerlite2 requires the Google Play Store, but it is missing.
07-01 22:02:35.976  5656  5695 W GooglePlayServicesUtil: com.spotlightsix.zentimerlite2 requires the Google Play Store, but it is missing.
07-01 22:02:35.976  5656  5695 W FA      : Service invalid
07-01 22:02:36.000  5656  5656 W g.h.t   : Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
07-01 22:02:36.000  5656  5656 W g.h.t   : You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
07-01 22:02:36.113  1226  3088 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
07-01 22:02:36.254  5656  5656 E mParticle: Failed to get MParticle instance, getInstance() called prior to start().
07-01 22:02:36.327  5656  5656 E x.zentimerlite: Invalid ID 0x00000000.
07-01 22:02:36.409  5656  5742 W Appboy v12.0.0 .bo.app.p1: Firebase Cloud Messaging requires the Google Play Store to be installed.
07-01 22:02:36.409  5656  5742 W Appboy v12.0.0 .com.appboy.Appboy: Firebase Cloud Messaging requirements not met. Braze will not register for Firebase Cloud Messaging.
07-01 22:02:36.613  1226  3112 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found
07-01 22:02:36.795  5656  5695 W x.zentimerlite: Verification of java.util.List g.j.a.e.l.b.da.a(java.lang.String, java.util.List, java.util.List, java.lang.Long, java.lang.Long) took 112.736ms (25209.12 bytecodes/s) (77304B approximate peak alloc)
07-01 22:02:37.174  5656  5695 W FA      : Callable skipped the worker queue.

**Comment by rehork** [comment]
Logs have been added.

**Comment by rehork** [comment]
Application Insight Timer requires MicroG installed as system component, so the only solution is installation via Magisk [module](https://github.com/Magisk-Modules-Repo/microg_installer).
It has been solved, though.
