### ISSUE TITLE
[com.google.android.apps.maps] Google Maps crashes due to SettingsProvider

### ISSUE THREAD

**Issue by benwaffle** [microg/GmsCore#1503]
**Affected app**
Name: Google Maps
Package id: com.google.android.apps.maps

**Describe the bug**
I updated microg to 0.2.20.212158 from fdroid because Maps has been crashing due to missing cronet. Now there is a new crash, see log below.

**To Reproduce**
1. Open google maps

**Expected behavior**
No crash.

**System**
Android Version: 10
Custom ROM: microg lineage build 17.1-20210328-microG-guacamole

**microG**
microG Core version: 0.2.20.212158
microG Self-Check results: All ticked

**Additional context**
```
FATAL EXCEPTION: DefaultPool5
Process: com.google.android.apps.maps, PID: 1937
java.lang.SecurityException: Permission Denial: reading org.microg.gms.settings.SettingsProvider uri content://org.microg.gms.settings/auth from pid=1937, uid=10356 requires the provider be exported, or grantUriPermission()
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at cwm.xX(PG:3)
	at cmvj.g(PG:5)
	at comx.a(PG:5)
	at conc.i(PG:11)
	at conc.h(PG:23)
	at comw.a(PG:3)
	at buol.b(PG:1)
	at buol.c(PG:3)
	at bvby.d(PG:2)
	at bvca.a(PG:10)
	at bulg.e(PG:2)
	at bule.j(PG:1)
	at bule.k(PG:5)
	at bule.e(PG:14)
	at bvby.c(PG:5)
	at bvap.a(PG:25)
	at dfbl.a(PG:1)
	at dghm.c(PG:2)
	at dgho.run(PG:9)
	at bwkb.run(PG:1)
	at bwlm.run(PG:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at bwlc.run(PG:4)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by aer0nix** [comment]
I have same error but with Play Market
@grote , any ideas?

**Comment by s644** [comment]
I have the same problem with play store as @aer0nix since the latest update yesterday. I've already cleared dalvik cache and removed data for play store, but when I open the store, the app only shows the splash.

**Affected app**
Name: Play Store
Package id: com.android.vending

**To Reproduce**
Steps to reproduce the behavior:
1. Update to 0.2.20.212158 via f-droid
2. start play store

**System**
Android Version: 11
Custom ROM: Official LineageOS 18.1

**microG**
microG Core version: 0.2.20.212158
microG Self-Check results: All ticked

**Additional context**
```
07-01 08:36:46.910 D/GmsAuthenticator(4559): getAuthToken: Account {name=__________________@gmail.com, type=com.google}, oauth2:https://www.googleapis.com/auth/experimentsandconfigs, Bundle[{androidPackageName=com.android.vending, callerPid=17905, callerUid=10168}]
07-01 08:36:46.914 W/GmsAuthenticator(4559): java.lang.SecurityException: Permission Denial: reading org.microg.gms.settings.SettingsProvider uri content://org.microg.gms.settings/auth from pid=0, uid=1000 requires the provider be exported, or grantUriPermission()
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentResolver.query(ContentResolver.java:1183)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentResolver.query(ContentResolver.java:1115)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.content.ContentResolver.query(ContentResolver.java:1071)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at org.microg.gms.settings.SettingsContract.getSettings(SettingsContract.kt:107)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at org.microg.gms.auth.AuthPrefs.isTrustGooglePermitted(AuthPrefs.kt:11)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at org.microg.gms.auth.AuthManager.requestAuth(AuthManager.java:203)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at org.microg.gms.auth.loginservice.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:97)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:244)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:282)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
07-01 08:36:46.914 W/GmsAuthenticator(4559): 	at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by mar-v-in** [comment]
Can you please check if commit https://github.com/microg/GmsCore/commit/a431fea9bb1be153661fab9f78a8672ca62ebacd (build uploaded to http://microg.org/dl/core-nightly.apk) fixes this issue for you?

**Comment by s644** [comment]
I'd like to test it, but i can't install the .apk over f-droid version :/

**Comment by ale5000-git** [comment]
@s644: Why? The F-Droid version should have the same signature.

**Comment by s644** [comment]
I don't know. The setup starts, but after showing the progressbar, the installer just says: "App wasn't installed"

**Comment by s644** [comment]
I used minmicro with magisk to install the microg framework. Updates via f-droid working without problems. Just in case this could be related to the problem....

```
07-01 11:21:41.261 E/AppIntegrityManagerServiceImpl(1131): Installer is package installer but originating UID not found.
07-01 11:21:41.063 E/TEST    (4559): exposure_scanner_enabled = 1
07-01 11:21:41.271 I/Finsky  (18525): [2] aefm.a(7): Verification requested, id = 10
07-01 11:21:41.291 W/RuleEvaluation(1131): Integrity rule files are not available.
07-01 11:21:41.292 I/PackageManager(1131): Integrity check passed for file:///data/app/vmdl12542435.tmp
07-01 11:21:41.424 I/Finsky  (18525): [228] VerifyAppsInstallTask.c(22): Skipping verification. Disabled by user setting
07-01 11:21:41.424 I/Finsky  (18525): [228] VerifyAppsInstallTask.c(23): Verify: Skipping anti malware verification due to pre-check failure. package=com.google.android.gms
07-01 11:21:41.430 I/Finsky  (18525): [228] VerifyAdvancedProtectionInstallTask.c(1): Verify AP install started
07-01 11:21:41.431 I/Finsky  (18525): [228] VerifyAdvancedProtectionInstallTask.c(2): Allowing install because there are no Advanced Protection users
07-01 11:21:41.432 I/Finsky  (18525): [2] VerifyAdvancedProtectionInstallTask.hT(2): Reported verification result: ALLOW
07-01 11:21:41.432 I/Finsky  (18525): [228] VerifyPerSourceInstallationConsentInstallTask.c(3): PSIC verification started with installer uid: 10090 package name: com.android.packageinstaller, originating uid: -1
07-01 11:21:41.434 I/Finsky  (18525): [228] VerifyPerSourceInstallationConsentInstallTask.c(9): Skipping logging for attempted installation. The GPP Installer warnings experiment for O+ is disabled.
07-01 11:21:41.435 I/Finsky  (18525): [2] VerifyInstallTask.c(15): Verifying id=10, result=1
07-01 11:21:41.438 I/Finsky  (18525): [2] VerifyInstallTask.hT(6): Verification complete: id=10, package_name=com.google.android.gms
07-01 11:21:41.463 W/PackageManager(1131): Package com.google.android.gms is a persistent app. Persistent apps are not updateable.
07-01 11:21:41.465 E/installd(935): Couldn't opendir /data/app/vmdl12542435.tmp: No such file or directory
07-01 11:21:41.465 E/installd(935): Failed to delete /data/app/vmdl12542435.tmp: No such file or directory
07-01 11:21:41.475 I/ActivityTaskManager(1131): START u0 {dat=file:///data/user_de/0/com.android.packageinstaller/no_backup/package8882160489664181592.apk flg=0x2000000 cmp=com.android.packageinstaller/.InstallFailed (has extras)} from uid 10090
```

**Comment by mar-v-in** [comment]
@s644
This seems to be some weirdness in Android. Can you try the following:
```
adb push core-nightly.apk /data/local/tmp/core-nightly.apk
adb shell pm install-create -r --staged # This returns a session id in brackets
adb shell pm install-write *session-id* base /data/local/tmp/core-nightly.apk
adb shell pm install-commit *session-id*
adb shell rm /data/local/tmp/core-nightly.apk
adb reboot
```

**Comment by s644** [comment]
Thx, everything is working again :)

**Comment by Ammako** [comment]
> This seems to be some weirdness in Android. Can you try the following:

Doesn't work in all versions of Android

`Error: java.lang.IllegalArgumentException: Unknown option --staged`

That being said I just rename core-nightly.apk to base.apk and `adb push base.apk /data/app/com.google.android.gms-1`, reboot, and that does the job 😉

I suggest either 0.2.20 should be re-released to include these changes, or 0.2.20 should be replaced with emergency nightly release at least on f-droid repo. Just to avoid issues for other people.

**Comment by drrossum** [comment]
Maps still crashes instantaneous for me on commit d8e50cb, though this seems to be a different issue than before (in v0.20).

[debug.log](https://github.com/microg/GmsCore/files/6748392/debug.log)

**Comment by mar-v-in** [comment]
@drrossum can you open a new issue for that error please?

**Comment by mar-v-in** [comment]
@Ammako what Android version are you using?

**Comment by Ammako** [comment]
7.1.2

**Comment by reyis4402** [comment]
@mar-v-in How can I do this with the terminal

**Comment by mar-v-in** [comment]
@reyis4402 assuming you mean a terminal running on the phone, this needs to have root.
```
cp /sdcard/path/to/core-nightly.apk /data/local/tmp/core-nightly.apk
pm install-create -r --staged # This returns a session id in brackets
pm install-write *session-id* base /data/local/tmp/core-nightly.apk
pm install-commit *session-id*
rm /data/local/tmp/core-nightly.apk
```

**Comment by benwaffle** [comment]
Awesome, google maps works now!

**Comment by steadfasterX** [comment]
> Can you please check if commit [a431fea](https://github.com/microg/GmsCore/commit/a431fea9bb1be153661fab9f78a8672ca62ebacd) (build uploaded to https://microg.org/dl/core-nightly.apk) fixes this issue for you?

fixes my issue thanks!

```
08-18 03:29:04.984  2587  3183 D GmsAuthenticator: getAuthToken: Account {name=REMOVED, type=com.google}, oauth2:https://www.googleapis.com/auth/googleplay, Bundle[{androidPackageName=com.android.vending, callerPid=5582, callerUid=10026}]
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: java.lang.SecurityException: Permission Denial: reading org.microg.gms.settings.SettingsProvider uri content://org.microg.gms.settings/auth from pid=0, uid=1000 requires the provider be exported, or grantUriPermission()
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:635)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:504)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentResolver.query(ContentResolver.java:803)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentResolver.query(ContentResolver.java:753)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.content.ContentResolver.query(ContentResolver.java:711)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at org.microg.gms.settings.SettingsContract.getSettings(SettingsContract.kt:107)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at org.microg.gms.auth.AuthPrefs.isTrustGooglePermitted(AuthPrefs.kt:11)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at org.microg.gms.auth.AuthManager.requestAuth(AuthManager.java:203)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at org.microg.gms.auth.loginservice.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:97)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:246)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
08-18 03:29:04.991  2587  3183 W GmsAuthenticator: 	at android.os.Binder.execTransact(Binder.java:731)
```
