### ISSUE TITLE
Installing v0.2.21.212158 - "Caller has no access to session"

### ISSUE THREAD

**Issue by Sapiosenses** [microg/GmsCore#1507]
**Describe the bug**
Attempting update from 0.2.20.212158 to 0.2.21.212158. Error message "Caller has no access to session" in root shell.

**To Reproduce**

1) Attempt to update via F-droid with microG repo - installation fails
2) Download com.google.android.gms-212158042.apk from Github, copy to /data/local/tmp
3) Open local root shell, execute suggested commands, leaving out "adb shell" and substituting "path/to/play-services-core-212158042.apk" with path/name of actual apk as shown in step 2.

Notes:
On line 4, apparently the terminal buffer doesn't expand my 'tab' entry which in the original session expanded to the full filename.

On line 6, I forgot the "pm" command, entered the proper command on line 8

See copy of session under "additional context"

**Expected behavior**
No command error

**Screenshots**

**System**
Android Version: 10
Custom ROM: CarbonROM (CARBON-CR-8.0-PAX-RELEASE-enchilada-2021-0520-0035)

**Additional context**
:/ $ su
:/ # pm install-create -r --staged
Success: created install session [959212503]
pm install-write 959212503 base /data/local/tmp/com.google.and*
Success: streamed 51350698 bytes
:/ # install-commit 95921503
/system/bin/sh: install-commit: inaccessible or not found
127|:/ # pm install-commit 95921503
Security exception: Caller has no access to session 95921503

java.lang.SecurityException: Caller has no access to session 95921503
        at com.android.server.pm.PackageInstallerService.openSessionInternal(PackageInstallerService.java:708)
        at com.android.server.pm.PackageInstallerService.openSession(PackageInstallerService.java:698)
        at com.android.server.pm.PackageManagerShellCommand.doCommitSession(PackageManagerShellCommand.java:2805)
        at com.android.server.pm.PackageManagerShellCommand.runInstallCommit(PackageManagerShellCommand.java:1100)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:174)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22045)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4876)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4092)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
255|:/ #

**Comment by Sapiosenses** [comment]
Re-tried command sequence, worked fine this time, microG control panel reflects new version.

Sorry for the spam.
