### ISSUE TITLE
e.g. [de.materna.bbk.mobile.app] No GCM/FCM registration happens and Google registration is reset after reboot

### ISSUE THREAD

**Issue by rugk** [microg/GmsCore#1544]
**Affected app**
Name: e.g. Nina, Threema, …
Package id: e.g. de.materna.bbk.mobile.app, …

**Describe the bug**
The device registration is shown as disabled after a reboot (GCM/push is shown as enable though) and push does not work.

**To Reproduce**
0. Fresh device installation, backup partially restored with Seedvault, see https://github.com/seedvault-app/seedvault/issues/307
1. Enable device registration and push notifications.
2. Wait some time and try around… start apps to register.

Issue 1: The GCM registration seems to just disable itself after some time. I can re-enable it, but maybe that is the core problem here.
Issue 2: No matter what I do (I tried with asking for registration enabled and disabled), no app seems to actually register for push notifications. Nina is a good example and even shows a proper error.

I tested this also with Threema and other apps.

Please note two important things:
* [In the wiki](https://github.com/microg/GmsCore/wiki/Installation) I saw too late that you should reboot after you have enabled. Given microG was preinstalled in my CustomROM I did not consider to look there.
* Also, I wonder how compatible microG is with Seedvault, which installs all apps from apk's. Given this likely happens before any user could enable device registration in the microG settings (it is supposed to happen in the wizard), I wonder whether these things work well together.
  That said, as far as I understood it, microG only needs to be _installed_ before any other GCM app to make it work, it does not have to be _enabled_, does it? If so, then a preinstalled microG should of course not be a problem hmm…
  Also, to make sure this is not an issue, Nina was freshly installed.

**Expected behavior**
* The device registration should stay enabled.
* GCM/push notifications work.

**Screenshots**
N/A

**System**
Android Version: 11
Custom ROM: LineageOS for microG 18.1 2021-08-11
FP3 (Fairphone 3)

**microG**
microG Core version: 0.2.19.211515
microG Self-Check results: All ticked

**Additional context**
Logcat: https://gist.github.com/rugk/86677d587eed2f8e1b90621958d9efce

**Edit:** Ah, it just seems to reset the device registration at reboot for some reason… another logcat: https://gist.github.com/rugk/122f1eb17215a1d38a831edca5e48093

Same as logcat-6 above, but grepped a bit more to show some more relevant stuff I think:
```
grep -i -E "3931|GmsGcm" ~/Downloads/logcat6.txt
08-28 12:03:15.629  1451  1451 D Zygote  : Forked child process 3931
08-28 12:03:15.634  1588  1671 I ActivityManager: Start proc 3931:com.google.android.gms:persistent/u0a94 for broadcast {com.google.android.gms/org.microg.gms.gcm.TriggerReceiver}
08-28 12:03:15.697   900   938 I adbd    : jdwp connection from 3931
08-28 12:03:15.758  3931  3931 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
08-28 12:03:15.764  3931  3931 W .gms:persisten: ClassLoaderContext classpath size mismatch. expected=1, found=0 (PCL[/system/framework/org.lineageos.platform.jar*2696821020] | PCL[])
08-28 12:03:15.774  3931  3931 I .gms:persisten: The ClassLoaderContext is a special shared library.
08-28 12:03:15.798  3931  3931 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 12:03:15.799  3931  3931 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 12:03:15.801  3931  3931 I MultiDex: VM with version 2.1.0 has multidex support
08-28 12:03:15.801  3931  3931 I MultiDex: Installing application
08-28 12:03:15.801  3931  3931 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-28 12:03:15.808  3931  3931 I TetheringManager: registerTetheringEventCallback:com.google.android.gms
08-28 12:03:15.830  3931  3931 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:15.831  3931  3931 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=android.intent.action.BOOT_COMPLETED flg=0x89000010 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
08-28 12:03:15.858  3931  3931 W .gms:persisten: Accessing hidden field Landroid/content/Context;->DEVICE_IDLE_CONTROLLER:Ljava/lang/String; (greylist-max-o,test-api, reflection, denied)
08-28 12:03:15.861  3931  3931 W .gms:persisten: Accessing hidden method Landroid/os/IDeviceIdleController$Stub$Proxy;->addPowerSaveTempWhitelistApp(Ljava/lang/String;JILjava/lang/String;)V (greylist-max-o, reflection, denied)
08-28 12:03:15.869  3931  3931 D ExposureNotification: ServiceTrigger: Intent { act=android.intent.action.BOOT_COMPLETED flg=0x89000010 cmp=com.google.android.gms/org.microg.gms.nearby.exposurenotification.ServiceTrigger (has extras) }
08-28 12:03:15.870  3931  3956 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=org.microg.gms.gcm.mcs.CONNECT cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }
08-28 12:03:15.870  3931  3956 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:15.874  3931  3956 D GmsGcmMcsSvc: Starting MCS connection...
08-28 12:03:15.876  3931  3931 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:15.876  3931  3931 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
08-28 12:03:16.946  3931  3956 D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
08-28 12:03:16.951  3931  3956 D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
08-28 12:03:20.307  3931  3931 D GmsGcmTrigger: Ignoring Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }: network is offline, scheduling new attempt.
08-28 12:03:20.308  3931  3931 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: Exception while connecting!
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: java.net.SocketException: Software caused connection abort
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at java.net.SocketInputStream.socketRead0(Native Method)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket.waitForHandshake(ConscryptEngineSocket.java:563)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at com.android.org.conscrypt.ConscryptEngineSocket.getInputStream(ConscryptEngineSocket.java:287)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at org.microg.gms.gcm.McsService.connect(McsService.java:442)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at org.microg.gms.gcm.McsService.handleMessage(McsService.java:642)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at android.os.Looper.loop(Looper.java:223)
08-28 12:03:20.326  3931  3956 W GmsGcmMcsSvc: 	at org.microg.gms.gcm.McsService$HandlerThread.run(McsService.java:173)
08-28 12:03:20.326  3931  3956 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
08-28 12:03:20.326  3931  3956 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:20.331  3931  3956 D GmsGcmMcsSvc: Scheduling reconnect in 10 seconds...
08-28 12:03:20.334  3931  3956 D GmsGcmMcsSvc: Teardown initiated, reason: java.net.SocketException: Software caused connection abort
08-28 12:03:20.335  3931  3956 D GmsGcmMcsSvc: Scheduling reconnect in 20 seconds...
08-28 12:03:20.430  3931  3931 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:20.430  3931  3931 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
08-28 12:03:20.451  3931  3956 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
08-28 12:03:20.459  3931  3956 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:03:20.461  3931  3956 D GmsGcmMcsSvc: Starting MCS connection...
08-28 12:03:20.632  3931  3956 D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
08-28 12:03:20.632  3931  3956 D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
08-28 12:03:20.728  3931  3956 D GmsGcmMcsSvc: Scheduling heartbeat in 300 seconds...
08-28 12:03:20.728  3931  4222 D GmsGcmMcsSvc: Sending login request...
08-28 12:03:20.747  3931  4222 D GmsGcmMcsOutput: Outgoing message: LoginRequest{id=android-30, domain=mcs.android.com, user=4425710221210967433, resource=4425710221210967433, auth_token=3730771431117802413, device_id=android-3d6b47ff6e185d89, setting=[Setting{name=new_vc, value=1}], adaptive_heartbeat=false, use_rmq2=true, auth_service=ANDROID_ID, network_type=1}
08-28 12:03:20.747  3931  4222 D GmsGcmMcsOutput: Write MCS version code: 41
08-28 12:03:21.305  3931  4221 D GmsGcmMcsInput: Reading from MCS version: 41
08-28 12:03:21.356  3931  4221 D GmsGcmMcsInput: Incoming message: LoginResponse{id=android-30, jid=user@firebase.com/notifications, last_stream_id_received=1, server_timestamp=1630145002567}
08-28 12:03:21.357  3931  4221 D GmsGcmMcsSvc: Logged in
08-28 12:03:21.375  3931  4221 D GmsGcmMcsInput: Incoming message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
08-28 12:03:21.376  3931  4221 W GmsGcmMcsSvc: Unknown message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
08-28 12:03:40.349  3931  3931 D GmsGcmTrigger: Ignoring Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }: service is running. heartbeat instead.
08-28 12:03:40.361  3931  3956 D GmsGcmMcsSvc: Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
08-28 12:03:40.363  3931  3956 D GmsGcmMcsSvc: Scheduling heartbeat in 300 seconds...
08-28 12:03:40.365  3931  4222 D GmsGcmMcsOutput: Outgoing message: HeartbeatPing{last_stream_id_received=2}
08-28 12:03:40.621  3931  4221 D GmsGcmMcsInput: Incoming message: HeartbeatAck{last_stream_id_received=2}
08-28 12:03:40.621  3931  4221 D GmsGcmPrefs: learnReached: gcm_network_mobile / 19245
08-28 12:03:45.977  3931  3931 D GmsGcmTrigger: Ignoring Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }: service is running. schedule reconnect instead.
08-28 12:03:45.977  3931  3931 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
08-28 12:03:45.981  3931  3931 D GmsGcmTrigger: Ignoring Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }: service is running. schedule reconnect instead.
08-28 12:03:45.981  3931  3931 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
08-28 12:03:50.994  3931  3931 D GmsGcmTrigger: Ignoring Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }: service is running. heartbeat instead.
08-28 12:03:51.008  3931  3956 D GmsGcmMcsSvc: Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
08-28 12:03:51.011  3931  3956 D GmsGcmMcsSvc: Scheduling heartbeat in 300 seconds...
08-28 12:03:51.012  3931  4222 D GmsGcmMcsOutput: Outgoing message: HeartbeatPing{last_stream_id_received=3}
08-28 12:03:51.327  3931  4221 D GmsGcmMcsInput: Incoming message: HeartbeatAck{last_stream_id_received=3}
08-28 12:03:51.327  3931  4221 D GmsGcmPrefs: learnReached: gcm_network_mobile / 10704
08-28 12:04:15.843  3931  4221 D GmsGcmMcsSvc: I/O error: java.net.SocketException: Software caused connection abort
08-28 12:04:15.844  3931  3956 D GmsGcmMcsSvc: Teardown initiated, reason: java.net.SocketException: Software caused connection abort
08-28 12:04:15.845  3931  3956 D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
08-28 12:04:20.864  3931  3931 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:04:20.864  3931  3931 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
08-28 12:04:20.879  3931  3956 D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }
08-28 12:04:20.883  3931  3956 D GmsGcmMcsSvc: Connection is not enabled or dead.
08-28 12:04:20.886  3931  3956 D GmsGcmMcsSvc: Starting MCS connection...
08-28 12:04:20.953  3931  3956 D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
08-28 12:04:20.954  3931  3956 D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
08-28 12:04:21.001  3931  3956 D GmsGcmMcsSvc: Scheduling heartbeat in 365 seconds...
08-28 12:04:21.001  3931  4466 D GmsGcmMcsSvc: Sending login request...
08-28 12:04:21.006  3931  4466 D GmsGcmMcsOutput: Outgoing message: LoginRequest{id=android-30, domain=mcs.android.com, user=4425710221210967433, resource=4425710221210967433, auth_token=3730771431117802413, device_id=android-3d6b47ff6e185d89, setting=[Setting{name=new_vc, value=1}], adaptive_heartbeat=false, use_rmq2=true, auth_service=ANDROID_ID, network_type=1}
08-28 12:04:21.006  3931  4466 D GmsGcmMcsOutput: Write MCS version code: 41
08-28 12:04:21.063  3931  4465 D GmsGcmMcsInput: Reading from MCS version: 41
08-28 12:04:21.069  3931  4465 D GmsGcmMcsInput: Incoming message: LoginResponse{id=android-30, jid=user@firebase.com/notifications, last_stream_id_received=1, server_timestamp=1630145062300}
08-28 12:04:21.070  3931  4465 D GmsGcmMcsSvc: Logged in
08-28 12:04:21.079  3931  4465 D GmsGcmMcsInput: Incoming message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
08-28 12:04:21.079  3931  4465 W GmsGcmMcsSvc: Unknown message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
```

**Comment by rugk** [comment]
Oh, updating to [v0.2.22.212658](https://github.com/microg/GmsCore/releases/tag/v0.2.22.212658) did fix the issue instantly.

Even old installed apps tried to re-register.

I'll close this, but anyway, if you still have further bugs to identify in my report, feel free to ask questions/let me debug things – I just cannot downgrade my microG version likely. :upside_down_face:
