### ISSUE TITLE
[com.tellm.android.app] Cannot login via mail (Firebase Dynamic Links?) to Jodel etc.

### ISSUE THREAD

**Issue by rugk** [microg/GmsCore#1547]
**Affected app**
Name: Jodel
Package id: com.tellm.android.app

**Describe the bug**
For Android 11(?) Jodel seem to have switched their login model, as they cannot access the phone ID or so anymore.
Here is their explanation: https://jodel.com/app/sign-in-explanation-android/

Instead, you need to use a Google or email login.

**To Reproduce**
1. Install and open Jodel on an Android 11 device.
2. Tap on "login with mail".
3. You receive a mail with a link like this: `https://ae3ts.app.goo.gl/?link=https://tellm-android.firebaseapp.com/__/auth/action?apiKey%3*****SAME_STRING******SA%26mode%3DsignIn%26oobCode%3DVjBo*****************************BA%26continueUrl%3Dhttps://jodel.com/app/magic-link-fallback%26lang%3Den&apn=com.tellm.android.app&amv=5.116.0`
4. Open that link on your phone.

The link is redirected to this intend when opened on with a phone user agent: `intent://ae3ts.app.goo.gl/?link=https://tellm-android.firebaseapp.com/__/auth/action?apiKey%3*****SAME_STRING******SA%26mode%3DsignIn%26oobCode%3DVjBo*****************************BA%26continueUrl%3Dhttps://jodel.com/app/magic-link-fallback%26lang%3Den&apn=com.tellm.android.app#Intent;package=com.google.android.gms;scheme=https;S.browser_fallback_url=https://play.google.com/store/apps/details%3Fid%3Dcom.tellm.android.app&pcampaignid%3Dfdl_long&url%3Dhttps://tellm-android.firebaseapp.com/__/auth/action%3FapiKey%253*****SAME_STRING******SA%2526mode%253DsignIn%2526oobCode%253DVjBo*****************************BA%2526continueUrl%253Dhttps://jodel.com/app/magic-link-fallback%2526lang%253Den;end;` (the last string is also the same as the unmarked one above)

Optionally open it/copy it into some "special" browser, i.e. I tried to open it with these browsers:
* Firefox for Android: white screen, I'm not sure whether it opened the intend (in any case, make sure it has "Open in apps" enabled)
* LineageOS browser: Tries to search the URL and DuckDuckGo reports the search term is too long then :facepalm:
* DuckDuckGo browser: cannot open intend
* Bromite: also not really successful (did not remember what happened)
* finally, Firefox Klar/Focus is a good try: It explicitly shows you a warning that this is going to open an app/go outside of an app that might violate your privacy or so. You can confirm that with "ok".

The link seems to be a Firebase dynamic link for Firebase authentication via mail that is intended to be expected by Google Play.
See https://firebase.google.com/docs/auth/web/email-link-auth, respectively https://firebase.google.com/docs/auth/android/email-link-auth and https://firebase.google.com/docs/dynamic-links for the doc I found about that…

Maybe microG supports email login, but not these dynamic links?

Logcat (I can provide you more, if needed) when opened with Firefox Klar/Focus:
```
08-29 13:50:52.673  1385  6285 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://ae3ts.app.goo.gl/... flg=0x10000000 pkg=com.google.android.gms (has extras)} from uid 10227
08-29 13:50:52.681 18992 18992 E Focus   : failed to start third party app activity
08-29 13:50:52.681 18992 18992 E Focus   : android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://ae3ts.app.goo.gl/... flg=0x10000000 pkg=com.google.android.gms (has extras) }
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Activity.startActivityForResult(Activity.java:5314)
08-29 13:50:52.681 18992 18992 E Focus   : 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Activity.startActivityForResult(Activity.java:5272)
08-29 13:50:52.681 18992 18992 E Focus   : 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Activity.startActivity(Activity.java:5658)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.Activity.startActivity(Activity.java:5611)
08-29 13:50:52.681 18992 18992 E Focus   : 	at mozilla.components.feature.app.links.AppLinksUseCases$OpenAppLinkRedirect.invoke$default(AppLinksUseCases.kt:8)
08-29 13:50:52.681 18992 18992 E Focus   : 	at mozilla.components.feature.app.links.AppLinksFeature$handleAppIntent$doOpenApp$1.invoke(AppLinksFeature.kt:7)
08-29 13:50:52.681 18992 18992 E Focus   : 	at mozilla.components.feature.app.links.SimpleRedirectDialogFragment$onCreateDialog$$inlined$with$lambda$1.onClick(SimpleRedirectDialogFragment.kt:3)
08-29 13:50:52.681 18992 18992 E Focus   : 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.os.Looper.loop(Looper.java:223)
08-29 13:50:52.681 18992 18992 E Focus   : 	at android.app.ActivityThread.main(ActivityThread.java:7664)
```

**Expected behavior**
According [to the wiki page](https://github.com/microg/GmsCore/wiki/Implementation-Status) _Firebase Auth_ (using email login is supported.

**Screenshots**
N/A

**System**
Android Version: 11
Custom ROM: LineageOS for microG 18.1 (2021-08-11)
Fairphone 3 (FP3)

**microG**
microG Core version: v0.2.22.212658.
microG Self-Check results: All ticked.

**Additional context**
Ref https://github.com/microg/GmsCore/issues/1281 and https://github.com/microg/GmsCore/issues/1281

**Comment by ntfc** [comment]
I can observe the same behavior with Shazam login links, even though I'm still on microg `0.2.19.211515`

**Comment by lp35** [comment]
Hello!

I've got the same issue with shazam login as well...

When I open the link sent by email from shazam on my phone, it redirects to the official playstore page.

**Comment by binomnom** [comment]
Same behaviour with shazam email login. microg `0.2.24.214816-48` self-check passed.

**Comment by otmaxxx** [comment]
Same issue. Anyone know how to login?

**Comment by riekusr** [comment]
I am having the same issue with StoryShots app. the login URL received in the mail does push/opens me to the app but there it stalls.

**Comment by HansGuenther1965** [comment]
Same issue for me with latest jodel app.

**Comment by Rmtony** [comment]
same here, hoe to login in Shazam?

**Comment by lp35** [comment]
Hey guys, I successfully connected my Shazam account today using the "Sign in with email" option.

1. Download Open Link With on FDroid: (https://f-droid.org/fr/packages/com.tasomaniac.openwith.floss/)
2. Use the Sign In option using EMail in Shazam (In Shazam, go to Library -> Little cog on the top left, scroll down to the bottom and click on connect button)
3. Enter your email
4. In the email received from Shazam, long press on the link given in the email, and click on the "share" button.
5. Choose the Open Link With app to handle the link you just shared
6. Choose Open With, and select Shazam.
7. Taddddaaaaa! Your account is now synchronized!
