### ISSUE TITLE
[za.co.discovery.consumer] App crashes on newer microg versions

### ISSUE THREAD

**Issue by Cerdtruir** [microg/GmsCore#1552]
**Affected app**
Name: Discovery
Package id: za.co.discovery.consumer

**Describe the bug**
App immediately crashes when opened. But works on gmscore version 0.2.10.19420

**To Reproduce**
Launch app and press login

**Expected behavior**
Browser to login should open up

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version: 0.2.22.212658
microG Self-Check results: All ticked

**Comment by Cerdtruir** [comment]
My logcat error is this:

FATAL EXCEPTION: main
Process: za.co.discovery.consumer, PID: 12553
java.lang.IllegalArgumentException: Deeplink was null.
	at za.co.discovery.utils.UrlUtil.parseDeeplink(SourceFile:8)
	at za.co.discovery.consumer.activity.common.AppLandingActivity$a.onNext(SourceFile:5)
	at za.co.discovery.consumer.activity.common.AppLandingActivity$a.onNext(SourceFile:1)
	at com.uber.autodispose.HalfSerializer.onNext(SourceFile:8)
	at com.uber.autodispose.AutoDisposingObserverImpl.onNext(SourceFile:2)
	at io.reactivex.internal.operators.observable.ObservableHide$a.onNext(SourceFile:1)
	at io.reactivex.subjects.PublishSubject$a.onNext(SourceFile:2)
	at io.reactivex.subjects.PublishSubject.onNext(SourceFile:3)
	at za.co.discovery.android.services.links.GoogleAppDynamicLinks.b(SourceFile:1)
	at mu1.onSuccess(Unknown Source:6)
	at b41.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
