### ISSUE TITLE
[Plugshare] app does not show the detail of the charging point

### ISSUE THREAD

**Issue by reg125** [microg/GmsCore#1575]
Affected app
Name: [PlugShare ]
Package id: [com.xatori.Plugshare]
https://play.google.com/store/apps/details?id=com.xatori.Plugshare

Describe the bug
If I tap on the charging station symbol on the map, the app does not respond, it does not show the detail of the charging point.

To Reproduce
Install the Plugshare app and tap the charging station icon on the map.
 
System
Android Version: [11]
Custom ROM: [LineageOS 18.1]

microG
microG Core version: [0.2.22.212658]
microG Self-Check results: [All ticked]

**Comment by kallisti5** [comment]
Similar issue here.

Name: [PlugShare] v4.16.0
Package id: [com.xatori.Plugshare]
https://play.google.com/store/apps/details?id=com.xatori.Plugshare

Describe the bug:
No charging stations show up.  Infinite spin loading map. 

To Reproduce
Install, and open app.

System
Android Version: [13]
Custom ROM: e/OS v1.17-t-20231112351094-dev-instantnoodlep

microG:
microG Core version: 0.3.0.233515
self check: all checked

**Comment by kallisti5** [comment]
[plugshare-logs.txt](https://github.com/microg/GmsCore/files/13638754/plugshare-logs.txt)

plugshare logs.. of note:
```
12-11 11:01:25.220 25028 25028 D GmsMapBitmap: registerMap
12-11 11:01:25.220 25028 25028 D GmsMap  : Invoking 0 internal callbacks now that the true map is initialized
12-11 11:01:25.221 25028 25028 W Resources: Drawable com.google.android.gms:drawable/maplibre_user_icon_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
12-11 11:01:25.221 25028 25028 W Resources: java.lang.RuntimeException
12-11 11:01:25.221 25028 25028 W Resources: 	at android.content.res.Resources.getDrawable(Resources.java:908)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:183)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:169)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateShadowBitmap(LayerBitmapProvider.java:30)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.styleBitmaps(LocationLayerController.java:162)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:98)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.initializeComponents(LocationLayerController.java:79)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.<init>(LocationLayerController.java:72)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationComponent.initialize(LocationComponent.java:1092)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.location.LocationComponent.activateLocationComponent(LocationComponent.java:250)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap$lambda$56(GoogleMap.kt:760)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.$r8$lambda$Ft58vpGt-mzTqKtvBnqIjsFwFak(Unknown Source:0)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$$ExternalSyntheticLambda3.onStyleLoaded(Unknown Source:4)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapboxMap.getStyle(MapboxMap.java:120)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:671)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.$r8$lambda$SopKtjQYYLh9Z4xMPOlCv4DMlsk(Unknown Source:0)
12-11 11:01:25.221 25028 25028 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$$ExternalSyntheticLambda5.onMapReady(Unknown Source:2)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1322)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1308)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:203)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:65)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:355)
12-11 11:01:25.221 25028 25028 W Resources: 	at android.os.Handler.handleCallback(Handler.java:942)
12-11 11:01:25.221 25028 25028 W Resources: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 11:01:25.221 25028 25028 W Resources: 	at android.os.Looper.loopOnce(Looper.java:201)
12-11 11:01:25.221 25028 25028 W Resources: 	at android.os.Looper.loop(Looper.java:288)
12-11 11:01:25.221 25028 25028 W Resources: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-11 11:01:25.221 25028 25028 W Resources: 	at java.lang.reflect.Method.invoke(Native Method)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-11 11:01:25.221 25028 25028 W Resources: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by ajjjjjjjj** [comment]
This issue is also valid for Allegro: https://play.google.com/store/apps/details?id=pl.allegro

Describe the bug:
Pickup point info shows up for a split second then disappears.

To Reproduce
Install, and open app, try to order an item, select pickup point from the map.

System
Android Version: [13]

microG:
microG Core version: v0.3.1.240913
self check: all checked

Map engine: MapLibre

**Comment by Kreuger** [comment]
I cant even get chargers to load. 5 years later it isnt working. 😔

**Comment by Jenna-66** [comment]
The fix is in maplibres sources since more than three years:
https://github.com/maplibre/maplibre-native/commit/0cc65337fa07ac68a91d3ec020bc3f60b507c63f
First version with the fix is:https://github.com/maplibre/maplibre-native/releases?page=19#release-android-v11.0.0-pre0

Unfortunetaly it has breaking changes, because it changes (better fixes) classnames from "\*mapbox\*"  to "\*maplibre\*".
