### ISSUE TITLE
Support for split install after installation

### ISSUE THREAD

**Issue by Iey4iej3** [microg/GmsCore#1629]
Some apps seem to rely on some kind of post-install split installation to function. For example, some functionalities of WeChat does not work. I look at the log, and it contains

> 12-30 17:39:03.153 28367 28538 I chatty  : uid=1010197(com.tencent.mm) [GT]ColdPool#9 expire 2 lines
12-30 17:39:03.163 28367 28481 I chatty  : uid=1010197(com.tencent.mm) SplitInstallSer expire 2 lines
12-30 17:39:03.166  5147  6291 W ActivityManager: Unable to start service Intent { act=com.google.android.play.core.splitinstall.BIND_SPLIT_INSTALL_SERVICE pkg=com.android.vending } U=10: not found
12-30 17:39:03.168     0     0 D cnss    : Setting MHI state: SUSPEND(6)
12-30 17:39:03.168     0     0 D cnss    : Suspending PCI link
12-30 17:39:03.168     0     0 D cnss    : Use PCIe DRV suspend
12-30 17:39:03.170     0     0 D cnss    : Runtime suspend status: 0
12-30 17:39:03.187 29209 29369 I chatty  : uid=1010197(com.tencent.mm) expire 24 lines
12-30 17:39:03.231  1011  1166 I WVCdm   : [app][com.tencent.mm] calling virtual Return<void> wvdrm::hardware::drm::V1_3::widevine::WVDrmFactory::createPlugin(const hidl_array<uint8_t, 16> &, const android::hardware::hidl_string &, android::hardware::drm::V1_3::IDrmFactory::createPlugin_cb)
12-30 17:39:03.231  1011  1166 D WVCdm   : Instantiating CDM.
12-30 17:39:03.265 28349 28583 I chatty  : uid=1010197(com.tencent.mm) [GT]ColdPool#9 expire 2 lines
12-30 17:39:03.266 28349 28513 I chatty  : uid=1010197(com.tencent.mm) SplitInstallSer expire 2 lines
12-30 17:39:03.268  5147  6291 W ActivityManager: Unable to start service Intent { act=com.google.android.play.core.splitinstall.BIND_SPLIT_INSTALL_SERVICE pkg=com.android.vending } U=10: not found
12-30 17:39:03.419  5147  6231 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
12-30 17:39:03.505 29209 29377 I chatty  : uid=1010197(com.tencent.mm) expire 3 lines
12-30 17:39:03.527 29209 29376 I chatty  : uid=1010197(com.tencent.mm) expire 1 line

MicroG does not contain any replacement for Play Store. However, it seems possible to relay the request to other third party stores such as Aurora Store.

**Comment by CoelacanthusHex** [comment]
> Some apps seem to rely on some kind of post-install split installation to function. More precisely, it is a feature of Android App Bundle which is enforced recently. For example, some functionalities of WeChat does not work.

Without this feature, all miniapps in WeChat won't work. And sadly, in my country, many thing must be done in WeChat miniapp...

> MicroG does not contain any replacement for Play Store. However, it seems possible to relay the request to other third party stores such as Aurora Store.

FakeStore was merged to microG. So the situation may be changed. But I think redirect to Aurore Store still a good idea to reduce implement complexity and duplicated code in opensource world.

**Comment by ale5000-git** [comment]
There is partial code for this on #2225

**Comment by CoelacanthusHex** [comment]
I found the functions used to get APK/OBB of Aurora Store is separate kotlin library, so we can reuse it directly.

https://gitlab.com/AuroraOSS/gplayapi

**Comment by infinity0** [comment]
WeChat miniapps previously worked on LineageOS/MicroG versions from 2023, I used them successfully. But as of today they do not work. Alipay miniapps work, but this ecosystem is much much smaller than that of WeChat miniapps and many places/services in China only provide WeChat miniapps.

**Comment by ale5000-git** [comment]
The needed feature is implemented as part of #2553
You need to wait for it to be merged.

**Comment by infinity0** [comment]
In the meantime I figured out that the problem is with WeChat 8.0.56.

Downgrading to 8.0.54 works around the problem and allows miniapps to run again - for example via `adb shell -r -d` on a rooted phone, possibly also with `adb root` depending on how the phone is rooted.

**Comment by ale5000-git** [comment]
> In the meantime I figured out that the problem is with WeChat 8.0.56.
> 
> Downgrading to 8.0.54 works around the problem and allows miniapps to run again - for example via `adb shell -r -d` on a rooted phone, possibly also with `adb root` depending on how the phone is rooted.

Why use root when it is completely unneded?
The correct command to downgrade is this:
`adb install -r -d -g "./old-wechat.apk"`

**Comment by infinity0** [comment]
I think it might depend on your ROM. For me on lineageOS + microG, I had to run `adb root` first, otherwise `adb install -d -r` still gave me `INSTALL_FAILED_VERSION_DOWNGRADE`. It worked without root on my other phone with lineageOS + MindTheGapps.

**Comment by ale5000-git** [comment]
Strange, but you can still uninstall the new version and install the old one; it is even simpler.

**Comment by Iey4iej3** [comment]
> Strange, but you can still uninstall the new version and install the old one; it is even simpler.

According to https://x.com/MishaalRahman/status/1699870712419274794 downgrading via `adb` or `pm` is no longer supported in Android 14.

**Comment by infinity0** [comment]
> Strange, but you can still uninstall the new version and install the old one; it is even simpler.

This would cause me to lose all my app data, which was what I was trying to avoid.

**Comment by ale5000-git** [comment]
> > Strange, but you can still uninstall the new version and install the old one; it is even simpler.
> 
> This would cause me to lose all my app data, which was what I was trying to avoid.

Not necessarily, you can use:
`adb uninstall -k app_name`

The parameter **-k** allow to keep its data.

**Comment by infinity0** [comment]
> > > Strange, but you can still uninstall the new version and install the old one; it is even simpler.
> > 
> > 
> > This would cause me to lose all my app data, which was what I was trying to avoid.
> 
> Not necessarily, you can use: `adb uninstall -k app_name`
> 
> The parameter **-k** allow to keep its data.

Ah OK, I didn't know that was a thing. Thanks, I'll try that next time.

**Comment by Iey4iej3** [comment]
> Not necessarily, you can use: `adb uninstall -k app_name`
> 
> The parameter **-k** allow to keep its data.

The latest Android would disallow you to install an older version if the data of a new version was kept.

**Comment by Iey4iej3** [comment]
> The needed feature is implemented as part of [#2553](https://github.com/microg/GmsCore/pull/2553) You need to wait for it to be merged.

I upgraded to 0.3.7, and it does not seem to work well for WeChat. I look at the log, the split installation ran but failed. I will investigate this later.

**Comment by Iey4iej3** [comment]
The `logcat` for WeChat failing to perform split installation:

```
04-26 11:42:09.701 13716 13810 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallListenerRegistry : registerListener
04-26 11:42:09.701 13716 13810 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : startInstall([delivery],[])
04-26 11:42:09.702 13716 13791 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : Initiate binding to the service.
04-26 11:42:09.706 14750 14750 D SplitInstallService: onBind: 
04-26 11:42:09.707 13716 13716 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService})
04-26 11:42:09.707 13716 13791 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : linkToDeath
04-26 11:42:09.708 14750 14789 D SplitInstallService: Method <startInstall> Called by package: com.tencent.mm
04-26 11:42:09.712 14750 14750 V SplitInstallManager: splitInstallFlow: start
04-26 11:42:09.712 14750 14750 V SplitInstallManager: splitInstallFlow will query for these packages: [delivery]
04-26 11:42:09.714 14750 14750 V SplitInstallManager: splitInstallFlow oauthToken: null
04-26 11:42:09.714 14750 14750 D SplitInstallService: startInstall: installStatus -> false
04-26 11:42:09.714 13716 13970 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : onStartInstall(0)
04-26 11:42:09.714 13716 13791 I PlayCore: UID: [1010154]  PID: [13716] SplitInstallService : Unbind from service.
04-26 11:42:09.715 14750 14750 D SplitInstallService: onUnbind: 
```

**Comment by imnotlxy** [comment]
> The needed feature is implemented as part of [#2553](https://github.com/microg/GmsCore/pull/2553) You need to wait for it to be merged.

#2553 is merged. With this patch alone, does this feature already work? Or another patch is needed for Aurora Store?

**Comment by ale5000-git** [comment]
This isn't related to Aurora Store.

Do someone still have problems with microG v0.3.9?

**Comment by Iey4iej3** [comment]
Yes, reproducible under MicroG 0.3.9.250932.

**Comment by ale5000-git** [comment]
> Yes, reproducible under MicroG 0.3.9.250932.

Could you please verify you have updated both microG Services and microG Companion to v0.3.9 and enabled the options "On-demand component installation" in microG settings and then take another logcat?

**Comment by Iey4iej3** [comment]
Yes, microG Companion 0.3.9.40226. "On-demand component installation" is enabled in "Play Store services -> Google Play Feature Delivery".

Part of logcat (I do not have convenient machines at hand, thus I copy the log messages one-by-one, thus I might miss important messages. Please tell me what you need more if necessary).

``` log

[2025-07-31 14:27:43.168 Uid(value=1000):1806:1861 I/ActivityManager]
Start proc 14581:com.android.vending/u10a325 for service {com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService}
[2025-07-31 14:27:52.024 Uid(value=1010154):14448:14534 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallListenerRegistry : registerListener
[2025-07-31 14:27:52.024 Uid(value=1010154):14448:14534 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : startInstall([delivery],[])
[2025-07-31 14:27:52.028 Uid(value=1010154):14448:14567 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : Initiate binding to the service.
[2025-07-31 14:27:52.033 Uid(value=1000):1806:2426 D/BackgroundInstallControlService]
Package event received: 0
[2025-07-31 14:27:52.041 Uid(value=1010325):14581:14581 D/SplitInstallService]
onBind: 
[2025-07-31 14:27:52.139 Uid(value=1000):1806:2426 D/BackgroundInstallControlService]
Package event received: 0
[2025-07-31 14:27:52.168 Uid(value=1000):1806:2426 D/BackgroundInstallControlService]
Package event received: 0
[2025-07-31 14:27:52.170 Uid(value=1000):1806:2426 D/BackgroundInstallControlService]
Package event received: 0
[2025-07-31 14:27:52.474 Uid(value=1010154):14448:14448 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService})
[2025-07-31 14:27:52.475 Uid(value=1010154):14448:14567 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : linkToDeath
[2025-07-31 14:27:52.478 Uid(value=1010325):14581:14876 D/SplitInstallService]
Method <startInstall> Called by package: com.tencent.mm
[2025-07-31 14:27:52.480 Uid(value=1000):1806:2426 D/BackgroundInstallControlService]
Package event received: 0
[2025-07-31 14:27:52.490 Uid(value=1010325):14581:14581 V/SplitInstallManager]
splitInstallFlow: start
[2025-07-31 14:27:52.492 Uid(value=1010325):14581:14581 V/SplitInstallManager]
splitInstallFlow oauthToken: null
[2025-07-31 14:27:52.492 Uid(value=1010325):14581:14581 D/SplitInstallService]
startInstall: installStatus -> false
[2025-07-31 14:27:52.497 Uid(value=1010154):14448:15438 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : onStartInstall(0)
[2025-07-31 14:27:52.497 Uid(value=1010154):14448:14567 I/PlayCore]
UID: [1010154]  PID: [14448] SplitInstallService : Unbind from service.
[2025-07-31 14:27:52.498 Uid(value=1010325):14581:14581 D/SplitInstallService]
onUnbind: 
```

**Comment by ale5000-git** [comment]
@Iey4iej3
It seems that the function run but the list of split packages to install is empty.

Could you please try to enable "Enable device information sync" in microG settings, add a Google account (if you don't have it already) and re-try?

**Comment by Iey4iej3** [comment]
Is a Google account necessary? Maybe others could have a try first.

**Comment by ale5000-git** [comment]
> Is a Google account necessary? Maybe others could have a try first.

I suspect for some things it is necessary but I'm not sure.

**Comment by Kimiblock** [comment]
I have installed latest pre-release microG components and logged into a Google account, using Aurora Store. Sadly miniapps doesn't work.

**Comment by Kimiblock** [comment]
Looking at logcat it shows that the target apk was downloaded successfully but installation failed:

```
09-14 14:04:07.706 27948 27948 W GmsPackageInstaller: installPackagesInternal my session fail
09-14 14:04:07.708  1653  1653 I QTI PowerHAL: PowerHintSessionImpl::reportActualWorkDuration: 
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: Error installing packages
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: java.lang.IllegalStateException: Too many active sessions for UID 10492
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3348)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Parcel.createException(Parcel.java:3324)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Parcel.readException(Parcel.java:3307)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Parcel.readException(Parcel.java:3249)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:630)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:819)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.vending.installer.InstallKt.installPackagesInternal(SourceFile:4)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.vending.installer.InstallKt.installPackagesFromNetwork(SourceFile:101)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.google.android.finsky.splitinstallservice.SplitInstallManager.splitInstallFlow(SourceFile:1047)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.google.android.finsky.splitinstallservice.SplitInstallManager$splitInstallFlow$1.invokeSuspend(Unknown Source:12)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Handler.handleCallback(Handler.java:995)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Looper.loopOnce(Looper.java:248)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Looper.loop(Looper.java:338)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.app.ActivityThread.main(ActivityThread.java:9068)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: Caused by: android.os.RemoteException: Remote stack trace:
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:995)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:668)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:286)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Binder.execTransactInternal(Binder.java:1421)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 	at android.os.Binder.execTransact(Binder.java:1365)
09-14 14:04:07.709 27948 27948 W GmsPackageInstaller: 
09-14 14:04:07.711 27948 27948 D SplitInstallService: startInstall: installStatus -> false

```

After another reset, it fails with `java.lang.SecurityException: Files still open`:

```
09-14 15:26:16.731  9443  9443 W GmsPackageInstaller: installPackagesInternal pendingSessions size: 17
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: Error installing packages
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: java.lang.SecurityException: Files still open
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3340)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Parcel.createException(Parcel.java:3324)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Parcel.readException(Parcel.java:3307)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Parcel.readException(Parcel.java:3249)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.content.pm.IPackageInstallerSession$Stub$Proxy.commit(IPackageInstallerSession.java:861)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.content.pm.PackageInstaller$Session.commit(PackageInstaller.java:1988)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.vending.installer.InstallKt.installPackagesInternal(SourceFile:17)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.vending.installer.InstallKt$installPackagesInternal$1.invokeSuspend(SourceFile:19)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Handler.handleCallback(Handler.java:995)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Looper.loopOnce(Looper.java:248)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Looper.loop(Looper.java:338)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.app.ActivityThread.main(ActivityThread.java:9068)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: Caused by: android.os.RemoteException: Remote stack trace:
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.server.pm.PackageInstallerSession.assertNoWriteFileTransfersOpenLocked(PackageInstallerSession.java:2183)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.server.pm.PackageInstallerSession.markAsSealed(PackageInstallerSession.java:2444)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at com.android.server.pm.PackageInstallerSession.commit(PackageInstallerSession.java:2198)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:466)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller: 	at android.os.Binder.execTransactInternal(Binder.java:1421)
09-14 15:26:16.737  9443  9443 W GmsPackageInstaller:
```

**Comment by Iey4iej3** [comment]
The issue still exists under MicroG 0.3.15.250932.

**Comment by infinity0** [comment]
Because of this bug, I have switched to using GrapheneOS (modified to allow `adb root`) instead of LineageOS+microG on my new phone.
