### ISSUE TITLE
Context crash in PushNotificationPreferencesFragment

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#1653]
microG GmsCore 0.2.23.214816

@grote
Apparently not all cases has been fixed by #1582

```
FATAL EXCEPTION: main
Process: com.google.android.gms:ui, PID: 4793
java.lang.IllegalStateException: Fragment PushNotificationPreferencesFragment{48c9662} (bdc89f82-a65b-4fb1-b1da-ba6914c2c4d1) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
	at androidx.fragment.app.Fragment.getString(Fragment.java:1018)
	at org.microg.gms.ui.PushNotificationPreferencesFragment$updateStatus$1.invokeSuspend(PushNotificationPreferencesFragment.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:205)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
	at org.microg.gms.gcm.ServiceInfoKt$sendToServiceInfoReceiver$2$1.onReceive(ServiceInfo.kt:64)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by ale5000-git** [comment]
Problematic line: https://github.com/microg/GmsCore/blob/2a19ef45de5ad43bb3101f72aff477a2fc491e68/play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationPreferencesFragment.kt#L76

New logcat:
```
01-01 05:14:20.462 12082 12082 E AndroidRuntime: FATAL EXCEPTION: main
01-01 05:14:20.462 12082 12082 E AndroidRuntime: Process: com.google.android.gms:ui, PID: 12082
01-01 05:14:20.462 12082 12082 E AndroidRuntime: java.lang.IllegalStateException: Fragment PushNotificationPreferencesFragment{438332d} (d8c9ef1a-bed1-436a-a109-f2a1169867b6) not attached to a context.
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getString(Fragment.java:1053)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at org.microg.gms.ui.PushNotificationPreferencesFragment$updateStatus$1.invokeSuspend(PushNotificationPreferencesFragment.kt:76)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:205)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at org.microg.gms.gcm.ServiceInfoKt$sendToServiceInfoReceiver$2$1.onReceive(ServiceInfo.kt:64)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-01 05:14:20.462 12082 12082 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-01 05:14:20.514  2370 12192 W DropBoxManagerService: Dropping: system_app_crash (1555 > 0 bytes)
01-01 05:14:20.525  2370 10289 W ActivityManager:   Force finishing activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
```

**Comment by ale5000-git** [comment]
Possible fix (not tested):
```
    private fun updateStatus() {
        handler.postDelayed(updateRunnable, UPDATE_INTERVAL)
        lifecycleScope.launchWhenStarted {
            val appContext = requireContext().applicationContext
            val statusInfo = getGcmServiceInfo(appContext)
            pushStatusCategory.isVisible = statusInfo.configuration.enabled
            pushStatus.summary = if (statusInfo != null && statusInfo.connected) {
                appContext.getString(R.string.gcm_network_state_connected, DateUtils.getRelativeTimeSpanString(statusInfo.startTimestamp, System.currentTimeMillis(), 0))
            } else {
                appContext.getString(R.string.gcm_network_state_disconnected)
            }
        }
    }
```
