### ISSUE TITLE
[com.discord] Discord failing to register to FCM - java.io.IOException: MISSING_INSTANCEID_SERVICE

### ISSUE THREAD

**Issue by Qufyy** [microg/GmsCore#1683]
**Affected app**
Name: Discord
Package id: com.discord

**Describe the bug**
The app fails to register to Firebase Cloud Messaging, which means push notifications won't work

**To Reproduce**
1. Open Discord (no account needed)

**Expected behavior**
Discord properly registers to Firebase Cloud Messaging

**System**
Android Version: 12
Custom ROM: crDroid 8.2
Device: Xiaomi Mi A2 Lite

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Additional context**
Log output
```
W Discord : Fetching FCM registration token failed
W Discord : java.io.IOException: MISSING_INSTANCEID_SERVICE
W Discord :       at b.i.c.s.n.b(com.google.firebase:firebase-iid@@21.0.0:60)
W Discord :       at com.google.firebase.iid.FirebaseInstanceId.m(com.google.firebase:firebase-iid@@21.0.0:16)
W Discord :       at b.i.c.s.i.a(Unknown Source:6)
W Discord :       at b.i.a.f.n.m.run(com.google.android.gms:play-services-tasks@@17.2.1:3)
W Discord :       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W Discord :       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W Discord :       at b.i.a.f.e.o.j.b.run(com.google.android.gms:play-services-basement@@17.6.0:2)
W Discord :       at java.lang.Thread.run(Thread.java:1013)
```

**Comment by Qufyy** [comment]
Just found this https://github.com/microg/GmsCore/issues/1573, looks like this is a duplicate, sorry
