### ISSUE TITLE
[de.corona.tracing] Contact Tracing with (testing) 2.21 broken on Android 12 with external microG

### ISSUE THREAD

**Issue by rugk** [microg/GmsCore#1708]
**Affected app**
Name: Corona Contact Tracing Germany
Package id: de.corona.tracing

**Describe the bug**
After updating from 2.18, contact tracing is disabled and re-enabling causes an exception being thrown in microG.

**To Reproduce**

0. Use external microG.
1. Install v2.21 of CCTG from https://bubu1.eu/cctg/ (already published, but not suggested there, so no autoupdates happen)

(internal microG works flawlessly)

**Expected behavior**
Contact tracing should continue to work.

**Screenshots**
![exposure-error-main](https://user-images.githubusercontent.com/11966684/164679009-42e96061-7a3f-443c-81ec-e01f069a8f19.png)
![exposure-error-interface](https://user-images.githubusercontent.com/11966684/164679018-980841ee-a4f3-491f-91fc-5b7e331b29b3.png)

**System**
Android Version: 12
Custom ROM: CalyxOS 3.4.0
Device: Pixel 4 (flame)
Build-ID: `SP2A.220405.004.22304000`

**microG**
microG Core version: v0.2.24.214816-25 (4b20f8b)
microG Self-Check results: All ticked (bundled with CalyxOS)

**Additional context**
<details>

<summary>Logcat</summary>

```
[04-21 14:09:28.578 1653:1894 I/PackageManager]
Update package de.corona.tracing code path from /data/app/~~-BL93ZJXJtxTDlVtEavxCw==/de.corona.tracing-Vm9johavku8W0LeOO3yZrA== to /data/app/~~397g_JV3W73PmmhddxgN2Q==/de.corona.tracing-VRT7I9ieZzKq1ZMBlKelYg==; Retain data and using new

[04-21 14:09:28.578 1653:1815 W/ActivityTaskManager]
Force removing ActivityRecord{eaeefd9 u0 de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity t18553 f}}: app died, no saved state

[04-21 14:09:28.642 1653:1808 W/UsageStatsService]
Unexpected activity event reported! (de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity event : 23 instanceId : 259619360)

[04-21 14:09:28.652 1653:8101 V/ActivityManager]
Got obituary of 14487:de.corona.tracing

[04-21 14:09:31.409 1653:1894 I/ActivityManager]
Force stopping de.corona.tracing appid=10237 user=0: pkg removed

[04-21 14:09:31.422 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.android.gallery3d/.app.PackagesMonitor

[04-21 14:09:31.422 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.gms.gcm.UnregisterReceiver

[04-21 14:09:31.422 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.nlp.service.PackageChangedReceiver

[04-21 14:09:31.430 1653:1894 I/ActivityManager]
Force stopping de.corona.tracing appid=10237 user=0: pkg removed

[04-21 14:09:31.448 1653:1653 I/Telecom]
CarModeTracker: Package de.corona.tracing is not tracked.: SSH.oR@Fi4

[04-21 14:09:31.547 1653:15446 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to org.lineageos.audiofx/.Compatibility$Receiver

[04-21 14:09:31.548 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.aurora.store/.data.receiver.PackageManagerReceiver

[04-21 14:09:31.548 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.android.packageinstaller/.PackageInstalledReceiver

[04-21 14:09:31.548 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.android.gallery3d/.app.PackagesMonitor

[04-21 14:09:31.567 1653:1767 D/CompanionDeviceManagerService]
onPackageModified(packageName = de.corona.tracing)

[04-21 14:09:31.606 1653:9154 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to org.lineageos.audiofx/.Compatibility$Receiver

[04-21 14:09:31.607 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.aurora.store/.data.receiver.PackageManagerReceiver

[04-21 14:09:31.607 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.nlp.service.PackageChangedReceiver

[04-21 14:09:31.607 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to org.lineageos.audiofx/.Compatibility$Receiver

[04-21 14:09:31.623 1653:1817 I/ActivityManager]
Start proc 23587:de.corona.tracing/u0a237 for broadcast {de.corona.tracing/de.rki.coronawarnapp.presencetracing.checkins.checkout.auto.AutoCheckOutBootRestoreReceiver}

[04-21 14:09:31.696 1653:1653 I/NotificationService]
Cannot find enqueued record for key: 0|org.fdroid.fdroid|2|https://bubu1.eu/cctg/fdroid/repo/de.corona.tracing_2210100.apk|10145

[04-21 14:09:31.698 1653:1653 I/NotificationService]
Cannot find enqueued record for key: 0|org.fdroid.fdroid|2|https://bubu1.eu/cctg/fdroid/repo/de.corona.tracing_2210100.apk|10145

[04-21 14:09:32.883 1653:9154 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=de.corona.tracing cmp=de.corona.tracing/de.rki.coronawarnapp.ui.launcher.LauncherActivity} from uid 10145

[04-21 14:09:32.970 1653:1817 I/ActivityManager]
Start proc 23686:de.corona.tracing:persistent/u0a237 for broadcast {de.corona.tracing/org.microg.gms.nearby.exposurenotification.ServiceTrigger}

[04-21 14:09:33.290 1653:15446 I/ActivityTaskManager]
START u0 {cmp=de.corona.tracing/de.rki.coronawarnapp.ui.onboarding.OnboardingActivity} from uid 10237

[04-21 14:10:01.466 1653:2621 I/ActivityTaskManager]
START u0 {flg=0x10008000 cmp=de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity} from uid 10237

[04-21 14:10:01.502 1653:2621 W/ActivityTaskManager]
Duplicate finish request for r=ActivityRecord{321fcd3 u0 de.corona.tracing/de.rki.coronawarnapp.ui.onboarding.OnboardingActivity t18558 f}}

[04-21 14:11:47.115 1653:2168 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564411} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (103 skipped)

[04-21 14:11:59.672 1653:1815 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564496} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (91 skipped)

[04-21 14:12:13.058 1653:2168 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564544} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (49 skipped)

[04-21 14:12:24.556 1653:1815 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564586} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (45 skipped)

[04-21 14:12:34.872 1653:2181 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564664} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (81 skipped)

[04-21 14:12:44.877 1653:11871 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564705} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (41 skipped)

[04-21 14:12:54.880 1653:3567 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564746} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (43 skipped)

[04-21 14:13:22.036 1653:1653 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564757} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (15 skipped)

[04-21 14:13:22.206 1653:2625 E/CameraService_proxy]
Recent task package name: de.corona.tracing doesn't match with camera client package name: vendor.client.pid<1322>

[04-21 14:13:36.414 1653:2168 W/ProcessStats]
Tracking association SourceState{b664183 de.corona.tracing/10237 Top #564875} whose proc state 1 is better than process ProcessState{9f7cd7e com.google.android.gms:persistent/10140 pkg=com.google.android.gms} proc state 7 (177 skipped)

[04-21 14:13:42.548 1653:9154 E/CameraService_proxy]
Recent task package name: de.corona.tracing doesn't match with camera client package name: vendor.client.pid<1322>

[04-21 14:13:45.112 1653:11871 I/InputDispatcher]
Monitor swipe-up (server) is stealing touch from [f507756 de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity (server), ]

[04-21 14:13:48.384 24744:24744 D/Screenshot]
ScrollCapture: connected to window [de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity]

[04-21 14:13:52.473 15697:15734 V/de.luhmer.owncloudnewsreader.helper.FavIconHandler]
Updating AVG color of feed: Das Coronavirus-Update von NDR Info - Color: -16748360

[04-21 14:13:58.096 1653:8101 I/InputDispatcher]
Monitor swipe-up (server) is stealing touch from [f507756 de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity (server), ]

[04-21 14:16:35.487 1653:2625 E/CameraService_proxy]
Recent task package name: de.corona.tracing doesn't match with camera client package name: vendor.client.pid<1322>

[04-21 14:16:41.490 23587:23587 W/DefaultDispatch]
type=1400 audit(0.0:133251): avc: denied { read } for name="cache" dev="dm-8" ino=16 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:cache_file:s0 tclass=lnk_file permissive=0 app=de.corona.tracing

[04-21 14:16:41.500 23587:23587 W/DefaultDispatch]
type=1400 audit(0.0:133252): avc: denied { read } for name="cache" dev="dm-8" ino=16 scontext=u:r:untrusted_app:s0:c237,c256,c512,c768 tcontext=u:object_r:cache_file:s0 tclass=lnk_file permissive=0 app=de.corona.tracing

[04-21 14:16:43.001 1653:3678 I/InputDispatcher]
Monitor swipe-up (server) is stealing touch from [f507756 de.corona.tracing/de.rki.coronawarnapp.ui.main.MainActivity (server), ]

```

and

```
<<< log_count = 33 >>>
[04-21 14:09:31.422 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.gms.gcm.UnregisterReceiver

[04-21 14:09:31.422 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.nlp.service.PackageChangedReceiver

[04-21 14:09:31.607 1653:1815 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:de.corona.tracing flg=0x4000010 (has extras) } to com.google.android.gms/org.microg.nlp.service.PackageChangedReceiver

[04-21 14:09:32.970 1653:1817 I/ActivityManager]
Start proc 23686:de.corona.tracing:persistent/u0a237 for broadcast {de.corona.tracing/org.microg.gms.nearby.exposurenotification.ServiceTrigger}

[04-21 14:10:13.886 1653:1815 W/BroadcastQueue]
Target SDK mismatch: receiver ActivityInfo{339c20f org.microg.gms.gcm.TriggerReceiver} targets 29 but delivery restricted to [0, 23] broadcasting Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } from android (pid=1653, uid=1000) to com.google.android.gms/org.microg.gms.gcm.TriggerReceiver

[04-21 14:10:13.898 1653:26416 W/BroadcastQueue]
Target SDK mismatch: receiver ActivityInfo{f4e6934 org.microg.gms.gcm.TriggerReceiver} targets 29 but delivery restricted to [0, 23] broadcasting Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } from android (pid=1653, uid=1000) to com.google.android.gms/org.microg.gms.gcm.TriggerReceiver

[04-21 14:11:02.110 1653:1815 W/BroadcastQueue]
Target SDK mismatch: receiver ActivityInfo{91b9760 org.microg.gms.gcm.TriggerReceiver} targets 29 but delivery restricted to [0, 23] broadcasting Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } from android (pid=1653, uid=1000) to com.google.android.gms/org.microg.gms.gcm.TriggerReceiver

[04-21 14:11:02.122 1653:1815 W/BroadcastQueue]
Target SDK mismatch: receiver ActivityInfo{75ffd51 org.microg.gms.gcm.TriggerReceiver} targets 29 but delivery restricted to [0, 23] broadcasting Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } from android (pid=1653, uid=1000) to com.google.android.gms/org.microg.gms.gcm.TriggerReceiver

[04-21 14:11:59.691 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:11:59.749 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:03.065 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:18.640 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:19.563 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:24.610 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:24.631 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:25.795 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:27.958 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:28.143 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:34.874 8208:8208 D/ExposureNotification]
ScannerService.start: Intent { flg=0x4 cmp=com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService (has extras) }

[04-21 14:12:43.622 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:44.582 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:53.247 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:12:54.611 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:13:26.422 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }


***

[04-21 14:14:14.960 8208:8267 D/GmsGcmMcsSvc]
Ack initiated, reason: Intent { act=org.microg.gms.gcm.mcs.ACK cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }

[04-21 14:14:48.335 8240:8240 D/LocationFuser]
Received no location from org.microg.nlp.backend.ichnaea/.BackendService

***
[04-21 14:15:34.901 8208:8208 D/ExposureNotification]
ScannerService.start: Intent { flg=0x4 cmp=com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService (has extras) }

```

</details>

Exception (other device):
```
2022-04-20 18:37:59.490 14226-14226/de.corona.tracing D/GmsClient: GmsCallbacks : onPostInitComplete(null)
2022-04-20 18:37:59.507 14226-14226/de.corona.tracing E/DefaultTracingStatus: asyncStart() - failed to enable tracing!
    java.lang.IllegalStateException: interface only available once connected!
        at org.microg.gms.common.GmsClient.getServiceInterface(GmsClient.java:135)
        at org.microg.gms.nearby.ExposureNotificationApiClient.start(ExposureNotificationApiClient.java:56)
        at org.microg.gms.nearby.ExposureNotificationClientImpl.lambda$start$3$ExposureNotificationClientImpl(ExposureNotificationClientImpl.java:135)
        at org.microg.gms.nearby.ExposureNotificationClientImpl$$ExternalSyntheticLambda1.execute(Unknown Source:4)
        at org.microg.gms.common.api.GoogleApiManager$WaitingApiCall.execute(GoogleApiManager.java:124)
        at org.microg.gms.common.api.GoogleApiManager.onInstanceConnected(GoogleApiManager.java:66)
        at org.microg.gms.common.api.GoogleApiManager.access$000(GoogleApiManager.java:22)
        at org.microg.gms.common.api.GoogleApiManager$ConnectionCallback.onConnected(GoogleApiManager.java:92)
        at org.microg.gms.common.GmsClient$GmsCallbacks.onPostInitComplete(GmsClient.java:179)
        at com.google.android.gms.common.internal.IGmsCallbacks$Stub.onTransact(IGmsCallbacks.java:76)
        at android.os.Binder.execTransactInternal(Binder.java:1179)
        at android.os.Binder.execTransact(Binder.java:1143)
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:571)
        at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$Proxy.getService(IGmsServiceBroker.java:1339)
        at org.microg.gms.common.GmsClient.onConnectedToBroker(GmsClient.java:70)
        at org.microg.gms.common.GmsClient$GmsServiceConnection.onServiceConnected(GmsClient.java:150)
        at org.microg.gms.common.MultiConnectionKeeper$Connection$1.onServiceConnected(MultiConnectionKeeper.java:99)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Same exception:
```
Ursache:
java.lang.IllegalStateException: interface only available once connected!
	at org.microg.gms.common.GmsClient.getServiceInterface(GmsClient.java:135)
	at org.microg.gms.nearby.ExposureNotificationApiClient.isEnabled(ExposureNotificationApiClient.java:64)
	at org.microg.gms.nearby.ExposureNotificationClientImpl.lambda$isEnabled$5$ExposureNotificationClientImpl(ExposureNotificationClientImpl.java:177)
	at org.microg.gms.nearby.ExposureNotificationClientImpl$$ExternalSyntheticLambda16.execute(Unknown Source:4)
	at org.microg.gms.common.api.GoogleApiManager$WaitingApiCall.execute(GoogleApiManager.java:124)
	at org.microg.gms.common.api.GoogleApiManager.onInstanceConnected(GoogleApiManager.java:66)
	at org.microg.gms.common.api.GoogleApiManager.access$000(GoogleApiManager.java:22)
	at org.microg.gms.common.api.GoogleApiManager$ConnectionCallback.onConnected(GoogleApiManager.java:92)
	at org.microg.gms.common.GmsClient$GmsCallbacks.onPostInitComplete(GmsClient.java:179)
	at com.google.android.gms.common.internal.IGmsCallbacks$Stub.onTransact(IGmsCallbacks.java:76)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$Proxy.getService(IGmsServiceBroker.java:1339)
	at org.microg.gms.common.GmsClient.onConnectedToBroker(GmsClient.java:70)
	at org.microg.gms.common.GmsClient$GmsServiceConnection.onServiceConnected(GmsClient.java:150)
	at org.microg.gms.common.MultiConnectionKeeper$Connection$1.onServiceConnected(MultiConnectionKeeper.java:99)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Downstream report: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/259

**Comment by ale5000-git** [comment]
Fixed in [CCTG](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/0ce4163ada5440fc6c3ac9825275b1b2eadbfcf9)

**Comment by rugk** [comment]
Though microG could improve error handling here, the error wss not really self-explanatory and there is no logging or so to debug it.

**Comment by ale5000-git** [comment]
It would be a good thing to improve the error message but it isn't a priority, please open a new ticket specifically for the "improve error handling" thing just as memorandum.

**Comment by rugk** [comment]
done: https://github.com/microg/GmsCore/issues/1711
