### ISSUE TITLE
[com.wallapop] Log in not working, ReCaptcha init failed

### ISSUE THREAD

**Issue by GarciaLnk** [microg/GmsCore#1748]
**Affected app**
Name: Wallapop
Package id: com.wallapop

**Describe the bug**
Can't log in into the app

**To Reproduce**
1. Go to log in
2. Input credentials
3. Click on log in
4. Error pops up

**Expected behavior**
Successful login, or show ReCaptcha into successful login.

**System**
Android Version: 12
Custom ROM: DivestOS 19.1

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Additional context**
Logcat:
```
07-10 19:36:51.645  4314 10887 D GmsDummySvc: bound by: GetServiceRequest{serviceId=RECAPTCHA, gmsVersion=12451000, packageName='com.wallapop', extras=Bundle[{}]}
07-10 19:36:51.656 30647 30647 E WallapopError: ReCaptcha init failed
07-10 19:36:51.656 30647 30647 E WallapopError: java.util.concurrent.CancellationException: ReCaptcha init failed
07-10 19:36:51.656 30647 30647 E WallapopError:         at kotlinx.coroutines.ExceptionsKt.CancellationException(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.wallapop.auth.recaptcha.ReCaptchaRetriever.r(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.wallapop.auth.recaptcha.ReCaptchaRetriever.c(Unknown Source:0)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.wallapop.auth.recaptcha.e.onFailure(Unknown Source:4)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.tasks.zzk.run(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Handler.handleCallback(Handler.java:938)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Handler.dispatchMessage(Handler.java:99)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Looper.loopOnce(Looper.java:201)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Looper.loop(Looper.java:288)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.app.ActivityThread.main(ActivityThread.java:7870)
07-10 19:36:51.656 30647 30647 E WallapopError:         at java.lang.reflect.Method.invoke(Native Method)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
07-10 19:36:51.656 30647 30647 E WallapopError: Caused by: com.google.android.gms.common.api.ApiException: 17: API: Recaptcha.API is not available on this device. Connection failed with: ConnectionResult{statusCode=CANCELED, resolution=null, message=null}
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(SourceFile:3)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.zag.zad(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.zabq.d(SourceFile:7)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.zabq.c(SourceFile:2)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.zabq.zar(SourceFile:26)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.api.internal.zabq.onConnectionFailed(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.zai.onConnectionFailed(SourceFile:1)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.zzf.zzb(SourceFile:2)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.zza.zza(SourceFile:6)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.zzc.zze(SourceFile:3)
07-10 19:36:51.656 30647 30647 E WallapopError:         at com.google.android.gms.common.internal.zzb.handleMessage(SourceFile:36)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Handler.dispatchMessage(Handler.java:106)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Looper.loopOnce(Looper.java:201)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.Looper.loop(Looper.java:288)
07-10 19:36:51.656 30647 30647 E WallapopError:         at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by SkewedZeppelin** [comment]
This may be a fix: https://github.com/Divested-Mobile/DivestOS-Build/commit/c08ce75b0394a47341efb9c791a683b72e49c695#diff-52d38218a40dbd909525069782f32be03ed15bd5fd5e26e252294cd902f4369dL369-R373

**Comment by NateDogg1232** [comment]
It might be the same error as #1654

**Comment by token0** [comment]
@[GarciaLnk](https://github.com/GarciaLnk)
Try this https://forum.xda-developers.com/t/why-cant-i-log-into-strava.4243101/post-86645867

**Comment by SkewedZeppelin** [comment]
This can be closed as it was an OS issue and has been fixed in the most recent update: https://divestos.org/pages/news#2023-07.2
