### ISSUE TITLE
Login to Google account failed

### ISSUE THREAD

**Issue by b767max** [microg/GmsCore#1751]
When I use microg to try to log in to Google account, I enter the password and click I agree to the terms of use. Microg prompts that the login fails and I cannot connect to Google server
I would appreciate it if someone could help me

1. Enter the account login interface.
2. Enter the mailbox.
3. Enter the password.
4. Click I agree privacy policy
5. Microg prompt: unable to connect to Google server

**Expected behavior**
Login successful

**Screenshots**

**System**
Android Version: 12
Custom ROM: Magic UI6.1

**Additional context**

**Comment by Wasifazhar00** [comment]
Same problem unable to login 😕

**Comment by Wasifazhar00** [comment]
![Uploading Screenshot_20220725_095104_com.google.android.gms.jpg…]()

**Comment by animesh-sharama** [comment]
Exact same issue for me, is this fixed on the new nightly release?

**Comment by Wasifazhar00** [comment]
> Exact same issue for me, is this fixed on the new nightly release?

No i don't know about nightly release i will try it

**Comment by dos1** [comment]
> is this fixed on the new nightly release?

Doesn't seem to be.

**Comment by ale5000-git** [comment]
Usually it is fixed by removing the account database (it will remove all account on the device, not just Google) and re-add it again.
The list of files to remove is here: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/files/bin/minutil.sh#L39

**Comment by dos1** [comment]
Doesn't help here - FWIW, I'm trying it on a fresh Waydroid container with LineageOS 18.1 (Android 11).

```
09-01 14:34:12.169  1655  1743 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult
09-01 14:34:16.758  1655  1743 D GmsAuthLoginBrowser: JSBridge: log
09-01 14:34:19.911  1655  1655 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid&cid=1&TL={REDACTED}#close
09-01 14:34:19.960  1655  1798 D GmsHttpFormClient: -- Request --
09-01 14:34:19.960  1655  1798 D GmsHttpFormClient: add_account=1&androidId={REDACTED}&app=com.google.android.gms&client_sig={REDACTED}&callerPkg=com.google.android.gms&callerSig={REDACTED}&device_country=us&get_accountid=1&google_play_services_version=214816000&ACCESS_TOKEN=1&lang=en_US&operatorCountry=us&sdk_version=30&service=ac2dm&Token={REDACTED}
09-01 14:34:20.090  1655  1798 W GmsAuthLoginBrowser: onException
09-01 14:34:20.090  1655  1798 W GmsAuthLoginBrowser: java.io.IOException: Error=ServerError
09-01 14:34:20.090  1655  1798 W GmsAuthLoginBrowser:   at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:95)
09-01 14:34:20.090  1655  1798 W GmsAuthLoginBrowser:   at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:203)
09-01 14:34:20.090  1655  1798 W GmsAuthLoginBrowser:   at java.lang.Thread.run(Thread.java:923)
```

**Comment by ale5000-git** [comment]
Have you disabled the 2-Step verification in the Google account settings?

**Comment by dos1** [comment]
The account I'm trying to use it with doesn't even have a phone number attached, so there nothing to disable ;) I can login via browser with no troubles. It used to work with microG in the past, although the last time I tried was years ago so that probably doesn't tell much...

**Comment by goctav** [comment]
I'm experiencing the same thing with 2FA enabled (v 0.2.24.215816-25) so it may not be connected to whether 2FA is enabled or not.

**Comment by ale5000-git** [comment]
Could all of you please update microG GmsCore to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and retry?

**Comment by lpylyp** [comment]
> Could all of you please update microG GmsCore to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and retry?

Had a problem on enter email stage.
This build fixes it.

**Comment by ale5000-git** [comment]
@dos1: Could you please take a logcat with the latest nightly build?

**Comment by Wasifazhar00** [comment]
> > Could all of you please update microG GmsCore to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and retry?
> 
> Had a problem on enter email stage. This build fixes it.

Nothing happen even after update. I think in my case phone spoofing feature is not working
![Uploading Screenshot_20221201_210430_com.google.android.gms.jpg…]()

**Comment by ale5000-git** [comment]
@Wasifazhar00: You haven't waited the upload completion of thr screenshot, so now it isn't working.

**Comment by dos1** [comment]
@ale5000-git Still same thing:
```
12-01 16:31:32.711  1613  1613 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid&cid=1&TL={REDACTED}#close
12-01 16:31:32.776  1613  1789 D GmsHttpFormClient: -- Request --
12-01 16:31:32.776  1613  1789 D GmsHttpFormClient: add_account=1&androidId={REDACTED}&app=com.google.android.gms&client_sig={REDACTED}&callerPkg=com.google.android.gms&callerSig={REDACTED}&device_country=us&get_accountid=1&google_play_services_version=223616000&ACCESS_TOKEN=1&lang=en_US&operatorCountry=us&sdk_version=30&service=ac2dm&Token=oauth2_{REDACTED}
12-01 16:31:32.942  1613  1789 W GmsAuthLoginBrowser: onException
12-01 16:31:32.942  1613  1789 W GmsAuthLoginBrowser: java.io.IOException: Error=ServerError
12-01 16:31:32.942  1613  1789 W GmsAuthLoginBrowser:   at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:95)
12-01 16:31:32.942  1613  1789 W GmsAuthLoginBrowser:   at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:203)
12-01 16:31:32.942  1613  1789 W GmsAuthLoginBrowser:   at java.lang.Thread.run(Thread.java:923)
```

microG Services Core 0.2.25.223616-9 (d01f371)

**Comment by Wasifazhar00** [comment]
![Screenshot_20221201_210430_com google android gms](https://user-images.githubusercontent.com/109942250/205108971-c829896a-c50c-4f71-abde-a2dbbcbabfab.jpg)

**Comment by ale5000-git** [comment]
@dos1: Have you tried if it make any difference with SafetyNet enabled/disabled?

@Wasifazhar00: If your ROM doesn't natively support signature spoofing you should patch it to add it or change ROM.

**Comment by dos1** [comment]
Yes, no difference.

**Comment by ale5000-git** [comment]
@mar-v-in
Could you please also log the response code in addition of the error message here?
https://github.com/microg/GmsCore/blob/HEAD/play-services-base-core/src/main/java/org/microg/gms/common/HttpFormClient.java#L88-L96

**Comment by mar-v-in** [comment]
The response code is not going to be helpful here. It's either 200 (OK) or 500 (Error).

@dos1 is your account a Google Workspace account or anything else to consider about the account? Can you try if creating a new account works?

**Comment by ale5000-git** [comment]
I'm not really sure how it work but in case the network is behind a proxy or something similar isn't possible that it return other 2xx http valid codes?

**Comment by mar-v-in** [comment]
No, the connection is TLS encrypted, proxies cannot modify it. Also the error we see, `Error=ServerError` is what is actually sent from the Google Server.

I was able to reproduce this in Waydroid with an account that does work on a real device, so at least we now know that for some reason Waydroid is causing this.

**Comment by mar-v-in** [comment]
I was able to workaround this issue by using the Moto G device profile in microG's device registration settings. We can probably generate a device profile matching Waydroid's GAPPS image to get this working more properly.

**Comment by ale5000-git** [comment]
So the problem is the Google ban of uncertified devices?

**Comment by ildar** [comment]
I also see that `Error=ServerError`. Any (new) way to overcome it?

**Comment by ildar** [comment]
switching profile to Pixel helped.

**Comment by sonic-onkaringale** [comment]
Turn off Authenticate with device registration in microG Setting ->Google Accounts

**Comment by mofixa702-ctrl** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/00570715-5691-4f1b-aa25-f0b056fb3e9c" />
