### ISSUE TITLE
[sinet.startup.inDriver] Latest version crashes when selecting the destination

### ISSUE THREAD

**Issue by 1024mb** [microg/GmsCore#1770]
**Affected app**
Name: inDriver
Package id: `sinet.startup.inDriver`

**Describe the bug**
The app crashes when one selects the destination. I got this: 

```
time: 1661732270823
msg: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder android.os.IInterface.asBinder()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder android.os.IInterface.asBinder()' on a null object reference
	at com.google.android.gms.dynamic.ObjectWrapper.unwrap(SourceFile:3)
	at com.google.android.gms.maps.model.Polyline.getTag(SourceFile:1)
	at sinet.startup.inDriver.core.map.mapView.GoogleMapView.Q(SourceFile:4)
	at i80.c.f(SourceFile:6)
	at i80.c.d(SourceFile:7)
	at i80.c.a(Unknown Source:0)
	at i80.a.onAnimationUpdate(Unknown Source:2)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
	at i80.c.h(Unknown Source:7)
	at i80.c.b(Unknown Source:0)
	at i80.b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
https://paste.crdroid.net/BNFvIf

**To Reproduce**
1. Select a destination, doesn't matter where
2. See crash

**Expected behavior**
App shouldn't crash.

**Screenshots**

**System**
Android Version: 12
Custom ROM: crDroid 8.8

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Additional context**
At least the app version 4.12.0 doesn't crash.

**Comment by fosscat** [comment]
I'm on e/OS/ 1.5 with microG Core 0.2.24.223616-96 (f87cb98)-noen and the last version of inDriver that runs without crashing is 4.29.0 (524) that I downloaded from Aurora Store

**Comment by 1024mb** [comment]
Latest version: 5.23.0 is working well, closing this issue.
