### ISSUE TITLE
[com.google.android.apps.tachyon] Google Meet fails to register

### ISSUE THREAD

**Issue by t-m-w** [microg/GmsCore#1777]
**Affected app**
Name: Google Meet (formerly Google Duo)
Package id: com.google.android.apps.tachyon

**Describe the bug**
Google Meet registration via phone number (required) fails with an error "Something went wrong. Please try again" and log messages showing `Received GRPC_REGISTER error` and `INVALID_ARGUMENT: Request contains an invalid argument.` (Log attached further down.)

**To Reproduce**
1. Install Google Meet and open the app.
2. Agree to the terms.
3. Give access to contacts and to make phone calls, or don't. Doesn't matter.
4. Enter a valid phone number.
5. Tap Agree.

**Expected behavior**
The app registers successfully and is usable.

**Screenshots**
<img src="https://user-images.githubusercontent.com/7275539/189772962-18ade506-2ae9-444a-827e-d630aa7b4cbb.jpg" width="240" alt="screenshot showing Google Meet setup screen with a dialog saying 'Something went wrong. Please try again.' and an OK button" />

**System**
Android Version: 12L
Custom ROM: CalyxOS 3.8.0 (custom build)

**microG**
microG Core version: 0.2.24.214816-25 (4b20f8b)
microG Self-Check results: All ticked

**Additional context**
Log: [tachyon.log](https://github.com/microg/GmsCore/files/9552315/tachyon.log)

```
09-12 18:59:10.738  6398  6837 W Grpc    : Received GRPC_REGISTER error (id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx), tachyon-error: 1
09-12 18:59:10.738  6398  6837 W Grpc    : zjm: INVALID_ARGUMENT: Request contains an invalid argument.
09-12 18:59:10.738  6398  6837 W Grpc    : 	at io.grpc.Status.g(Unknown Source:2)
[...]
```

**Comment by lookway12123** [comment]
> **Affected app** Name: Google Meet (formerly Google Duo) Package id: com.google.android.apps.tachyon Affected version: 174.0.471884746.duo.android_20220821.17_p2 (seems to affect all versions as far back as April, when still named Duo)
> 
> **Describe the bug** Google Meet registration via phone number (required) fails with an error "Something went wrong. Please try again" and log messages showing `Received GRPC_REGISTER error` and `INVALID_ARGUMENT: Request contains an invalid argument.` (Log attached further down.)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install Google Meet and open the app.
> 2. Agree to the terms.
> 3. Give access to contacts and to make phone calls, or don't. Doesn't matter.
> 4. Enter a valid phone number.
> 5. Tap Agree.
> 
> **Expected behavior** The app registers successfully and is usable.
> 
> **Screenshots** <img alt="screenshot showing Google Meet setup screen with a dialog saying &apos;Something went wrong. Please try again.&apos; and an OK button" width="240" src="https://user-images.githubusercontent.com/7275539/189772962-18ade506-2ae9-444a-827e-d630aa7b4cbb.jpg">
> 
> **System** Android Version: 12L Custom ROM: CalyxOS 3.8.0 (custom build)
> 
> **microG** microG Core version: 0.2.24.214816-25 (4b20f8b) microG Self-Check results: All ticked
> 
> **Additional context** Log: [tachyon.log](https://github.com/microg/GmsCore/files/9552315/tachyon.log)
> 
> Log snippet (more in log attached above):
> 
> ```
> 09-12 18:59:10.738  6398  6837 W Grpc    : Received GRPC_REGISTER error (id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx), tachyon-error: 1
> 09-12 18:59:10.738  6398  6837 W Grpc    : zjm: INVALID_ARGUMENT: Request contains an invalid argument.
> 09-12 18:59:10.738  6398  6837 W Grpc    : 	at io.grpc.Status.g(Unknown Source:2)
> [...]
> ```
