### ISSUE TITLE
[com.garmin.android.apps.connectmobile] Connect mobile crashes when viewing activity with map

### ISSUE THREAD

**Issue by hrosseel** [microg/GmsCore#1779]
**Affected app**
Name: Garmin Connect
Package id: com.garmin.android.apps.connectmobile
Version: 4.58.1

**Describe the bug**
In the Garmin Mobileconnect app, when viewing an activity that shows a map, the map fails to load and crashes the app / view.

**To Reproduce**
1. Start the Garmin Mobileconnect app.
2. If you did a recent activity, click on the activity.
2. Otherwise, click "News Feed" and select an activity of your friend(s). 
4. The view loads, and immediately the app or view crashes.

**Expected behavior**
Activity details show up, including a map that shows the trajectory of the activity.

**System**
Android Version: 12
Custom ROM: CalyxOS 3.9.0

**microG**
microG Core version: 0.2.24.214816-25 (4b20f8b)
microG Self-Check results: All ticked

**Additional context**

Logcat output:

```09-15 13:30:07.568  1568  9532 I ActivityTaskManager: START u0 {flg=0x20000000 cmp=com.garmin.android.apps.connectmobile/.activities.stats.ActivityStatsActivity (has extras)} from uid 10204
09-15 13:30:07.580  2991  3240 D MeasurementService: f10(0, null, null, com.garmin.android.apps.connectmobile)
09-15 13:30:07.581  1568  9532 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (890224)
09-15 13:30:07.586  2991  3240 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@6ac7a2a) for AppMetadata[com.garmin.android.apps.connectmobile]
09-15 13:30:07.617 10727 10727 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10204; state: ENABLED
09-15 13:30:07.638  2003  2441 I HbmSvManager:  Request state 2 req 0
09-15 13:30:07.655  2991  3240 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@b25001b) for AppMetadata[com.garmin.android.apps.connectmobile]
09-15 13:30:07.655  2991  3240 D MeasurementService: f10(1611150339567867964, null, ActivityStatsActivity, com.garmin.android.apps.connectmobile)
09-15 13:30:07.671  1568  1597 I ActivityTaskManager: Displayed com.garmin.android.apps.connectmobile/.activities.stats.ActivityStatsActivity: +102ms
09-15 13:30:07.693  2003  2441 I HbmSvManager:  Request state 2 req 0
09-15 13:30:08.238  2003  2441 I HbmSvManager:  Request state 2 req 0
09-15 13:30:08.733  2062  2744 W SHANNON_IMS: 1692 [RULE] imsEnabled: false [WiFiConnectivity  STATE:trueSLID:0 ] (WiFiConnectivity%isImsEnabled:92)
09-15 13:30:08.733  2062  2744 W SHANNON_IMS: 1693 [RULE] VOC is NOT ready, isWifiConnectionEnabled() is false [WiFiConnectivity  STATE:trueSLID:0 ] (WiFiConnectivity%isVocReady:69)
09-15 13:30:08.933   926  1119 I CHRE    : @ 1873.211: [ip] Peak detected: magnitude = 0.314128 hpa, duration = 80.000001 ms
09-15 13:30:08.933   764  1595 I suez-nanoapp-clients: Barometric peak detected: magnitude = 0.314128 hPa (bucket: 7), duration = 80.000000 ms (bucket: 7).
09-15 13:30:08.934  1568  1624 E ContextHubClientManager: Cannot send message to unregistered client (host endpoint ID = -28638)
09-15 13:30:08.934   440   440 I servicemanager: Found android.frameworks.stats.IStats/default in framework VINTF manifest.
09-15 13:30:08.937   764  1595 I suez-nanoapp-clients: Vendor atom [id = 100047] reported.
09-15 13:30:09.415 10727 10727 W GmsDynamiteLoaderImpl: No such module known: com.google.android.gms.maps_core_dynamite
09-15 13:30:09.415 10727 10727 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.maps_core_dynamite
09-15 13:30:09.415 10727 10727 W GmsDynamiteLoaderImpl: No such module known: com.google.android.gms.maps_dynamite
09-15 13:30:09.415 10727 10727 D GmsDynamiteLoaderImpl: returning v1 for maps
09-15 13:30:09.415 10727 10727 D GmsDynamiteLoaderImpl: createModuleContext for com.google.android.gms.maps_dynamite at version 1
09-15 13:30:09.417 10727 10727 W s.connectmobil: Unsupported class loader
09-15 13:30:09.480 10727 10727 W s.connectmobil: Unsupported class loader
09-15 13:30:09.481  1568 10234 E system_server: Invalid class loader spec: =UnsupportedClassLoaderContext=
09-15 13:30:09.481  1568 10234 E PackageDexUsage: Unsupported context?
09-15 13:30:09.484 10727 10727 D GmsMapCreator: initV2 12451000
09-15 13:30:09.485 10727 10727 D GmsMapCreator: onTransact [unknown]: 9, android.os.Parcel@edae41d, 0
09-15 13:30:09.485 10727 10727 D GmsMapCreator: onTransact [unknown]: 10, android.os.Parcel@222692, 0
09-15 13:30:09.488 10727 10727 D GmsMapView: onCreate: null
09-15 13:30:09.502 10727 10986 W CrashReporter: Root directory doesn't exist
09-15 13:30:09.507 10727 10727 D GmsMultiArchLoader: Loading mapbox-gl from /data/user/0/com.garmin.android.apps.connectmobile/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
09-15 13:30:09.502 10727 10727 W s.connectmobile: type=1400 audit(0.0:142): avc: granted { execute } for path="/data/data/com.garmin.android.apps.connectmobile/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so" dev="dm-39" ino=28867 scontext=u:r:untrusted_app:s0:c204,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c204,c256,c512,c768 tclass=file app=com.garmin.android.apps.connectmobile
09-15 13:30:09.519 10727 10727 D GmsMap  : create
09-15 13:30:09.529 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.554 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.555 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.556 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.557 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.558 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.558 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.558 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.558 10727 10727 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-15 13:30:09.562 10727 10988 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
09-15 13:30:09.573 10727 10988 D mali_cmarp_predictor: checking cmar_predictor for com.garmin.android.apps.connectmobile
09-15 13:30:09.575 10727 10988 I Mbgl-EGLConfigChooser: In emulator: false
09-15 13:30:09.581 10727 11011 I Mbgl    : {GLThread 259}[General]: GPU Identifier: Mali-G78
09-15 13:30:09.599 10727 10727 D AndroidRuntime: Shutting down VM
09-15 13:30:09.599 10727 10727 E AndroidRuntime: FATAL EXCEPTION: main
09-15 13:30:09.599 10727 10727 E AndroidRuntime: Process: com.garmin.android.apps.connectmobile, PID: 10727
09-15 13:30:09.599 10727 10727 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 186, Size: 186
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.github.mikephil.charting.data.DataSet.getEntryForIndex(Unknown Source:2)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at lh.d.drawDataSet(SourceFile:29)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(SourceFile:13)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(SourceFile:2)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(SourceFile:30)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.garmin.android.apps.connectmobile.activities.charts3.components.OverlayCombinedChart.onDraw(SourceFile:1)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22704)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.buildDrawingCacheImpl(View.java:21976)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.buildDrawingCache(View.java:21836)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22427)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21570)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22435)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21570)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22435)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21570)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22435)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21570)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22435)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21570)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22435)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.draw(View.java:22707)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at androidx.core.widget.NestedScrollView.draw(SourceFile:1)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21579)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4531)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4251)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-15 13:30:09.599 10727 10727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-15 13:30:09.609  2991  3240 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@f2f5f91) for AppMetadata[com.garmin.android.apps.connectmobile]
09-15 13:30:09.609  1568  9532 W ServiceManager: Permission failure: android.permission.HIGH_SAMPLING_RATE_SENSORS from uid=10204 pid=10727
09-15 13:30:09.621  2991  3240 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@1700ef6) for AppMetadata[com.garmin.android.apps.connectmobile]
09-15 13:30:09.700  1568  9532 W ActivityTaskManager:   Force finishing activity com.garmin.android.apps.connectmobile/.activities.stats.ActivityStatsActivity
09-15 13:30:09.700  1568 11014 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

**Comment by ale5000-git** [comment]
Could you please try the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and report back?
