### ISSUE TITLE
adb shell am start com.google.android.gms/org.microg.gms.auth.AskPermissionActivity crash microG

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#1800]
I know it isn't the right way to use it, but a single command shouldn't be able to take down microG.
`adb shell am start com.google.android.gms/org.microg.gms.auth.AskPermissionActivity` crash microG.

```
10-05 11:51:42.739   973   973 D AndroidRuntime: Calling main entry com.android.commands.am.Am
10-05 11:51:42.780  2366  6134 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.google.android.gms/org.microg.gms.auth.AskPermissionActivity} from uid 2000 on display 0
10-05 11:51:42.782  2366  6134 V PegasusPowerHAL: boost: (param=boost_time, value=2000000000)
10-05 11:51:42.810   973   973 D AndroidRuntime: Shutting down VM
10-05 11:51:42.821  2366 24078 I ActivityManager: Start proc 984:com.google.android.gms:ui/u0a114 for activity com.google.android.gms/org.microg.gms.auth.AskPermissionActivity
10-05 11:51:42.992   984   984 I MultiDex: VM with version 2.1.0 has multidex support
10-05 11:51:42.993   984   984 I MultiDex: Installing application
10-05 11:51:42.993   984   984 I MultiDex: VM has multidex support, MultiDex support library is disabled.
10-05 11:51:43.065   984  1001 D libEGL  : loaded /system/lib/egl/libEGL_mali.so
10-05 11:51:43.076   984  1001 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_mali.so
10-05 11:51:43.077   984   984 D AndroidRuntime: Shutting down VM
10-05 11:51:43.079   984   984 E AndroidRuntime: FATAL EXCEPTION: main
10-05 11:51:43.079   984   984 E AndroidRuntime: Process: com.google.android.gms:ui, PID: 984
10-05 11:51:43.079   984   984 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.auth.AskPermissionActivity}: java.lang.IllegalArgumentException: the name must not be empty: null
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-05 11:51:43.079   984   984 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: the name must not be empty: null
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.accounts.Account.<init>(Account.java:78)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.accounts.Account.<init>(Account.java:63)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at org.microg.gms.auth.AskPermissionActivity.onCreate(AskPermissionActivity.java:81)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
10-05 11:51:43.079   984   984 E AndroidRuntime: 	... 9 more
10-05 11:51:43.082  2366  7768 W ActivityManager:   Force finishing activity com.google.android.gms/org.microg.gms.auth.AskPermissionActivity
10-05 11:51:43.090  2366 24315 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4ead798 attribute=null, token = android.os.BinderProxy@3020264
10-05 11:51:43.132   984  1001 D libEGL  : loaded /system/lib/egl/libGLESv2_mali.so
10-05 11:51:43.147  2366  1009 W DropBoxManagerService: Dropping: system_app_crash (1575 > 0 bytes)
10-05 11:51:43.164  2366  8522 I OpenGLRenderer: Initialized EGL, version 1.4
10-05 11:51:43.164  2366  8522 D OpenGLRenderer: Swap behavior 1
10-05 11:51:43.592  2366  2380 W ActivityManager: Activity pause timeout for ActivityRecord{e155a5f u0 com.google.android.gms/org.microg.gms.auth.AskPermissionActivity t56 f}
10-05 11:51:43.633  2366  6134 V PegasusPowerHAL: boost: (param=boost_time, value=2000000000)
10-05 11:51:53.604  2366  2380 W ActivityManager: Activity destroy timeout for ActivityRecord{e155a5f u0 com.google.android.gms/org.microg.gms.auth.AskPermissionActivity t56 f}
10-05 11:52:01.190 23390 23405 D BinderHooker: Got binder ptr 4e7af160 for the given val
10-05 11:52:20.790 23390 23447 I nightwatch-target: monitor resources last 600 iteration: 301628 msec
10-05 11:52:29.951 32272 32307 I PlayCommon: [3180] afhz.j(22): Preparing logs for uploading
10-05 11:52:30.026 32272 32307 I PlayCommon: [3180] afhz.j(134): Connecting to server for timestamp: https://play.googleapis.com/play/log/timestamp
10-05 11:52:30.072 32272 32307 E PlayCommon: [3180] afhz.j(135): Failed to connect to server for server timestamp: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
```

**Comment by mar-v-in** [comment]
(This should only crash the :ui subprocess. The main process and :persistent subprocess should not be affected.)
