### ISSUE TITLE
Android Studio Doesn't Import microG Emulator

### ISSUE THREAD

**Issue by OldManPeabody** [microg/GmsCore#1827]
**Describe the bug**
I'm using the version of Android Studio below:

> Android Studio Dolphin 2021.3.1 Patch 1
> Build #AI-213.7172.25.2113.9123335

![image](https://user-images.githubusercontent.com/36141328/202526330-d601e9aa-657b-480e-a308-3de2efbe883b.png)

When I add the SDK URL as described in the WikiPage (https://github.com/microg/GmsCore/wiki/Development-Tools), the repository adds, but is not listed after closing and reopening the SDK Manager to check for updates.

![image](https://user-images.githubusercontent.com/36141328/202527233-1628c1ca-af6b-4043-b299-ba245319dd99.png)

![image](https://user-images.githubusercontent.com/36141328/202527476-2f6ad146-e299-4aeb-91d4-f44ea6403eb5.png)

**Troubleshooting**
I wanted to see if Android Studio would pick up a local XML file using the file:/// protocol, so I compared differences between Google's official repository XML files and the microG repository XML files. The only difference so far was that XML header tag at the top of the Google official XML, so I added it into a local copy of the microG repository, but that didn't work:

`<?xml version="1.0" ?>`

**Comment by mar-v-in** [comment]
Make sure to check `Show package details` in the bottom right of that dialog. Then expand the `Android 6.0 (Marshmallow)` or `Android 10.0 (Q)` entry, which should show a `microG Intel x86 Atom_64 System Image` at the very bottom of each such section.

![image](https://user-images.githubusercontent.com/994036/209724980-2f93f6aa-0a54-44de-bcae-fd54b85eb3bd.png)

**Comment by PierceLBrooks** [comment]
Hi there, I am seeing a similar issue. Android Studio itself cannot pull the emulator image repo manifest file from your website any longer. Here is the error log:
```
 pbrooks@pbrooks-MacBook-Pro Personal % cd /Applications/Android\ Studio.app/Contents/MacOS/       
 pbrooks@pbrooks-MacBook-Pro MacOS % ls
 studio
 pbrooks@pbrooks-MacBook-Pro MacOS % tree
 .
 └── studio
 
 1 directory, 1 file
 pbrooks@pbrooks-MacBook-Pro MacOS % ls -lah
 total 3248
 drwxr-xr-x@  3 pbrooks  admin    96B Jul  9 00:19 .
 drwxr-xr-x@ 13 pbrooks  admin   416B Jul  9 00:19 ..
 -rwxr-xr-x@  1 pbrooks  admin   1.6M Jul  9 00:19 studio
 pbrooks@pbrooks-MacBook-Pro MacOS % ./studio 
 2025-08-25 12:23:34,249 [   5962]   WARN - #com.android.ddmlib - * daemon not running; starting now at tcp:5037
 2025-08-25 12:23:34,911 [   6624]   WARN - #com.android.tools.ndk.HotfixForOCInitialTablesBuildingActivity - Overriding OCInitialTablesBuildingActivity with HotfixForOCInitialTablesBuildingActivity
 2025-08-25 12:23:35,582 [   7295]   WARN - #c.i.u.j.JBCefApp - JCefAppConfig.class is not from a JBR module, url: jar:file:/Applications/Android%20Studio.app/Contents/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class (Use JBR bundled with the IDE)
 2025-08-25 12:23:37,270 [   8983]   WARN - #com.android.ddmlib - * daemon started successfully
 2025-08-25 12:23:40,106 [  11819]   WARN - #o.j.p.g.p.GHPRStatisticsCollector - Unknown rate limit resource: unknown
 2025-08-25 12:23:40,281 [  11994]   WARN - #o.j.p.g.p.GHPRStatisticsCollector - Unknown rate limit resource: unknown
 2025-08-25 12:23:53,857 [  25570]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
 2025-08-25 12:23:53,867 [  25580]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - use other group instead of unexpected one: testing.instrumented.configuration
 2025-08-25 12:23:53,867 [  25580]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - Use <groupConfigurable> to specify custom configurable group: other
 2025-08-25 12:23:53,867 [  25580]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - use other group instead of unexpected one: project.propCompiler
 2025-08-25 12:24:08,292 [  40005]   WARN - #com.android.tools.idea.progress.RepoProgressIndicatorAdapter - IO exception while downloading manifest
 com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://microg.org/sdk/sys-img.xml
     at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:678)
     at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:653)
     at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:366)
     at com.android.tools.idea.sdk.StudioDownloader.lambda$doDownloadFully$2(StudioDownloader.java:234)
     at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:529)
     at com.intellij.util.io.HttpRequests.process(HttpRequests.java:511)
     at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:340)
     at com.android.tools.idea.sdk.StudioDownloader.doDownloadFully(StudioDownloader.java:230)
     at com.android.tools.idea.sdk.StudioDownloader.downloadFully(StudioDownloader.java:152)
     at com.android.tools.idea.sdk.StudioDownloader.downloadFully(StudioDownloader.java:295)
     at com.android.tools.idea.sdk.StudioDownloader.downloadAndStreamWithOptions(StudioDownloader.java:142)
     at com.android.tools.idea.sdk.StudioDownloader.downloadAndStream(StudioDownloader.java:136)
     at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:140)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SumUsxp** [comment]
I'm running into the same issue. Looks like both of the packages in the XML file are now gone/404. Are there any Android Virtual Device images with microG available?

**Comment by ale5000-git** [comment]
See here : #3057
