### ISSUE TITLE
com.starfinanz.mobile.android.dkbpushtan DKB-TAN2go

### ISSUE THREAD

**Issue by occp201** [microg/GmsCore#1839]
**Affected app**
Name:   DKB-TAN2go
Package id:  com.starfinanz.mobile.android.dkbpushtan

**Describe the bug**

**To Reproduce**

0. To verify the working of the app NO need of any account.
1. Install DKB-TAN2go
2. Open it
3. Error message

TAN2go won't run without Google Play services, which are not supported by your device

**Expected behavior**

Just works (I mean ideally the devs of that app should do it but they are possibly poor in code writing)

**Screenshots**

```
11-00 00:00:49.550 25067 25067 W GooglePlayServicesUtil: com.starfinanz.mobile.android.dkbpushtan requires the Google Play Store, but it is missing.
11-00 00:00:49.550 25067 25067 E GoogleApiAvailability: Google Play services is invalid. Cannot recover.
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability: Creating dialog for Google Play services availability issue. ConnectionResult=9
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability: java.lang.IllegalArgumentException
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at sf.cm.c(SourceFile:17)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at sf.f40.onCreate(SourceFile:38)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.Activity.performCreate(Activity.java:7994)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.Activity.performCreate(Activity.java:7978)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.os.Handler.dispatchMessage(Handler.java:106)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.os.Looper.loop(Looper.java:223)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at android.app.ActivityThread.main(ActivityThread.java:7664)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at java.lang.reflect.Method.invoke(Native Method)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-00 00:00:49.550 25067 25067 W GoogleApiAvailability:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-00 00:00:49.576 25067 25067 W         : type=1400 audit(0.0:550): avc: denied { read } for name="tcp" dev="proc" ino=4026532086 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.starfinanz.mobile.android.dkbpushtan
11-00 00:00:49.617  1083  1124 I ActivityTaskManager: Displayed com.starfinanz.mobile.android.dkbpushtan/.DKBPushTan: +111ms
11-00 00:00:49.619 25067 25067 W         : type=1400 audit(0.0:551): avc: denied { read } for name="tcp" dev="proc" ino=4026532086 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.starfinanz.mobile.android.dkbpushtan
11-00 00:00:50.022   647   647 E Layer   : [Surface(name=Task=905)/@0x99b3ac7 - animation-leash#0] No local sync point found
11-00 00:00:50.022   647   647 E Layer   : [Surface(name=Task=905)/@0x99b3ac7 - animation-leash#0] No local sync point found
11-00 00:00:50.022   647   647 E Layer   : [Surface(name=Task=1)/@0xe984174 - animation-leash#0] No local sync point found
11-00 00:00:50.022   647   647 E Layer   : [Surface(name=Task=1)/@0xe984174 - animation-leash#0] No local sync point found
11-00 00:00:50.071  2190  2190 W Choreographer: Frame time is 0.227016 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
11-00 00:00:50.071  1757  1757 W Choreographer: Frame time is 0.226651 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
11-00 00:00:50.643 25067 25067 W         : type=1400 audit(0.0:553): avc: denied { read } for name="tcp" dev="proc" ino=4026532086 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tc
```

**System**
Android Version: 11
Custom ROM: LOS 18.1

**microG**
microG Core version: v0.2.25.223616
microG Self-Check results:  All ticked

**Additional context**

**Comment by mar-v-in** [comment]
I can't reproduce this on my device. Are you using LineageOS for microG or a custom-patched LineageOS?

**Comment by ale5000-git** [comment]
@occp201: Please check that you have FakeStore installed and that the version is at least 0.1.0

**Comment by huth** [comment]
FWIW, I just ran into the same error message here ("TAN2go won't run without Google Play services..."). I was missing the signature spoofing in the microG settings. After enabling that (and after enabling the cloud messaging), the DKB TAN2Go app started fine.
