### ISSUE TITLE
[com.streetcrowd] Cannot log in to the StreetCrowd app

### ISSUE THREAD

**Issue by tamas646** [microg/GmsCore#1873]
**Affected app**
Name: StreetCrowd (v2.16.0b391)
Package id: com.streetcrowd

**Describe the bug**
I cannot log in to the app using the link that was being sent by email.
First the link was opened in the browser and nothing happened.
Later I found a way to open the link directly with the StreetCrowd app but nothing happened there either. (I mean absolutely nothing)

**To Reproduce**
Steps to reproduce the behavior (open link in browser):
1. Download and install StreetCrowd app (v2.16.0b391)
2. Open the StreetCrowd app and select your city/service
3. Enter your email address than tap 'Login/Register' - soon you will get an email
4. Open the email you got from streetcrowd
5. Tap on the link in the email
6. The link will be opened in your browser
7. The browser will load an empty page where nothing happens

Steps to reproduce the behavior (open link directly in the app):
1. Download and install StreetCrowd app (v2.16.0b391)
2. Go to the device settings and open the application settings
3. Select 'StreetCrowd'
4. Select 'Open by default'
5. Tap on add link
6. Select 'streetcrowd.page.link then tap 'Add'
7. Open the StreetCrowd app and select your city/service
8. Enter your email address than tap 'Login/Register' - soon you will get an email
9.  Open the email you got from streetcrowd
10. Tap on the link in the email
11. You will be automatically redirected back to the StreetCrowd app
12. Nothing happens

**Expected behavior**
By opening the link in the email the app should log me in to the service.

**System**
Android Version: 12
Custom ROM: LineageOS 19.1 (2022-12-18) + Magisk 25.2

**microG**
microG Core version: 0.2.26.223616
microG Self-Check results: All ticked

**Additional context**
I also tried to deny root access to the app but it seems that it's not a Magisk related problem.

**Comment by tamas646** [comment]
I've successfully registered and logged in to StreetCrowd in the newest version of the app.
I close this issue now.

**Android version:** 12 (LOS 19.1 with microg)
**StreetCrowd version:** v2.18.0b400
**MicroG version:** 0.2.26.223616

**Comment by tamas646** [comment]
Now I have problems again.

After clicking on 'Login' the app shows a popup: `Connection Error`:
```
There is a problem with your connection.
Please refresh your internet connection and try again.
Thank you.
```

I started debugging and there's a warning that may cause the issue:
```
java.lang.RuntimeException: Checkin disabled
	at org.microg.gms.gcm.PushRegisterServiceKt.ensureCheckinIsUpToDate(PushRegisterService.kt:33)
	at org.microg.gms.gcm.PushRegisterServiceKt.access$ensureCheckinIsUpToDate(PushRegisterService.kt:1)
	at org.microg.gms.gcm.PushRegisterHandler$handleMessage$1.invokeSuspend(PushRegisterService.kt:313)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at androidx.lifecycle.LifecycleCoroutineScope.launchWhenStarted(Lifecycle.kt:96)
	at org.microg.gms.gcm.PushRegisterHandler.handleMessage(PushRegisterService.kt:309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
It looks like StreetCrowd app cannot register for push notifications.

Any ideas?

**Comment by tamas646** [comment]
**Android version:** 12 (LOS 19.1 with microg)
**StreetCrowd version:** v2.19.0b402
**MicroG version:** 0.2.27.223616

**Comment by tamas646** [comment]
I found and fixed the problem.

Somehow I got Google device registration disabled.
After re-enabling it I could successfully login to the application.
