### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcpfr

### ISSUE THREAD

**Issue by zxhandroid** [microg/GmsCore#1877]
**Describe the bug**
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcpfr;
       at abxk.d(abxk.java)
       at zad.<clinit>(zad.java:2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(DynamiteLoaderImpl.java:4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzf(com.google.android.gms:play-services-basement@@18.0.1:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.0.1:26)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.0.1:1)
       at com.google.android.gms.dynamite.zzk.selectModule(com.google.android.gms:play-services-basement@@18.0.1:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.1:5)
       at com.google.android.gms.internal.measurement.zzee.zzf(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:3)
       at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

Caused by java.lang.ClassNotFoundException: Didn't find class "cpfr" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-2/base.apk", zip file "/data/app/com.google.android.gms-2/split_config.es.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-2/lib/arm, /data/app/com.google.android.gms-2/base.apk!/lib/armeabi-v7a, /data/app/com.google.android.gms-2/split_config.es.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at abxk.d(abxk.java)
       at zad.<clinit>(zad.java:2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(DynamiteLoaderImpl.java:4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzf(com.google.android.gms:play-services-basement@@18.0.1:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.0.1:26)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.0.1:1)
       at com.google.android.gms.dynamite.zzk.selectModule(com.google.android.gms:play-services-basement@@18.0.1:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.1:5)
       at com.google.android.gms.internal.measurement.zzee.zzf(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:3)
       at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@19.0.2:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**To Reproduce**
Can not reproduce the crash ，just find many crash report in firebase

**Screenshots**
Most crash occur in Samsung android 7 \8 and on the background.

![image](https://user-images.githubusercontent.com/22110022/216249055-f328758d-5ed4-4c17-b9c2-19facca6f91b.png)

**More Info**
com.google.gms:google-services:4.3.13

**Comment by lic2050** [comment]
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcqaw;
       at aavi.d(aavi.java)
       at xvx.<clinit>(xvx.java:2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(DynamiteLoaderImpl.java:4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzg(com.google.android.gms:play-services-basement@@18.1.0:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.1.0:28)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.1.0:1)
       at com.google.android.gms.dynamite.zzi.selectModule(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.1.0:5)
       at com.google.android.gms.internal.measurement.zzef.zzf(zzef.java:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:3)
       at com.google.android.gms.internal.measurement.zzdu.run(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.ClassNotFoundException: cqaw
       at aavi.d(aavi.java)
       at xvx.<clinit>(xvx.java:2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(DynamiteLoaderImpl.java:4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzg(com.google.android.gms:play-services-basement@@18.1.0:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.1.0:28)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.1.0:1)
       at com.google.android.gms.dynamite.zzi.selectModule(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.1.0:5)
       at com.google.android.gms.internal.measurement.zzef.zzf(zzef.java:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:3)
       at com.google.android.gms.internal.measurement.zzdu.run(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)


com.google.gms:google-services:4.3.15

**Comment by ddeepali** [comment]
Seeing same crashes:

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcrfl;
       at aclp.d(:com.google.android.gms@230914026@23.09.14 (100306-515650844))
       at znd.<clinit>(:com.google.android.gms@230914026@23.09.14 (100306-515650844):2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(:com.google.android.gms@230914026@23.09.14 (100306-515650844):4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzf(com.google.android.gms:play-services-basement@@18.0.0:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.0.0:26)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.0.0:1)
       at com.google.android.gms.dynamite.zzi.selectModule(com.google.android.gms:play-services-basement@@18.0.0:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:5)
       at com.google.android.gms.internal.measurement.zzee.zzf(zzee.java:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@20.1.0:3)
       at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@20.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)



Caused by java.lang.ClassNotFoundException: Didn't find class "crfl" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-e2yXAR_q5ysx22Qh10RtMw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-e2yXAR_q5ysx22Qh10RtMw==/lib/arm, /data/app/com.google.android.gms-e2yXAR_q5ysx22Qh10RtMw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at aclp.d(:com.google.android.gms@230914026@23.09.14 (100306-515650844))
       at znd.<clinit>(:com.google.android.gms@230914026@23.09.14 (100306-515650844):2)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(:com.google.android.gms@230914026@23.09.14 (100306-515650844):4)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzf(com.google.android.gms:play-services-basement@@18.0.0:5)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@18.0.0:26)
       at com.google.android.gms.dynamite.zze.zzb(com.google.android.gms:play-services-basement@@18.0.0:1)
       at com.google.android.gms.dynamite.zzi.selectModule(com.google.android.gms:play-services-basement@@18.0.0:2)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:5)
       at com.google.android.gms.internal.measurement.zzee.zzf(zzee.java:2)
       at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@20.1.0:3)
       at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@20.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)


com.google.gms:google-services:4.3.10

**Comment by abitling** [comment]
Any update here, facing same issue on `com.google.gms:google-services:4.4.2`
