### ISSUE TITLE
Crash in background

### ISSUE THREAD

**Issue by Wojtaz0w** [microg/GmsCore#1878]
**Describe the bug**
https://paste.crdroid.net/323LJ3
```
time: 1675519058753 msg: android.os.DeadObjectException stacktrace: android.os.DeadObjectException 	at android.os.BinderProxy.transactNative(Native Method) 	at android.os.BinderProxy.transact(BinderProxy.java:584) 	at com.google.android.gms.clearcut.internal.IClearcutLoggerCallbacks$Stub$Proxy.onLogResult(IClearcutLoggerCallbacks.java:150) 	at org.microg.gms.clearcut.ClearcutLoggerServiceImpl$log$1.invokeSuspend(ClearcutLoggerService.kt:37) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367) 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:174) 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invokeSuspend(PausingDispatcher.kt:162) 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invoke(Unknown Source:8) 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invoke(Unknown Source:4) 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169) 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 	at androidx.lifecycle.PausingDispatcherKt.whenStateAtLeast(PausingDispatcher.kt:156) 	at androidx.lifecycle.PausingDispatcherKt.whenStarted(PausingDispatcher.kt:60) 	at androidx.lifecycle.LifecycleCoroutineScope$launchWhenStarted$1.invokeSuspend(Lifecycle.kt:97) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 	at android.os.Handler.handleCallback(Handler.java:942) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:201) 	at android.os.Looper.loop(Looper.java:288) 	at android.app.ActivityThread.main(ActivityThread.java:7872) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946) 
```

**To Reproduce**
Have microG running in the background. 

**Expected behavior**
MicroG doesn't crash

**Screenshots**
NA. 

**System**
Android Version: 13 QPR1, 05.12.2022 SPL
Custom ROM: crDroid 9.0

**Additional context**
My phone is Redmi 9 3/32GB
MicroG crashed while I was starting Firefox if it might help

**Comment by rayisbadat** [comment]
I am also seeing this error i believe.  I don't have  error logs, but can grab some next time it happens.    It happens around once every 2 days.  A reboot or  stopping `microg services core` resolves the issues for another day or two.  

  The two apps that alert me it is happening are DAVx5  and  Nextcloud background syncs.  They both throw some version of ` "EXCEPTION android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe`. 

 I am  running 20-20230126-microG-lemonade (microg's lineageOS 20 on a OnePlus9).

**Comment by Wojtaz0w** [comment]
Caught another crash today. 
https://paste.crdroid.net/wtAvLf
`time: 1675688068362
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to stop service org.microg.gms.wearable.WearableService@e2e2f5b: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4705)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
	at org.microg.gms.wearable.WearableImpl.stop(WearableImpl.java:622)
	at org.microg.gms.wearable.WearableService.onDestroy(WearableService.java:47)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4685)
	... 9 more`

**Comment by Wojtaz0w** [comment]
https://paste.crdroid.net/3frSvh
Another one.

**Comment by Wojtaz0w** [comment]
https://paste.crdroid.net/GxiqFB

**Comment by Wojtaz0w** [comment]
https://paste.crdroid.net/pBkqF9

**Comment by Wojtaz0w** [comment]
Its seams to be about clearcut logger
https://paste.crdroid.net/NqbYme

**Comment by Wojtaz0w** [comment]
Please at least look into this issue! 
https://paste.crdroid.net/n0ky9z
