### ISSUE TITLE
[<package-id>] <title>

### ISSUE THREAD

**Issue by mtlive** [microg/GmsCore#1899]
**Affected app**
Name: Snapp
Package id: cab.snapp.passenger

**Describe the bug**
The app crashes and doesn't open at all.

**To Reproduce**
1. Open the app.

**Expected behavior**
It should open.

**System**
Android Version: 9
Custom ROM:  LineageOS 16

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: All ticked

**Logcat**
```
03-12 16:21:03.086 28184 28184 E AndroidRuntime: FATAL EXCEPTION: main
03-12 16:21:03.086 28184 28184 E AndroidRuntime: Process: cab.snapp.passenger, PID: 28184
03-12 16:21:03.086 28184 28184 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {cab.snapp.passenger/cab.snapp.passenger.app_starter.LauncherActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-12 16:21:03.086 28184 28184 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at java.lang.String.substring(String.java:2036)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at cab.snapp.passenger.framework.c.b.getServiceVersionName(SourceFile:36)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at cab.snapp.passenger.app_starter.units.splash.a.reportGooglePLayServiceVersion$impl_ProdRelease(SourceFile:282)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at cab.snapp.passenger.app_starter.units.splash.a.handleDefaultOnUnitResume(SourceFile:231)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at cab.snapp.passenger.app_starter.units.splash.a.onUnitResume(SourceFile:140)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at cab.snapp.arch.protocol.BaseController.onResume(SourceFile:62)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.Fragment.performResume(SourceFile:3180)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.resume(SourceFile:606)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:285)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStore.moveToExpectedState(SourceFile:113)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(SourceFile:1424)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:2968)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchResume(SourceFile:2900)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.Fragment.performResume(SourceFile:3189)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.resume(SourceFile:606)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:285)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentStore.moveToExpectedState(SourceFile:113)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(SourceFile:1424)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:2968)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchResume(SourceFile:2900)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchResume(SourceFile:285)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onResumeFragments(SourceFile:334)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onPostResume(SourceFile:323)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onPostResume(SourceFile:240)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7325)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
03-12 16:21:03.086 28184 28184 E AndroidRuntime:        ... 11 more
03-12 16:21:03.267 28184 28184 E WebEngage: App has crashed
03-12 16:21:03.267 28184 28184 E WebEngage: java.lang.RuntimeException: Unable to resume activity {cab.snapp.passenger/cab.snapp.passenger.app_starter.LauncherActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
03-12 16:21:03.312 19731 19731 D MeasurementService: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
03-12 16:21:03.315 27907 27983 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids=null, source=APP), candidates=[Candidate(clids=null, source=APP)])
03-12 16:21:03.330 27907 27983 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids=null, source=APP), candidates=[Candidate(clids=null, source=APP)])
03-12 16:21:03.385 27907 27982 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids=null, source=APP), candidates=[Candidate(clids=null, source=APP)])
03-12 16:21:03.615   672   688 W ActivityManager:   Force finishing activity cab.snapp.passenger/.app_starter.LauncherActivity
03-12 16:21:03.398 27907 27982 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids=null, source=APP), candidates=[Candidate(clids=null, source=APP)])
03-12 16:21:03.680 28184 28184 I Process : Sending signal. PID: 28184 SIG: 9
03-12 16:21:03.703   672  2523 I ActivityManager: Process cab.snapp.passenger (pid 28184) has died: fore TOP
03-12 16:21:03.705   672   721 W libprocessgroup: kill(-28184, 9) failed: No such process
03-12 16:21:03.705   672   721 I libprocessgroup: Successfully killed process cgroup uid 10091 pid 28184 in 0ms
```

**Comment by mortezadadgar** [comment]
Could any core member take a look at this? I would like to provide anything to solve this issue
And here's a link to this app https://snapp.ir/download/ (button with android icon)

**Comment by src-tinkerer** [comment]
Tested with nightly build and can confirm that it works with the latest build.

**Comment by src-tinkerer** [comment]
I get the same error with the latest version `240913004`, however it works fine with `233515001`.

**Comment by mortezadadgar** [comment]
Just letting everybody know that snapp finally starts without any crash! for the record, I use version 8.21.0 of snapp and microg 3.4.240913.
