### ISSUE TITLE
[de.hochbahn.hvvswitch] says "Update Google Play services; hvv switch won't run unless you update Google Play services."

### ISSUE THREAD

**Issue by erAck** [microg/GmsCore#1911]
**Affected app**
Name: hvv switch - Mobility Hamburg
Package id: de.hochbahn.hvvswitch

**Describe the bug**
Starting the hvv switch app latest release from Mar 8, 2023 displays a notification

Update Google Play services
hvv switch won't run unless you update Google Play services.

The app runs though, but forcing a map to open doesn't work.

**To Reproduce**
1. Install https://play.google.com/store/apps/details?id=de.hochbahn.hvvswitch
2. Start it.
3. Mentioned notification is displayed.

Additionally:

4. Disable Location in Settings.
5. Swipe up twice to "Choose your vehicle" => displays "Your location cannot be determined precisely enough." (which was also in earlier releases, but ok).
6. Tap "Open map" => map does not open. (which was possible in earlier releases that did not display the notification).

If Location is enabled, choosing a vehicle from the then displayed map is possible.

**Expected behavior**
No notification, opening map works.

**System**
Android Version: 10
Custom ROM: LineageOS for microG 17.1

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: All ticked

**Additional context**

**Comment by Antzus** [comment]
I have the same issue and microG version, using /e/OS 1.9 instead of LineageOS

**Comment by Tomoms** [comment]
I am most likely facing the same issue on the same microG version. Apps that should display a map through Mapbox/Maplibre do not, and instead a "Play Services is unavailable" kind of pop up message is shown.
Here's a typical error displayed in the log when the pop up appears, taken while trying to open the map in the DB Navigator app:

```
04-12 16:43:26.778 31855 31855 W GooglePlayServicesUtil: de.hafas.android.db requires the Google Play Store, but it is missing.
04-12 16:43:26.787 31855 31855 D FragmentManager: moveto ACTIVITY_CREATED: a{b61c28e} (039a570e-9e78-4be1-9d77-5be2e70398e9 id=0x7f0a0505 tag=map_fragment)
04-12 16:43:26.787 31855 31855 W GooglePlayServicesUtil: de.hafas.android.db requires the Google Play Store, but it is missing.
04-12 16:43:26.788 31855 31855 E GoogleApiAvailability: Google Play services is invalid. Cannot recover.
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: Creating dialog for Google Play services availability issue. ConnectionResult=9
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: java.lang.IllegalArgumentException
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@18.1.0:99)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(com.google.android.gms:play-services-base@@18.1.0:3)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(com.google.android.gms:play-services-base@@18.1.0:4)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(com.google.android.gms:play-services-base@@18.1.0:1)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at nd.c.P(GoogleMaps2View.java:14)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at uh.a.onActivityCreated(BasicMapScreen.java:10)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:12)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.e0.a(FragmentStateManager.java:36)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.e0.m(FragmentStateManager.java:117)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.w.g0(FragmentManager.java:231)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.w.q1(FragmentManager.java:82)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.w.d0(FragmentManager.java:22)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at androidx.fragment.app.w$f.run(FragmentManager.java:4)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at android.os.Handler.handleCallback(Handler.java:942)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at android.os.Looper.loopOnce(Looper.java:201)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at android.os.Looper.loop(Looper.java:288)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at android.app.ActivityThread.main(ActivityThread.java:7903)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at java.lang.reflect.Method.invoke(Native Method)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-12 16:43:26.788 31855 31855 W GoogleApiAvailability: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

I'm using Android 13 (self-built LineageOS 20 with signature spoofing support) and the self check is completely ok. The same microG version does not exhibit this behaviour on other instances of my ROM (other users of my ROM are using microG without this issue), so it must be caused by something that is tied specifically to my setup.

@mar-v-in I am available for all kinds of debugging or helping tasks aimed at fixing this, I have no problem rebuilding and testing whatever might help you.

**Comment by erAck** [comment]
Fwiw, DB Navigator for me displays the map.

**Comment by felix-engelmann** [comment]
I experienced a similar issue. For me it was fixed by installing and setting a Location module for the UnifiedNlp. Maybe that helps.

**Comment by erAck** [comment]
I do have the Mozilla UnifiedNlp Backend activated.

**Comment by Antzus** [comment]
the June 2023 update to /e/OS (version 1.12.3-2023062030151) seems to have fixed it for me.

I also reinstalled the Switch app, which may or may not have been necessary for it to work here. I had the latest Switch update before this, but this by itself did _not_ help the Google Play error.

**Comment by ale5000-git** [comment]
For those with /e/ there is the new version of microG GmsCore (0.2.28), the link is here: https://github.com/micro5k/gmscore-info

**Comment by felix-engelmann** [comment]
The /e/ update fixed it for me too. At least it no longer crashes, but the map is not pan or zoomable. So it might still crash some handler, but just a little bit better handled. I have not debugged the missing functionality.

**Comment by ale5000-git** [comment]
There are already a lot of map related and location related fixes after the 0.2.28 release but only the ones with officially signed microG can try it, they are in the [nightly build](https://microg.org/dl/core-nightly.apk).

**Comment by ale5000-git** [comment]
Now there is a new version of microG for any ROM, links are here: https://github.com/micro5k/gmscore-info
Could all of you that still have the problem please retry?

**Comment by erAck** [comment]
This issue is solved for me with microG Core 2.29.233013 (didn't try 2.28).
