### ISSUE TITLE
[com.ubs.swidKXJ.android] FATAL EXCEPTION when casting com.google.android.play.core.review.internal.zzu

### ISSUE THREAD

**Issue by Codain** [microg/GmsCore#1916]
**Affected app**
Name: UBS & UBS key4
Package id: [com.ubs.swidKXJ.android]

**Describe the bug**
Application crashes since several months on startup.

Possible workaround is to remove the app and reinstall it... Until it crashed again.

**To Reproduce**
1. Open the application
2. Type your credentials
3. Wait for the home page to load

**Expected behavior**
No crash.

**Screenshots**
N/A

**Log**
```
04-17 21:47:10.457  2852  2852 E AndroidRuntime: FATAL EXCEPTION: main
04-17 21:47:10.457  2852  2852 E AndroidRuntime: Process: com.ubs.swidKXJ.android, PID: 2852
04-17 21:47:10.457  2852  2852 E AndroidRuntime: java.lang.ClassCastException: com.google.android.play.core.review.internal.zzu cannot be cast to com.google.android.play.core.review.ReviewException
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.HomeViewModel.WiJ(:0)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.HomeViewModel.invokeGooglePlayInAppReviewAPI$lambda-0(Unknown Source:12)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.HomeViewModel.WiJ(:0)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.HomeViewModel.a(Unknown Source:11)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.g.KvJ(:0)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.ubs.swidKXJ.mobilebanking.homescreen.home.g.onComplete(Unknown Source:9)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.google.android.gms.tasks.zzi.uoc(:0)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.google.android.gms.tasks.zzi.run(Unknown Source:6)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-17 21:47:10.457  2852  2852 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**System**
Android Version: [12]
Custom ROM: [/e/OS 1.9.1]

**microG**
microG Core version: [0.2.27.223616-1]
microG Self-Check results: [All ticked]

**Additional context**
N/A

Thanks for your support and hard work!

**Comment by illerokcob** [comment]
According to the logs, the app tries to start and bind to the [in-app review](https://developer.android.com/guide/playcore/in-app-review) service which is a Play Store component and unavailable on the device. This should be implemented as a fake service in the FakeStore app to avoid similar crashes in the future

**Comment by Codain** [comment]
Thanks @illerokcob for reviewing, that was also my understanding.

Hopefully in their latest update the app is not crashing anymore, but I am not sure if it is because they have a cleaner and more robust code (amazing the number of warnings in the logs...) or if it is because the app is trying to call this service only every n days (I noticed that if I reinstalled the app it is not crashing anymore... before it eventually crash again some days after, thus the hypothesis).

I let open in case it crashes again and because there might be something to do on microG side.

**Comment by Skirmisher** [comment]
Running into this with the latest update to Canon Camera Connect (jp.co.canon.ic.cameraconnect); the app tries to launch this service on each start, and then crashes when it can't, making it unusable. Definitely needs to be a new FakeStore stub.

**Comment by Codain** [comment]
Now the application is again not able to start (blocked on the splash page) but it doesn't crash and I don't see an exception in the logs. I suspect that the issue remains on the app but that they are still not correctly handling the exception (which would not surprise me given how many warnings remains in the logs).

Not sure if microg can fake the store without leading the user believe he can use it and send a feedback.

**Comment by ale5000-git** [comment]
It will certainly be fixed (I'm not sure about the time), but it is the wrong repo.
It specifically request com.android.vending, so it belong to there: https://github.com/microg/FakeStore/issues

**Comment by Codain** [comment]
@ale5000-git, do you expect me to create a second issue under fakestore that links to this one?

**Comment by Skirmisher** [comment]
Well, FakeStore now lives in the GmsCore repo apparently, so this issue ended up on the right repo after all...

**Comment by Atemu** [comment]
This has been fixed in 0.3.9.
