### ISSUE TITLE
[com.deepl.mobiletranslator] DeepL app crashes upon taking a picture

### ISSUE THREAD

**Issue by Wojtaz0w** [microg/GmsCore#1918]
**Affected app**
Name: [DeepL Translator]
Package id: [com.deepl.mobiletranslator]
App version : 1.9.1 (55)
Play Store:  https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator
**Describe the bug**
After attempting to take a picture for DeepL to translate text on it app crashes. 

**To Reproduce**
1. Open DeepL
2. Click on camera icon
3. Try to take a picture
4. It crashes

**Expected behavior**
Photo is taken and text is detected and translated

**Screenshots**
Step 1:
![Screenshot_20230420-095400_DeepL.png](https://user-images.githubusercontent.com/104674625/233298654-e40b869b-0d8b-48d1-89c1-3241693be040.png)
Step 2:
![Screenshot_20230420-095405_DeepL.png](https://user-images.githubusercontent.com/104674625/233298694-531e5238-ae31-4eef-b54f-dd7218cfbc69.png)
Step 3:
![Uploading Screenshot_20230420-095408_DeepL.png …]()
Step 4:
![Screenshot_20230420-095410_crDroid Home.png](https://user-images.githubusercontent.com/104674625/233298763-e1ec30f3-eb55-4661-90f8-4032cffa3169.png)

**System**
Android Version: 13
Custom ROM: crDroid 9.1

**microG**
microG Core version: 0.2.27
microG Self-Check results: All ticked except SMS

**Additional context**
Log: https://paste.crdroid.net/NQyHFh
```
msg: java.lang.IllegalStateException: MlKitContext has not been initialized
stacktrace: java.lang.IllegalStateException: MlKitContext has not been initialized
	at ba.p.j(com.google.android.gms:play-services-basement@@18.0.0:10)
	at lc.i.c(com.google.mlkit:common@@18.0.0:13)
	at ma.m9.a(com.google.mlkit:vision-common@@17.0.0:5)
	at lc.e.b(com.google.mlkit:common@@18.0.0:20)
	at ma.n9.a(com.google.mlkit:vision-common@@17.0.0:18)
	at ma.n9.b(com.google.mlkit:vision-common@@17.0.0:14)
	at nc.a.n(com.google.mlkit:vision-common@@17.0.0:3)
	at nc.a.m(com.google.mlkit:vision-common@@17.0.0:171)
	at nc.a.c(com.google.mlkit:vision-common@@17.0.0:2)
	at d7.c0$a$a$b.a(TakePicture.kt:27)
	at androidx.camera.core.j1$h.d(ImageCapture.java:3)
	at androidx.camera.core.j1$h.b(ImageCapture.java:1)
	at androidx.camera.core.l1.run(R8$$SyntheticClass:5)
	at d7.c0$a$a$a$a.invokeSuspend(TakePicture.kt:13)
	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.c1.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
	Suppressed: kotlinx.coroutines.a1: [x2{Cancelling}@3968f95, Dispatchers.Main]
```

**Comment by illerokcob** [comment]
It is strange, I could not reproduce on my device. It seems the app tries to connect through google play services to access the mlkit feature built into the services bundle, but obviously it fails because microG does not have the required classes. On my device, the DeepL app has the text recognizer mlkit bundled and it uses the internal library for that feature to work. 
Could you please copy the exact DeepL app version? Maybe there are versions which do not have the mlkit library bundled or it could be a simple bug in the app itself, I don't know..

**Comment by Wojtaz0w** [comment]
DeepL 2.0 (57) still crashes.
https://paste.crdroid.net/YIifFz
`time: 1684528829303
msg: java.lang.IllegalStateException: MlKitContext has not been initialized
stacktrace: java.lang.IllegalStateException: MlKitContext has not been initialized
	at ab.p.j(com.google.android.gms:play-services-basement@@18.1.0:10)
	at ld.i.c(com.google.mlkit:common@@18.0.0:13)
	at lb.m9.a(com.google.mlkit:vision-common@@17.0.0:5)
	at ld.e.b(com.google.mlkit:common@@18.0.0:20)
	at lb.n9.a(com.google.mlkit:vision-common@@17.0.0:18)
	at lb.n9.b(com.google.mlkit:vision-common@@17.0.0:14)
	at nd.a.n(com.google.mlkit:vision-common@@17.0.0:3)
	at nd.a.m(com.google.mlkit:vision-common@@17.0.0:171)
	at nd.a.c(com.google.mlkit:vision-common@@17.0.0:2)
	at k7.c0$a$a$b.a(TakePicture.kt:27)
	at androidx.camera.core.j1$h.d(ImageCapture.java:3)
	at androidx.camera.core.j1$h.b(ImageCapture.java:1)
	at androidx.camera.core.l1.run(R8$$SyntheticClass:5)
	at k7.c0$a$a$a$a.invokeSuspend(TakePicture.kt:13)
	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.c1.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
	Suppressed: kotlinx.coroutines.a1: [x2{Cancelling}@c5e04cb, Dispatchers.Main]`
I use microG installer revived 3.3.1-0 (https://github.com/nift4/microg_installer_revived) if that may help.

**Comment by Wojtaz0w** [comment]
For me still crashes as of 0.2.28 
https://paste.crdroid.net/8ccRtL

**Comment by Wojtaz0w** [comment]
How did you install microG? I did via microG_installer_revived

**Comment by ale5000-git** [comment]
For those that use microG unofficial installer there is a test build with the latest microG: https://androidfilehost.com/?fid=10620683726822057114

**Comment by Wojtaz0w** [comment]
Today I noticed that App Manager blocked mlkit as a "tracker" and thats what caused picture translating not to work. I unblocked it and works perfectly. Sorry for not noticing earlier. 

![Screenshot_20230611-134254_App Manager.png](https://github.com/microg/GmsCore/assets/104674625/936202fd-dc44-47d7-beea-f7f60e302d42)

These two need to be unchecked
