### ISSUE TITLE
[it.hype.app] App displays error modal and stops before initial loading

### ISSUE THREAD

**Issue by kde3kko** [microg/GmsCore#1926]
**Affected app**
Name: Hype
Package id: [it.hype.app]
https://play.google.com/store/apps/details?id=it.hype.app

**Describe the bug**
When opening the app it displays an error modal with title "Something went wrong" and description "Check that Google Play is enabled on your device and that you're using an up-to-date version before opening the app".

It then gives the only option to close the app.

**To Reproduce**
1. Open the app at version > 7.0.0 (e.g. 7.2.0) on a Xiaomi mi 9 SE (only device I have) using microg

**Expected behavior**
App should open normally without complaining about missing Play Services

**Screenshots**
<none included>

**System**
Android Version: [e.g. 13]
Custom ROM: LineageOS 20 for microg v. 20-20230410-microG-grus

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: All ticked

**Additional context**
App is installed via Aurora Store using session installer (default)
Previous versions of the app worked fine (up until 7.0.0)
Problem appeared on version 7.2.0 (published April, 17)

adb logcat shows:

```
04-30 23:26:09.538  1624  3373 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found

04-30 23:26:09.540 29025 29025 E LicenseClientV3: Error while checking license: com.pairip.licensecheck3.LicenseClientV3$LicenseCheckException: Could not bind with the licensing service.

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.connectToLicensingService(LicenseClientV3.java:107)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.$r8$lambda$mdXeWrbXjkADjcVRgNH0zKMqAIU(Unknown Source:0)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3$$ExternalSyntheticLambda3.run(Unknown Source:2)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at android.os.Handler.handleCallback(Handler.java:942)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at android.os.Looper.loopOnce(Looper.java:201)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at android.os.Looper.loop(Looper.java:288)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at android.app.ActivityThread.main(ActivityThread.java:7884)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)

04-30 23:26:09.540 29025 29025 E LicenseClientV3: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by kde3kko** [comment]
Update: seems very similar to https://github.com/microg/GmsCore/issues/1825
