### ISSUE TITLE
Many dialogue boxes "microg services core keeps stopping"

### ISSUE THREAD

**Issue by robinpaulson** [microg/GmsCore#1953]
Lineageos 16
Samsung galaxy s5 mini
Microg 0.28, manually installed
Up to date gsf proxy and fake store

I've used microg for over a year, no problems, until today's upgrade.

Logcat shows this message or similar, many times

FATAL EXCEPTION: NetworkLocationService
Process: com.google.android.gms, PID: 20227
java.lang.NullPointerException: telephonyManager.allCellInfo must not be null
	at org.microg.gms.location.network.cell.CellDetailsSource.startScan(CellDetailsSource.kt:32)
	at org.microg.gms.location.network.NetworkLocationService.scan(NetworkLocationService.kt:86)
	at org.microg.gms.location.network.NetworkLocationService.highPowerScanRunnable$lambda-0(NetworkLocationService.kt:45)
	at org.microg.gms.location.network.NetworkLocationService.$r8$lambda$JuZpzAgFbVF3vF3Avck0xJkSwHY(Unknown Source:0)
	at org.microg.gms.location.network.NetworkLocationService$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by robinpaulson** [comment]
Turning on location services prevents the dialogues. I'm not sure that's a solution though
