### ISSUE TITLE
nz.co.kiwibank.mobile crashing

### ISSUE THREAD

**Issue by robinpaulson** [microg/GmsCore#1959]
FATAL EXCEPTION: main
Process: nz.co.kiwibank.mobile, PID: 20650
java.lang.NullPointerException: null cannot be cast to non-null type androidx.appcompat.widget.SearchView
	at nz.co.kiwibank.mobile.ui.payTransfer.fragments.a.Mf(SourceFile:3)
	at androidx.fragment.app.Fragment.pg(SourceFile:3)
	at androidx.fragment.app.FragmentManager.E(SourceFile:3)
	at androidx.fragment.app.FragmentManager$c.d(Unknown Source:2)
	at androidx.core.view.l.e(SourceFile:2)
	at androidx.activity.ComponentActivity.onCreatePanelMenu(SourceFile:2)
	at androidx.appcompat.view.i.onCreatePanelMenu(Unknown Source:2)
	at androidx.appcompat.app.g$n.onCreatePanelMenu(SourceFile:2)
	at androidx.appcompat.app.s.B(SourceFile:5)
	at androidx.appcompat.app.s$a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by robinpaulson** [comment]
Lineage 16, microg 0.28.
