### ISSUE TITLE
[nl.devolksbank.asn.bankieren] Cannot scan QR codes because of missing mlkit barcode scanning module

### ISSUE THREAD

**Issue by blackdragon2447** [microg/GmsCore#1966]
**Affected app**
Name: ASN Bank
Package id: nl.devolksbank.asn.bankieren

**Describe the bug**
The app cannot scan QR codes. The app's build in QR Code scanner opens fine and doesn't report an error but will not actually scan any QR Codes

**To Reproduce**
1. After opening the app log in.
2. Click the QR symbol in the top right.
3. Point the camera at a QR Code
4. Nothing Happens 

**Expected behavior**
The QR Code gets scanned.

**System**
Android Version: 11
Custom ROM: /e/OS 1.11-20230509288096

**microG**
microG Core version: 0.2.27.223616-1
microG Self-Check results: All ticked

**Additional context**
logcat:
```
6-22 13:36:30.403 10426 10673 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
06-22 13:36:29.814     0     0 I [0:  kworker/u17:3: 8770] [SSP]: MSG From MCU - SSP_batch_full 60 60 0
06-22 13:36:29.814     0     0 I         : [0:  kworker/u17:3: 8770] Pack = 0 966 980 60
06-22 13:36:30.409 25608 25627 D GmsDummySvc: bound by: GetServiceRequest{serviceId=UNKNOWN(308), gmsVersion=12451000, packageName='nl.devolksbank.asn.bankieren', extras=Bundle[{}]}
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: Failed to check feature availability
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: o.uV: 17: API: ModuleInstall.API is not available on this device. Connection failed with: uA{statusCode=CANCELED, resolution=null, message=null}
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.vd.read(:1003)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.wr.RemoteActionCompatParcelizer(:1)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.vP.setContentView(:7)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.vP.write(:2)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.vP.setContentView(:24)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.vP.RemoteActionCompatParcelizer(:1)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.xu.IconCompatParcelizer(:1)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.xO.read(:2)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.xG.RemoteActionCompatParcelizer(:3)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.xJ.read(:3)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at o.xK.handleMessage(:31)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at android.os.Looper.loop(Looper.java:223)
06-22 13:36:30.411 10426 10426 E OptionalModuleUtils: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: Failed to complete the task of features availability check
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: java.util.concurrent.ExecutionException: o.uV: 17: API: ModuleInstall.API is not available on this device. Connection failed with: uA{statusCode=CANCELED, resolution=null, message=null}
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.agW.setContentView(:5)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.agW.read(:8)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atz.write(:9)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atz.read(:3)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.aup.setContentView(:6)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.aum.setContentView(:1)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atN.run(:1004)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atY.run(:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atC.IconCompatParcelizer(:4)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atC.setContentView(:1)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atP.run(Unknown Source:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atC.read(:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.atM.run(Unknown Source:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at java.lang.Thread.run(Thread.java:923)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: Caused by: o.uV: 17: API: ModuleInstall.API is not available on this device. Connection failed with: uA{statusCode=CANCELED, resolution=null, message=null}
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.vd.read(:1003)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.wr.RemoteActionCompatParcelizer(:1)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.vP.setContentView(:7)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.vP.write(:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.vP.setContentView(:24)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.vP.RemoteActionCompatParcelizer(:1)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.xu.IconCompatParcelizer(:1)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.xO.read(:2)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.xG.RemoteActionCompatParcelizer(:3)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.xJ.read(:3)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at o.xK.handleMessage(:31)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at android.os.Looper.loop(Looper.java:223)
06-22 13:36:30.411 10426 10673 E OptionalModuleUtils: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by blackdragon2447** [comment]
Related: https://github.com/microg/GmsCore/issues/395#issuecomment-1541025563

**Comment by Beanow** [comment]
Same issue with Digid now depending on the [ML Kit scanner](https://developers.google.com/ml-kit/vision/barcode-scanning/). Using a different app I can immediately get a scan result it's purely a hard dependency on the Google module causing this to fail.

```
07-08 13:16:35.660  7415  9601 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
07-08 13:16:35.663  3341  3365 D GmsDummySvc: bound by: GetServiceRequest{serviceId=UNKNOWN(308), gmsVersion=12451000, packageName='nl.rijksoverheid.digid.pub', extras=Bundle[{}]}
07-08 13:16:35.664  7415  7415 E OptionalModuleUtils: Failed to check feature availability
07-08 13:16:35.664  7415  7415 E OptionalModuleUtils: com.google.android.gms.common.api.ApiException: 17: API: ModuleInstall.API is not available on this device. Connection failed with: ConnectionResult{statusCode=CANCELED, resolution=null, message=null}
```

**Comment by TheLastProject** [comment]
As a workaround, the "business" version (aka: the old app) [nl.asnbank.asnbankieren](https://play.google.com/store/apps/details?id=nl.asnbank.asnbankieren), version 2.46.0 (latest at moment of writing) works fine and can be used for personal accounts too.

But yes, I'd love to see this fixed too and can confirm the same issue on:
**System**
Android Version: 13
Custom ROM: LineageOS 20-20230704-microG-FP3

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: All ticked

**Comment by Sjoerdfc** [comment]
It looks like ASN changed their app. I contacted customer support months ago to complain about this, and never heard anything. But with the ASN Bank version released on october 5th I can now scan QR codes.
