### ISSUE TITLE
GmsCore crashes on device without GPS provider

### ISSUE THREAD

**Issue by goffioul** [microg/GmsCore#2005]
I have a device running Android 13 (android-x86) and GmsCore-0.2.28.231657. The device does not have a gnss HAL (no hardware, gnss HAL service not installed or running). In that case, there is no GPS location provider. When an app requests location, e.g. MyChart, the GmsCore app crashes with the following backtrace:
```
08-04 09:59:06.536  1379  2246 D LocationManager: getLastLocationWithReceiver by epic.mychart.android
08-04 09:59:06.547  1379  1379 D LocationManager: Note app epic.mychart.android @ null
08-04 09:59:06.566  1379  2246 D LocationManager: registerLocationUpdates (callback) by epic.mychart.android
08-04 09:59:06.675  1379  1379 E AndroidRuntime: FATAL EXCEPTION: main
08-04 09:59:06.675  1379  1379 E AndroidRuntime: Process: com.google.android.gms, PID: 1379
08-04 09:59:06.675  1379  1379 E AndroidRuntime: java.lang.IllegalArgumentException: provider "gps" does not exist
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1306)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1564)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.core.location.LocationManagerCompat$Api31Impl.requestLocationUpdates(LocationManagerCompat.java:1088)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.core.location.LocationManagerCompat.requestLocationUpdates(LocationManagerCompat.java:292)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationManager.onRequestManagerUpdated(LocationManager.kt:188)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationManager.access$onRequestManagerUpdated(LocationManager.kt:40)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationManager$requestManager$2$1.invoke(LocationManager.kt:45)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationManager$requestManager$2$1.invoke(LocationManager.kt:45)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationRequestManager.notifyRequestDetailsUpdated(LocationRequestManager.kt:257)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationRequestManager.check(LocationRequestManager.kt:242)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationRequestManager.checkWhileHighAccuracy(LocationRequestManager.kt:249)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationRequestManager.access$checkWhileHighAccuracy(LocationRequestManager.kt:33)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at org.microg.gms.location.manager.LocationRequestManager$recalculateRequests$1.invokeSuspend(LocationRequestManager.kt:196)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:174)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invokeSuspend(PausingDispatcher.kt:162)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invoke(Unknown Source:8)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.PausingDispatcherKt$whenStateAtLeast$2.invoke(Unknown Source:4)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.PausingDispatcherKt.whenStateAtLeast(PausingDispatcher.kt:156)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.PausingDispatcherKt.whenStarted(PausingDispatcher.kt:60)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at androidx.lifecycle.LifecycleCoroutineScope$launchWhenStarted$1.invokeSuspend(Lifecycle.kt:97)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-04 09:59:06.675  1379  1379 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
My understanding is that the gnss HAL is optional, so I would expect GmsCore to be able to cope with that scenario:
https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/compatibility_matrices/compatibility_matrix.7.xml;l=249;bpv=0

**Comment by chirayudesai** [comment]
Still running into this even with the "Handle rare sidecases" commit. Stacktrace differs

```
09-12 18:17:20.247 10115  2762  2762 D AndroidRuntime: Shutting down VM
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime: FATAL EXCEPTION: main
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime: Process: com.google.android.gms, PID: 2762
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime: java.lang.RuntimeException: Unable to create service org.microg.gms.location.network.NetworkLocationService: java.lang.IllegalArgumentException: provider "gps" does not exist
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4499)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Looper.loopOnce(Looper.java:201)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:288)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:7924)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: provider "gps" does not exist
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Parcel.createException(Parcel.java:2995)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Parcel.readException(Parcel.java:2978)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Parcel.readException(Parcel.java:2920)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1306)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1564)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at androidx.core.location.LocationManagerCompat$Api31Impl.requestLocationUpdates(LocationManagerCompat.java:1088)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at androidx.core.location.LocationManagerCompat.requestLocationUpdates(LocationManagerCompat.java:292)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at org.microg.gms.location.network.NetworkLocationService.onCreate(NetworkLocationService.kt:92)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4486)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  ... 9 more
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:727)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:590)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Binder.execTransactInternal(Binder.java:1285)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:  at android.os.Binder.execTransact(Binder.java:1244)
09-12 18:17:20.249 10115  2762  2762 E AndroidRuntime:
```

**Comment by ale5000-git** [comment]
@chirayudesai

Hi,
I'm trying to fix the issue; could you please try this to see if the problem is fixed?
https://androidfilehost.com/?fid=10620683726822078822

IMPORTANT: It is signed by me so you need to remove the existing one before installing it.

**Comment by chirayudesai** [comment]
@ale5000-git thanks for your help!

Unfortunately I haven't been able to reproduce the issue myself yet, and the reports are from production devices running signed builds with a locked bootloader, making it hard to test a differently signed APK directly.

**Comment by ale5000-git** [comment]
@chirayudesai
The patch is here: https://github.com/micro5k/GmsCoreMod/tree/patch-location-fix
but I prefer to wait at least one report before creating a pull request.
