### ISSUE TITLE
microG issue with firebase 

### ISSUE THREAD

**Issue by AhmadNosratian** [microg/GmsCore#2020]
**Firebase apis like Crashlytics,CloudMessaging not working with microG.**

 FirebaseCrashlytics     com.b.mysampleapplication        E  Settings request failed.
                                                                                                    java.net.SocketTimeoutException: failed to connect to localhost/127.0.0.1 (port 443) from /127.0.0.1 (port 46002) after 10000ms
                                                                                                    	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
                                                                                                    	at libcore.io.IoBridge.connect(IoBridge.java:179)
                                                                                                    	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
                                                                                                    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
                                                                                                    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
                                                                                                    	at java.net.Socket.connect(Socket.java:646)

 FirebaseMessaging       com.b.mysampleapplication        E  Failed to get FIS auth token
                                                                                                    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
                                                                                                    	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
                                                                                                    	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(GmsRpc.java:260)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.startRpc(GmsRpc.java:222)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.getToken(GmsRpc.java:180)

FirebaseCrashlytics     com.b.mysampleapplication        E  Cannot send reports. Timed out while fetching settings.

**Comment by mar-v-in** [comment]
This looks unrelated to microG. The error message suggests that your DNS server reported 127.0.0.1 when connecting to the Firebase Installations service for requesting a token. You likely have some privacy blocking in your DNS (e.g. PiHole)
