### ISSUE TITLE
Conscrypt error on KitKat and lower

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2023]
**Affected app**
Name: Google Calendar Sync 5.2.3-99827563 (2015080710)
Package id: com.google.android.syncadapters.calendar

**Describe the bug**
It was working in the past but now no longer works.

**System**
Android Version: Android 4.4.4

**microG**
microG Core version: 0.2.28.231657-28 (a749fe4)
microG Self-Check results: All ticked
![self-check](https://github.com/microg/GmsCore/assets/15793015/b613bd58-036c-4028-a644-328c19700c84)

**Additional context**
Logcat:
```
I/ActivityManager(  481): Start proc com.google.android.syncadapters.calendar for service com.google.android.syncadapters.calendar/.CalendarSyncAdapterService: pid=1561 uid=10054 gids={50054, 3003}
D/dalvikvm(  481): GC_CONCURRENT freed 11507K, 68% free 6511K/19892K, paused 1ms+1ms, total 24ms
W/audio_hw_primary(  166): out_write() limiting sleep time 44149 to 23219
W/audio_hw_primary(  166): out_write() limiting sleep time 55759 to 23219
D/GmsServicesProvider(  839): query caller=com.google.android.syncadapters.calendar name=calendar_ssa_analytics_sampling_rate value=null
I/dalvikvm( 1561): Could not find method android.app.Notification$Builder.setLocalOnly, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
W/dalvikvm( 1561): VFY: unable to resolve virtual method 25: Landroid/app/Notification$Builder;.setLocalOnly (Z)Landroid/app/Notification$Builder;
D/dalvikvm( 1561): VFY: replacing opcode 0x6e at 0x00c2
I/dalvikvm( 1561): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzl
W/dalvikvm( 1561): VFY: unable to resolve virtual method 174: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm( 1561): VFY: replacing opcode 0x6e at 0x000b
W/audio_hw_primary(  166): out_write() limiting sleep time 37369 to 23219
D/GmsPlayLogSvc(  839): onBind: Intent { act=com.google.android.gms.playlog.service.START pkg=com.google.android.gms }
D/dalvikvm( 1561): GC_CONCURRENT freed 277K, 11% free 2779K/3120K, paused 3ms+1ms, total 7ms
D/GmsPlayLogSvc(  839): bound by: GetServiceRequest{serviceId=PLAY_LOG, gmsVersion=7571000, packageName='com.google.android.syncadapters.calendar', extras=Bundle[{}]}
W/audio_hw_primary(  166): out_write() limiting sleep time 28979 to 23219
I/AnalyticsLogBase( 1561): PlayLogger.onLoggerConnected
I/dalvikvm( 1561): Could not find method android.content.Context.checkSelfPermission, referenced from method com.google.android.calendar.PermissionsCompat.checkSelfPermission
W/dalvikvm( 1561): VFY: unable to resolve virtual method 97: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm( 1561): VFY: replacing opcode 0x6e at 0x0006
D/GmsServicesProvider(  839): query caller=com.google.android.syncadapters.calendar name=google_calendar_calendar_colors value=null
D/GmsServicesProvider(  839): query caller=com.google.android.syncadapters.calendar name=google_calendar_event_colors value=null
E/ProviderInstaller( 1561): Failed to install provider: Didn't find class "com.google.android.gms.common.security.ProviderInstallerImpl" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/GmsCore.apk"],nativeLibraryDirectories=[/system/lib]]
E/ConscryptUtils( 1561): Unrecoverable error from installIfNeeded, in installSecurityProvider
E/ConscryptUtils( 1561): com.google.android.gms.common.GooglePlayServicesNotAvailableException
E/ConscryptUtils( 1561): 	at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
E/ConscryptUtils( 1561): 	at com.google.android.syncadapters.calendar.ConscryptUtils.installSecurityProvider(ConscryptUtils.java:21)
E/ConscryptUtils( 1561): 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.performSync(CalendarSyncAdapterApiary.java:536)
E/ConscryptUtils( 1561): 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.onPerformLoggedSync(CalendarSyncAdapterApiary.java:440)
E/ConscryptUtils( 1561): 	at com.android.emailcommon.syncadapter.LoggingThreadedSyncAdapter.onPerformSync(LoggingThreadedSyncAdapter.java:49)
E/ConscryptUtils( 1561): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
E/CalendarSyncAdapter( 1561): Conscrypt error during sync
E/CalendarSyncAdapter( 1561): com.google.android.syncadapters.calendar.ConscryptInstallationException: Error from installSecurityProvider
E/CalendarSyncAdapter( 1561): 	at com.google.android.syncadapters.calendar.ConscryptUtils.installSecurityProvider(ConscryptUtils.java:36)
E/CalendarSyncAdapter( 1561): 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.performSync(CalendarSyncAdapterApiary.java:536)
E/CalendarSyncAdapter( 1561): 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.onPerformLoggedSync(CalendarSyncAdapterApiary.java:440)
E/CalendarSyncAdapter( 1561): 	at com.android.emailcommon.syncadapter.LoggingThreadedSyncAdapter.onPerformSync(LoggingThreadedSyncAdapter.java:49)
E/CalendarSyncAdapter( 1561): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
E/CalendarSyncAdapter( 1561): Caused by: com.google.android.gms.common.GooglePlayServicesNotAvailableException
E/CalendarSyncAdapter( 1561): 	at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
E/CalendarSyncAdapter( 1561): 	at com.google.android.syncadapters.calendar.ConscryptUtils.installSecurityProvider(ConscryptUtils.java:21)
E/CalendarSyncAdapter( 1561): 	... 4 more
W/audio_hw_primary(  166): out_write() limiting sleep time 31178 to 23219
I/ActivityManager(  481): Killing 933:com.android.dialer/u0a4 (adj 15): empty #17
D/SyncManager(  481): failed sync operation [sample_mail]@gmail.com u0 (com.google), com.android.calendar, SERVER, latestRunTime 115743, reason: AutoSync, SyncResult: stats [ numParseExceptions: 1]
D/SyncManager(  481): not retrying sync operation because the error is a hard error: [sample_mail]@gmail.com u0 (com.google), com.android.calendar, SERVER, latestRunTime 115893, reason: AutoSync
D/dalvikvm(  633): GC_CONCURRENT freed 424K, 11% free 3988K/4464K, paused 2ms+2ms, total 9ms
I/GAV2    ( 1561): Thread[GAThread,5,main]: No campaign data found.
I/LeapdroidClipboardServer(  481): accept new connection
I/LeapdroidClipboardServer(  481): handle new connection in new thread
I/LeapdroidClipboardServer(  481): new connection is 99
I/LeapdroidClipboardServer(  481): read 19 UTF-16 chars
I/LeapdroidClipboardServer(  481): Client Says: is not an ABI2 app
I/LeapdroidClipboardClient(  481): copy plain text
I/LeapdroidClipboardClient(  481): connected leapdroid.clipboard.server.c
I/LeapdroidClipboardClient(  481): the message is: is not an ABI2 app
```

**Comment by ale5000-git** [comment]
@mar-v-in
I wanted to try something but even if `gradlew buildWithMapboxWithNearbyReleasePreBundle` build successfully the apk is NOT created.

Do you know why?

**Comment by mar-v-in** [comment]
I think you are looking for `gradlew :play-services-core:assembleWithMapboxWithNearbyRelease` target

**Comment by ale5000-git** [comment]
@mar-v-in
I have just compiled without any change, remove Google account from the device, replace GmsCore.apk, restart, re-add Google account and it appears but when visiting the account under Android settings it always crash.

Do you know why?

Logcat:
```
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.settings), err=0
I/ActivityManager(  481): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 2354
W/ActivityManager(  481): resume package=com.android.settings
D/dalvikvm(  481): GC_CONCURRENT freed 882K, 17% free 6581K/7924K, paused 3ms+1ms, total 10ms
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.settings), err=0
W/audio_hw_primary(  169): out_write() limiting sleep time 44149 to 23219
W/ActivityManager(  481): resume package=com.android.settings
D/SubSettings( 2354): Launching fragment com.android.settings.accounts.ManageAccountsSettings
W/audio_hw_primary(  169): out_write() limiting sleep time 55759 to 23219
D/AndroidRuntime( 2354): Shutting down VM
W/dalvikvm( 2354): threadid=1: thread exiting with uncaught exception (group=0xa4ca5b38)
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
E/AndroidRuntime( 2354): FATAL EXCEPTION: main
E/AndroidRuntime( 2354): Process: com.android.settings, PID: 2354
E/AndroidRuntime( 2354): java.lang.NullPointerException
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.updatePreferenceIntents(ManageAccountsSettings.java:410)
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.addAuthenticatorSettings(ManageAccountsSettings.java:350)
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.onAccountsUpdated(ManageAccountsSettings.java:337)
E/AndroidRuntime( 2354): 	at android.accounts.AccountManager$12.run(AccountManager.java:1442)
E/AndroidRuntime( 2354): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2354): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2354): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2354): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 2354): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2354): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2354): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 2354): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 2354): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  481):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager(  481):   Force finishing activity com.android.settings/.Settings
W/ActivityManager(  481): resume package=com.android.launcher
W/audio_hw_primary(  169): out_write() limiting sleep time 57369 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 38979 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 30589 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 23876 to 23219
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
W/ActivityManager(  481): Activity pause timeout for ActivityRecord{529afaa0 u0 com.android.settings/.SubSettings t7 f}
W/ActivityManager(  481): resume package=com.android.launcher
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
W/ActivityManager(  481): resume package=com.android.launcher
W/EGL_emulation(  683): eglSurfaceAttrib not implemented(attribute=12435, value=12436), simply return EGL_TRUE
I/ActivityManager(  481): Killing 732:com.android.music/u0a27 (adj 15): empty #17
W/MediaFocusControl(  481):   RemoteControlClient died
I/Process ( 2354): Sending signal. PID: 2354 SIG: 9
E/JavaBinder(  481): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  481): !!! FAILED BINDER TRANSACTION !!!
D/leapdroid_hostime(  650): noticeInputStart cmd:0
W/InputMethodManagerService(  481): Got RemoteException sending setActive(false) notification to pid 2354 uid 1000
W/InputDispatcher(  481): channel '52928b6c com.android.settings/com.android.settings.Settings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  481): channel '52928b6c com.android.settings/com.android.settings.Settings (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  481): channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  481): channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  481): Attempted to unregister already unregistered input channel '52928b6c com.android.settings/com.android.settings.Settings (server)'
I/ActivityManager(  481): Process com.android.settings (pid 2354) has died.
I/WindowState(  481): WIN DEATH: Window{52928b6c u0 com.android.settings/com.android.settings.Settings}
W/InputDispatcher(  481): Attempted to unregister already unregistered input channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)'
I/WindowState(  481): WIN DEATH: Window{528c09a8 u0 com.android.settings/com.android.settings.SubSettings}
E/leapdroid(  650): inputType:0
E/leapdroid(  650): s_bStartInput:true s_bFinishInput:true
```
