### ISSUE TITLE
Commit "Add basic Google account settings" break Android settings on KitKat

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2024]
Hi,
I have moved here the message that was in the other post since it is a separate issue.

I have compiled microG on Windows as is (without any change).
On Android 4.4.4 it works in general and even allow to add a Google account correctly but when visiting the account in the Android settings the Settings app crash.

The crash happens in the Android code, exactly here: https://android.googlesource.com/platform/packages/apps/Settings/+/refs/tags/android-4.4.4_r2.0.1/src/com/android/settings/accounts/ManageAccountsSettings.java#410

Does someone know why?

Logcat:
```
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.settings), err=0
I/ActivityManager(  481): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 2354
W/ActivityManager(  481): resume package=com.android.settings
D/dalvikvm(  481): GC_CONCURRENT freed 882K, 17% free 6581K/7924K, paused 3ms+1ms, total 10ms
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.settings), err=0
W/audio_hw_primary(  169): out_write() limiting sleep time 44149 to 23219
W/ActivityManager(  481): resume package=com.android.settings
D/SubSettings( 2354): Launching fragment com.android.settings.accounts.ManageAccountsSettings
W/audio_hw_primary(  169): out_write() limiting sleep time 55759 to 23219
D/AndroidRuntime( 2354): Shutting down VM
W/dalvikvm( 2354): threadid=1: thread exiting with uncaught exception (group=0xa4ca5b38)
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
E/AndroidRuntime( 2354): FATAL EXCEPTION: main
E/AndroidRuntime( 2354): Process: com.android.settings, PID: 2354
E/AndroidRuntime( 2354): java.lang.NullPointerException
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.updatePreferenceIntents(ManageAccountsSettings.java:410)
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.addAuthenticatorSettings(ManageAccountsSettings.java:350)
E/AndroidRuntime( 2354): 	at com.android.settings.accounts.ManageAccountsSettings.onAccountsUpdated(ManageAccountsSettings.java:337)
E/AndroidRuntime( 2354): 	at android.accounts.AccountManager$12.run(AccountManager.java:1442)
E/AndroidRuntime( 2354): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2354): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2354): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2354): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 2354): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2354): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2354): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 2354): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 2354): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  481):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager(  481):   Force finishing activity com.android.settings/.Settings
W/ActivityManager(  481): resume package=com.android.launcher
W/audio_hw_primary(  169): out_write() limiting sleep time 57369 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 38979 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 30589 to 23219
W/audio_hw_primary(  169): out_write() limiting sleep time 23876 to 23219
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
W/ActivityManager(  481): Activity pause timeout for ActivityRecord{529afaa0 u0 com.android.settings/.SubSettings t7 f}
W/ActivityManager(  481): resume package=com.android.launcher
I/android_os_LeapdroidJNI(  481): Leapdroid_set()
I/android_os_LeapdroidJNI(  481): Leapdroid_set(): setPropVBox(key=android_launched_package, val=com.android.launcher), err=0
W/ActivityManager(  481): resume package=com.android.launcher
W/EGL_emulation(  683): eglSurfaceAttrib not implemented(attribute=12435, value=12436), simply return EGL_TRUE
I/ActivityManager(  481): Killing 732:com.android.music/u0a27 (adj 15): empty #17
W/MediaFocusControl(  481):   RemoteControlClient died
I/Process ( 2354): Sending signal. PID: 2354 SIG: 9
E/JavaBinder(  481): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  481): !!! FAILED BINDER TRANSACTION !!!
D/leapdroid_hostime(  650): noticeInputStart cmd:0
W/InputMethodManagerService(  481): Got RemoteException sending setActive(false) notification to pid 2354 uid 1000
W/InputDispatcher(  481): channel '52928b6c com.android.settings/com.android.settings.Settings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  481): channel '52928b6c com.android.settings/com.android.settings.Settings (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  481): channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  481): channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  481): Attempted to unregister already unregistered input channel '52928b6c com.android.settings/com.android.settings.Settings (server)'
I/ActivityManager(  481): Process com.android.settings (pid 2354) has died.
I/WindowState(  481): WIN DEATH: Window{52928b6c u0 com.android.settings/com.android.settings.Settings}
W/InputDispatcher(  481): Attempted to unregister already unregistered input channel '528c09a8 com.android.settings/com.android.settings.SubSettings (server)'
I/WindowState(  481): WIN DEATH: Window{528c09a8 u0 com.android.settings/com.android.settings.SubSettings}
E/leapdroid(  650): inputType:0
E/leapdroid(  650): s_bStartInput:true s_bFinishInput:true
```

**Comment by ale5000-git** [comment]
@mar-v-in
I have found the cause, reverting this commit fix the crash of Android settings on legacy devices: https://github.com/microg/GmsCore/commit/dcf5f1fecb9add7e640a6bb780cb0c752e5c025e?diff=split

**Comment by mar-v-in** [comment]
Can you try if this patch helps?
```patch
--- a/play-services-core/src/main/res/xml/preferences_auth.xml	2023-08-24 11:51:41.540969319 +0200
+++ b/play-services-core/src/main/res/xml/preferences_auth.xml	2023-09-07 21:29:16.594943370 +0200
@@ -40,6 +40,7 @@
         android:key="legacy"
         android:title="Legacy settings">
         <intent
+            android:action="android.intent.action.VIEW"
             android:targetClass="org.microg.gms.ui.LegacyAccountSettingsActivity"
             android:targetPackage="com.google.android.gms" />
     </PreferenceScreen>

```

**Comment by ale5000-git** [comment]
@mar-v-in
It fix the problem, thanks :-)

**Comment by ale5000-git** [comment]
Fixed by: https://github.com/microg/GmsCore/commit/11001291e19333a1cb37f77196067222c76b4fb7
