### ISSUE TITLE
Key app expected String but value was a android.app.PendingIntent.  The default value <null> was returned.

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2029]
Here:
https://github.com/microg/GmsCore/tree/11001291e19333a1cb37f77196067222c76b4fb7/play-services-core/src/main/java/org/microg/gms/gcm/RegisterRequest.java#L127

Logcat:
```
D/GmsHttpFormClient( 2400): androidId=***&app=com.android.vending&client_sig=***&callerPkg=com.google.android.gms&callerSig=***&device_country=us&Email=***&lang=en_US&operatorCountry=us&service=androidmarket&source=android&Token=***&google_play_services_version=233013000&is_called_from_account_manager=1&_opt_is_called_from_account_manager=1&sdk_version=21&system_partition=1
D/GmsGcmRegister( 2499): register[req]: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } extras=Bundle[{sender=932144863878, app=PendingIntent{1d5e35e1: android.os.BinderProxy@28daf06}}]
D/ProfileManager( 2499): Using Serial ***
W/Bundle  ( 2499): Key app expected String but value was a android.app.PendingIntent.  The default value <null> was returned.
W/Bundle  ( 2499): Attempt to cast generated internal exception:
W/Bundle  ( 2499): java.lang.ClassCastException: android.app.PendingIntent cannot be cast to java.lang.String
W/Bundle  ( 2499): 	at android.os.BaseBundle.getString(BaseBundle.java:921)
W/Bundle  ( 2499): 	at org.microg.gms.gcm.RegisterRequest.extraParams(RegisterRequest.java:127)
W/Bundle  ( 2499): 	at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.kt:154)
W/Bundle  ( 2499): 	at org.microg.gms.gcm.PushRegisterService.handleIntent(PushRegisterService.kt:130)
W/Bundle  ( 2499): 	at org.microg.gms.gcm.PushRegisterService.access$handleIntent(PushRegisterService.kt:101)
W/Bundle  ( 2499): 	at org.microg.gms.gcm.PushRegisterService$onStartCommand$1.invokeSuspend(PushRegisterService.kt:118)
W/Bundle  ( 2499): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/Bundle  ( 2499): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/Bundle  ( 2499): 	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
W/Bundle  ( 2499): 	at androidx.lifecycle.DispatchQueue.resume(DispatchQueue.kt:54)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleController.observer$lambda-0(LifecycleController.kt:40)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleController.$r8$lambda$7XqClT_TFDHmqX3ARP07WvbP2Qg(LifecycleController.kt)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleController$$ExternalSyntheticLambda0.onStateChanged(D8$$SyntheticClass)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
W/Bundle  ( 2499): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
W/Bundle  ( 2499): 	at androidx.lifecycle.ServiceLifecycleDispatcher$DispatchRunnable.run(ServiceLifecycleDispatcher.java:106)
W/Bundle  ( 2499): 	at android.os.Handler.handleCallback(Handler.java:739)
W/Bundle  ( 2499): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/Bundle  ( 2499): 	at android.os.Looper.loop(Looper.java:135)
W/Bundle  ( 2499): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
W/Bundle  ( 2499): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 2499): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/Bundle  ( 2499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/Bundle  ( 2499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by mar-v-in** [comment]
This is merely a warning, it does not cause any harm except for log spam.

**Comment by ale5000-git** [comment]
Maybe it is just a minor thing but thanks for the fix :)
