### ISSUE TITLE
NPE with Firefox on /e/OS trying Fido2 Authentication

### ISSUE THREAD

**Issue by ne20002** [microg/GmsCore#2058]
I tried to test/use fido2 authentication on https://webauthn.me. This works with Firefox on Linux and FIdo2-Key. 
On /e/OS the challenge is started and when I choose to authenticate with either the device with fingerprint or using the same key that is working on Linux (with otg adapter) a NullPointerException occurs when touching fingerprint sensor.

**To Reproduce**
1. Start https://webauthn.me in Firefox on /e/OS
2. Start registration
3. Options are displayed for authentication, external USB token or device, is selectable -> select device
4. Prompted to used fingerprint
5. When touching fingerprint sensor, NPE occurs

**Expected behavior**
No NPE

**System**
Android Version: /e/OS S 1.15 (Android 12)
Custom ROM: /e/OS

**Additional context**
```
02ce77ea-8d55-4a16-8fbd-32944dc55996
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.NullPointerException: null reference
----
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.NullPointerException: null reference
	at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:22)
	at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:13)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$6(GeckoResult.java:63)
	at org.mozilla.geckoview.GeckoResult.$r8$lambda$nsAzyhhKgAo0Ha3SEAUSdsKADo8(GeckoResult.java:1)
	at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:9)
	at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$7(GeckoResult.java:17)
	at org.mozilla.geckoview.GeckoResult.$r8$lambda$JYfUuhIZf5JetbZ-qCaWvlWcPeE(GeckoResult.java:1)
	at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: null reference
	at com.google.android.gms.common.internal.Preconditions.checkNotNull([com.google.android.gms:play-services-basement@@18.1.0:1](mailto:com.google.android.gms:play-services-basement@@18.1.0:1))
	at com.google.android.gms.fido.fido2.api.common.AuthenticatorAttestationResponse.<init>([com.google.android.gms:play-services-fido@@20.0.1:19](mailto:com.google.android.gms:play-services-fido@@20.0.1:19))
	at com.google.android.gms.fido.fido2.api.common.zzk.createFromParcel([com.google.android.gms:play-services-fido@@20.0.1:79](mailto:com.google.android.gms:play-services-fido@@20.0.1:79))
	at com.google.android.gms.common.internal.safeparcel.SafeParcelableSerializer.deserializeFromBytes([com.google.android.gms:play-services-basement@@18.1.0:16](mailto:com.google.android.gms:play-services-basement@@18.1.0:16))
	at org.mozilla.geckoview.WebAuthnTokenManager.lambda$makeCredential$0(WebAuthnTokenManager.java:21)
	at org.mozilla.geckoview.WebAuthnTokenManager.$r8$lambda$mgx_0oGbYxl_yQV2hcq1rrAR1Vo(WebAuthnTokenManager.java:1)
	at org.mozilla.geckoview.WebAuthnTokenManager$$ExternalSyntheticLambda5.accept(R8$$SyntheticClass:5)
	at org.mozilla.geckoview.GeckoResult.lambda$accept$2(GeckoResult.java:1)
	at org.mozilla.geckoview.GeckoResult.$r8$lambda$9zWUu4Bh604Sdx3PHhezEs2AuyE(GeckoResult.java:1)
	at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda6.onValue(R8$$SyntheticClass:3)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$6(GeckoResult.java:11)
	... 13 more
```

**Comment by ale5000-git** [comment]
What is the exact version of microG GmsCore?

**Comment by ne20002** [comment]
Version 0.2.28.233013-135 (63b1553)-noen

**Comment by ne20002** [comment]
Version 0.2.28.233013-135 (63b1553)-noen
Firefox for Android 118
/e/OS 1.15 S

**Comment by ale5000-git** [comment]
I'm not completely sure but probably the problem was already fixed here: https://github.com/microg/GmsCore/commit/b3032b94c107380899632effdeccf7707fcbdf55

If you want you can try to update microG manually (to v0.2.29 or later), links are here:
https://github.com/micro5k/gmscore-info/

**Comment by ne20002** [comment]
2.29 can't be installed due to conflict with existing package.
:)

**Comment by ale5000-git** [comment]
Do you mean this one? https://gitlab.e.foundation/e/os/GmsCore/-/jobs/709954/artifacts/raw/play-services-core/build/outputs/apk/mapboxDefault/releaseStable/play-services-core-mapbox-default-releaseStable.apk

Or another build?

**Comment by ne20002** [comment]
For this it is the same error.

**Comment by ne20002** [comment]
![Screenshot_20230925-210013_Paketinstallation](https://github.com/microg/GmsCore/assets/39007279/62de9eb6-2084-485d-9f59-51a9dc0ce2d1)

**Comment by ale5000-git** [comment]
Never seen such error, have you tried to download it on the pc and install it via adb?

Example:
`adb install -r -g "./play-services-core-mapbox-default-releaseStable.apk"`

**Comment by ne20002** [comment]
Sorry
I'm not experienced with adb and Android. I may see if I get some more info on how to do this. But I may need some time.

**Comment by ne20002** [comment]
@ale5000-git 
I can confirm that with /e/OS 1.16 and Firefox for Android everything works well.
