### ISSUE TITLE
Logging into an account on one of my devices causes the android.process.acore application error

### ISSUE THREAD

**Issue by Artem13327** [microg/GmsCore#2079]
**Describe the bug**
Logging into an account on one of my devices causes the android.process.acore application error. There is no error without an account, because of this error the contacts application does not work

**System**
Android Version: [e.g. 10] 5.0.1
Custom ROM: [e.g. LineageOS 17.1] https://4pda.to/forum/index.php?showtopic=714661&view=findpost&p=95285552 (I removed some system applications)

**Comment by Typical0** [comment]
The issue was not fixed yet in the latest test version. Here's what I managed to get with logcat (on Android 4.4.4 with latest version installed):


``` E/JavaBinder( 3321): !!! FAILED BINDER TRANSACTION !!!
W/dalvikvm( 3321): threadid=12: thread exiting with uncaught exception (group=0x417abce0)
E/AndroidRuntime( 3321): FATAL EXCEPTION: ContactsProviderWorker
E/AndroidRuntime( 3321): Process: android.process.acore, PID: 3321
E/AndroidRuntime( 3321): java.lang.RuntimeException: Package manager has died
E/AndroidRuntime( 3321): 	at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:618)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactDirectoryManager.getDirectoryProviderPackages(ContactDirectoryManager.java:219)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactDirectoryManager.scanAllPackages(ContactDirectoryManager.java:256)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactDirectoryManager.scanAllPackagesIfNeeded(ContactDirectoryManager.java:191)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactDirectoryManager.scanAllPackages(ContactDirectoryManager.java:181)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactsProvider2.updateDirectoriesInBackground(ContactsProvider2.java:1996)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactsProvider2.performBackgroundTask(ContactsProvider2.java:1815)
E/AndroidRuntime( 3321): 	at com.android.providers.contacts.ContactsProvider2$1.handleMessage(ContactsProvider2.java:1501)
E/AndroidRuntime( 3321): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3321): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3321): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/AndroidRuntime( 3321): Caused by: android.os.TransactionTooLargeException
E/AndroidRuntime( 3321): 	at android.os.BinderProxy.transact(Native Method)
E/AndroidRuntime( 3321): 	at android.content.pm.IPackageManager$Stub$Proxy.queryContentProviders(IPackageManager.java:2590)
E/AndroidRuntime( 3321): 	at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:616)
E/AndroidRuntime( 3321): 	... 10 more
W/ActivityManager( 1840): Process android.process.acore has crashed too many times: killing!
I/ActivityManager( 1840): Killing 3321:android.process.acore/u0a4 (adj 15): crash
D/ActivityManager( 1840): cleanUpApplicationRecordLocked -- 3321

**Comment by Lost-Entrepreneur439** [comment]
This issue is still present, I'm constantly getting acore has stopped messages whenever using microG on LineageOS 11.

**Comment by ale5000-git** [comment]
Hve all of you tried with microG Services 0.3.6 and microG Companion 0.3.6?

**Comment by Lost-Entrepreneur439** [comment]
> Have all of you tried with microG Services 0.3.6 and microG Companion 0.3.6?

GitHub didn't notify me for this for some reason, anyways, yes, I am running microG Services and Companion 0.3.6 on my LineageOS 11 (android kitkat) device.
