### ISSUE TITLE
Discord push notifications not working

### ISSUE THREAD

**Issue by laser505t** [microg/GmsCore#2080]
**Describe the bug**
Discord (com.discord) push notifications are failing. ADB logcat shows "Fetching FCM registration token failed" and SERVICE_NOT_AVAILABLE. Notifications that one would expect to see never show up.

**To Reproduce**
1. Plug in device for USB debugging
2. Launch Discord (`adb shell ps | grep com.discord`)
3. Get PID of com.discord and filter out logcat for that PID (`adb logcat --pid=<PID>`)
4. Observe error message shown below

**Expected behavior**
This error message and backtrace to not show up and for Discord notifications to show up.

**Logcat**
```
10-29 21:22:17.484  7438  7438 W IOException: Fetching FCM registration token failed
10-29 21:22:17.484  7438  7438 W IOException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.FirebaseMessaging.i(SourceFile:67)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.FirebaseMessaging.w(SourceFile:1)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.FirebaseMessaging.f(Unknown Source:0)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.u.run(Unknown Source:4)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-29 21:22:17.484  7438  7438 W IOException: 	at h9.c.run(SourceFile:7)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.lang.Thread.run(Thread.java:1012)
10-29 21:22:17.484  7438  7438 W IOException: Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.b.f(SourceFile:32)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.b.a(SourceFile:32)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.FirebaseMessaging.i(SourceFile:55)
10-29 21:22:17.484  7438  7438 W IOException: 	... 10 more
10-29 21:22:17.484  7438  7438 W IOException: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.z.f(SourceFile:41)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.z.h(Unknown Source:8)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.z.a(Unknown Source:0)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.y.a(Unknown Source:2)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.e.run(SourceFile:27)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.firebase.messaging.f.execute(Unknown Source:0)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.f.a(Unknown Source:7)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.t.b(SourceFile:36)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.w.r(SourceFile:15)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.e.run(SourceFile:37)
10-29 21:22:17.484  7438  7438 W IOException: 	at x8.d0.execute(Unknown Source:0)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.f.a(Unknown Source:7)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.t.b(SourceFile:36)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.w.r(SourceFile:15)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.google.android.gms.tasks.TaskCompletionSource.c(Unknown Source:2)
10-29 21:22:17.484  7438  7438 W IOException: 	at x8.t.d(SourceFile:59)
10-29 21:22:17.484  7438  7438 W IOException: 	at x8.v.a(SourceFile:11)
10-29 21:22:17.484  7438  7438 W IOException: 	at x8.j.handleMessage(SourceFile:110)
10-29 21:22:17.484  7438  7438 W IOException: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 21:22:17.484  7438  7438 W IOException: 	at android.os.Looper.loopOnce(Looper.java:201)
10-29 21:22:17.484  7438  7438 W IOException: 	at android.os.Looper.loop(Looper.java:288)
10-29 21:22:17.484  7438  7438 W IOException: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
10-29 21:22:17.484  7438  7438 W IOException: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-29 21:22:17.484  7438  7438 W IOException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-29 21:22:17.485  7438  7438 W g       : Fetching FCM registration token failed
10-29 21:22:17.485  7438  7438 W g       : ha.g: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.w.k(SourceFile:20)
10-29 21:22:17.485  7438  7438 W g       : 	at com.discord.notifications.fcm.utils.FCMTokenHelper.getToken$lambda$1(SourceFile:11)
10-29 21:22:17.485  7438  7438 W g       : 	at com.discord.notifications.fcm.utils.FCMTokenHelper.b(Unknown Source:0)
10-29 21:22:17.485  7438  7438 W g       : 	at l2.b.a(Unknown Source:2)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.k.run(SourceFile:22)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Handler.handleCallback(Handler.java:942)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Looper.loopOnce(Looper.java:201)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Looper.loop(Looper.java:288)
10-29 21:22:17.485  7438  7438 W g       : 	at android.app.ActivityThread.main(ActivityThread.java:7924)
10-29 21:22:17.485  7438  7438 W g       : 	at java.lang.reflect.Method.invoke(Native Method)
10-29 21:22:17.485  7438  7438 W g       : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-29 21:22:17.485  7438  7438 W g       : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-29 21:22:17.485  7438  7438 W g       : Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.FirebaseMessaging.i(SourceFile:67)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.FirebaseMessaging.w(SourceFile:1)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.FirebaseMessaging.f(Unknown Source:0)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.u.run(Unknown Source:4)
10-29 21:22:17.485  7438  7438 W g       : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
10-29 21:22:17.485  7438  7438 W g       : 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-29 21:22:17.485  7438  7438 W g       : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-29 21:22:17.485  7438  7438 W g       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-29 21:22:17.485  7438  7438 W g       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-29 21:22:17.485  7438  7438 W g       : 	at h9.c.run(SourceFile:7)
10-29 21:22:17.485  7438  7438 W g       : 	at java.lang.Thread.run(Thread.java:1012)
10-29 21:22:17.485  7438  7438 W g       : Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.b.f(SourceFile:32)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.b.a(SourceFile:32)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.FirebaseMessaging.i(SourceFile:55)
10-29 21:22:17.485  7438  7438 W g       : 	... 10 more
10-29 21:22:17.485  7438  7438 W g       : Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.z.f(SourceFile:41)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.z.h(Unknown Source:8)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.z.a(Unknown Source:0)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.y.a(Unknown Source:2)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.e.run(SourceFile:27)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.firebase.messaging.f.execute(Unknown Source:0)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.f.a(Unknown Source:7)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.t.b(SourceFile:36)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.w.r(SourceFile:15)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.e.run(SourceFile:37)
10-29 21:22:17.485  7438  7438 W g       : 	at x8.d0.execute(Unknown Source:0)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.f.a(Unknown Source:7)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.t.b(SourceFile:36)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.w.r(SourceFile:15)
10-29 21:22:17.485  7438  7438 W g       : 	at com.google.android.gms.tasks.TaskCompletionSource.c(Unknown Source:2)
10-29 21:22:17.485  7438  7438 W g       : 	at x8.t.d(SourceFile:59)
10-29 21:22:17.485  7438  7438 W g       : 	at x8.v.a(SourceFile:11)
10-29 21:22:17.485  7438  7438 W g       : 	at x8.j.handleMessage(SourceFile:110)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Looper.loopOnce(Looper.java:201)
10-29 21:22:17.485  7438  7438 W g       : 	at android.os.Looper.loop(Looper.java:288)
10-29 21:22:17.485  7438  7438 W g       : 	at android.app.ActivityThread.main(ActivityThread.java:7924)
10-29 21:22:17.485  7438  7438 W g       : 	at java.lang.reflect.Method.invoke(Native Method)
10-29 21:22:17.485  7438  7438 W g       : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-29 21:22:17.485  7438  7438 W g       : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-29 21:22:17.488  7438  7464 E FirebaseMessaging: Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE. Won't retry the operation.
```

**System**
Information for the above logcat output:
Android Version: 13 (TQ3A.230901.001)
Custom ROM: LineageOS 20 (20-20231009-microG-h830)
microG Services Version: 0.2.29.233013
Discord Version: 201.13 - Stable

**Additional context**
This same issue has been observed in other configurations:
- LineageOS 20, microG 0.2.27.223616, Discord 201.13 - Stable
- LineageOS 19.1, microG 0.2.27.223616, Discord 200.13 - Stable
- LineageOS 19.1, microG 0.2.29.233013, Discord 200.13 - Stable

Discord notifications used to work, but within the past month or 2 they have ceased to work.

Also have seen probably the same issue with Duolingo ("Failed to get FCM token", SERVICE_NOT_AVAILABLE). May create a separate issue for this.

**Comment by ppebb** [comment]
How did you install microg? I have a rooted lineage 20 installation where I installed microg through [nift4's installer](https://github.com/nift4/microg_installer_revived) and it works for me. Your microg version being 0.2.x is a bit concerning, given mine is 0.3.0.233515.
