### ISSUE TITLE
[com.whatsapp] Crash while loading location message

### ISSUE THREAD

**Issue by Kobaxidze256** [microg/GmsCore#2154]
**Affected app**
Name: WhatsApp
Package id: com.whatsapp

**Describe the bug**
App or something crashes when you open a conversation in which someone sent you a location.

**To Reproduce**
1. Receive location
2. Open conversation

**Expected behavior**
App or whatever doesn't crash.

**System**
Android Version: 13
Custom ROM: LineageOS 20, up to January 4th update installed

**microG**
microG Core version: 0.3.0.233515
microG Self-Check results: All ticked

**Additional context**
```sh
su -c 'logcat -d -b crash' | termux-clipboard-set
```
```
--------- beginning of crash
01-24 04:13:42.441 28206 28206 E AndroidRuntime: FATAL EXCEPTION: main
01-24 04:13:42.441 28206 28206 E AndroidRuntime: Process: com.whatsapp, PID: 28206
01-24 04:13:42.441 28206 28206 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:44)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:100)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.LiteGoogleMapImpl.onCreate(LiteGoogleMap.kt:209)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.MapViewImpl.onCreate(MapView.kt:42)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact(IMapViewDelegate.java:110)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.MapViewImpl.onTransact(MapView.kt:79)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:1164)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.000.A0u(:1)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.6iZ.A03(:6)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.6tp.BrI(:32)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.6ZJ.A01(:147)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.4YR.A06(:27)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at X.3xZ.run(:922)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-24 04:13:42.441 28206 28206 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by nkeor** [comment]
If you are using nift4's magisk module, check https://github.com/nift4/microg_installer_revived/issues/116. That solved the crash for me.
