### ISSUE TITLE
[com.innogy.echarge] eCharge crashing with 0.3.0 while working with 0.2.27

### ISSUE THREAD

**Issue by fwg-cag** [microg/GmsCore#2218]
**Affected app**
Name: eCharge
Package id: com.innogy.echarge (Version 1.16.3)

**Describe the bug**
The app crashes with microg 0.3.0 as soon as the filter settings button is touched to open its dialogue (this worked with 0.2.27 but with this version no map was shown)

**To Reproduce**
1. Open the app
2. Try to open the filter settings dialogue via the round button in the bottom right

**Expected behavior**
The filter settings dialog should open (as it did with microg 0.2.27)

**System**
Android Version: 14
Custom ROM: LineageOS 21.0

**microG**
microG Core version: 0.3.0.233515-106 (9028d03) and other 0.3.0 versions before
microG Self-Check results: All ticked

**Additional context**
Log:

> 03-03 11:03:02.231 27732 27772 D AppMeasurementService: Not yet implemented: logEvent
03-03 11:03:02.234 27732 27772 D AppMeasurementService: Not yet implemented: logEvent
03-03 11:03:02.253 27732 27808 D SERVER  : Handling local request: https://localhost:4200/462.61810de3b2b8e7c7.js
03-03 11:03:02.355 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/svg/innogy_picto_star.svg
03-03 11:03:02.358 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/svg/innogy_picto_star.svg
03-03 11:03:02.361 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/svg/innogy_picto_star.svg
03-03 11:03:02.364 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/svg/innogy_picto_star.svg
03-03 11:03:02.368 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/svg/innogy_picto_star.svg
03-03 11:03:02.377 27732 27933 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
03-03 11:03:02.407 27732 27923 W System.err: java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to java.util.LinkedHashMap
03-03 11:03:02.411 27732 27923 W System.err: 	at plugin.google.maps.CordovaGoogleMaps.removeMap(CordovaGoogleMaps.java:424)
03-03 11:03:02.411 27732 27923 W System.err: 	at plugin.google.maps.CordovaGoogleMaps$2.run(CordovaGoogleMaps.java:265)
03-03 11:03:02.411 27732 27923 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
03-03 11:03:02.411 27732 27923 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
03-03 11:03:02.411 27732 27923 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-03 11:03:02.411 27732 27923 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-03 11:03:02.411 27732 27923 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
03-03 11:03:02.413 27732 27732 D GmsMapAbstract: unimplemented Method: setIndoorEnabled
03-03 11:03:02.416 27732 27732 D GmsMapAbstract: Not yet implemented: setOnPolylineClickListener
03-03 11:03:02.419 27732 27732 D GmsMapAbstract: Not yet implemented: setOnPolygonClickListener
03-03 11:03:02.419 27732 27732 D GmsMap  : onTransact [unknown]: 45, android.os.Parcel@da8ae2a, 0
03-03 11:03:02.422 27732 27732 D GmsMapAbstract: Not yet implemented: setOnGroundOverlayClickListener
03-03 11:03:02.453 27732 27732 D AndroidRuntime: Shutting down VM
03-03 11:03:02.454 27732 27732 E AndroidRuntime: FATAL EXCEPTION: main
03-03 11:03:02.454 27732 27732 E AndroidRuntime: Process: com.innogy.echarge, PID: 27732
03-03 11:03:02.454 27732 27732 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method org.microg.gms.maps.mapbox.AbstractGoogleMap.setOnInfoWindowCloseListener, parameter listener
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.AbstractGoogleMap.setOnInfoWindowCloseListener(Unknown Source:2)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(IGoogleMapDelegate.java:752)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.onTransact(GoogleMap.kt:905)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:1212)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.google.android.gms.maps.internal.zzg.setOnInfoWindowCloseListener(Unknown Source:9)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap.setOnInfoWindowCloseListener(Unknown Source:5)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at plugin.google.maps.PluginMap$5$1.run(PluginMap.java:845)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:7646)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at plugin.google.maps.PluginMap$5.onResult(PluginMap.java:826)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at plugin.google.maps.PluginUtil$MyCallbackContext.sendPluginResult(PluginUtil.java:60)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at org.apache.cordova.CallbackContext.success(CallbackContext.java:113)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at plugin.google.maps.PluginMap$17.run(PluginMap.java:1933)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-03 11:03:02.454 27732 27732 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
03-03 11:03:02.478 27732 27923 I .innogy.echarge: Explicit concurrent copying GC freed 61315(2708KB) AllocSpace objects, 0(0B) LOS objects, 85% free, 4068KB/27MB, paused 733us,110us total 66.609ms
03-03 11:03:02.528 27732 27772 D AppMeasurementService: Not yet implemented: logEvent
03-03 11:03:02.573 27732 27808 D SERVER  : Handling local request: https://localhost:4200/assets/img/favicon.ico
03-03 11:03:03.028 27732 27971 W FirebaseCrashlytics: Timeout exceeded while awaiting app exception callback from Analytics listener.
03-03 11:03:03.090  1362 27973 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-03 11:03:03.101  1362  8485 W ActivityTaskManager:   Force finishing activity com.innogy.echarge/.MainActivity
03-03 11:03:03.108 27732 27732 I Process : Sending signal. PID: 27732 SIG: 9
03-03 11:03:03.129   514   514 I BpBinder: onLastStrongRef automatically unlinking death recipients: 
03-03 11:03:03.254  1362  2252 D ConnectivityService: releasing NetworkRequest [ REQUEST id=8896, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10000 RequestorUid: 10000 RequestorPkg: com.innogy.echarge UnderlyingNetworks: Null] ] (release request)
03-03 11:03:03.254  1362  1496 I ImeTracker: com.innogy.echarge:de981509: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_REMOVE_CLIENT
03-03 11:03:03.254  1362 17835 I WindowManager: WIN DEATH: Window{8477b2 u0 com.innogy.echarge/com.innogy.echarge.MainActivity}
03-03 11:03:03.254  1362  1496 I ImeTracker: com.innogy.echarge:de981509: onCancelled at PHASE_SERVER_SHOULD_HIDE
03-03 11:03:03.254  1362  2607 I ActivityManager: Process com.innogy.echarge (pid 27732) has died: fg  TOP 
03-03 11:03:03.255  1362 17835 W InputManager-JNI: Input channel object '8477b2 com.innogy.echarge/com.innogy.echarge.MainActivity (client)' was disposed without first being removed with the input manager!

**Comment by fwg-cag** [comment]
Thank you so much for the swift fix! I'm looking forward to testing the next nightly ...
