### ISSUE TITLE
microG Services Core keeps stopping on bramble (Pixel 4a 5G)

### ISSUE THREAD

**Issue by PixelNeck** [microg/GmsCore#2241]
**Describe the bug**
microG Services Core keeps stopping message on bramble (Pixel 4a 5G)

**To Reproduce**
1. Install LineageOS unofficial build from here (I used the official guide on Wayback Machine): https://sourceforge.net/projects/aleasto-lineageos/files/LineageOS%2018.1/bramble/
2. and all patches from here: https://xdaforums.com/t/how-to-install-microg-on-unsupported-roms.4540957/
3. Enable all permissions for microG

**Expected behavior**
MicroG settings open and everything works as expected.

**Screenshots**
https://github.com/microg/GmsCore/assets/155148854/33421664-c61e-4952-aa9b-f73600ca27ca (this is a video recording click here)

![Screenshot_20240316-212327_Bromite](https://github.com/microg/GmsCore/assets/155148854/f951e589-ed51-4c70-9e5d-a1f3675a5a28)

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Additional context**
I used MicroG installer revived. App version is 0.3.0.233515.
Error log:
`FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 8174
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:6359)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6599)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by ale5000-git** [comment]
Could you please attach a full logcat?

**Comment by PixelNeck** [comment]
Oh sorry I already reinstalled with opengapps
