### ISSUE TITLE
microG UI crashes after clicking on app location access

### ISSUE THREAD

**Issue by Wojtaz0w** [microg/GmsCore#2260]
**Describe the bug**
MicroG UI crashes after clicking on Location settings > apps that used location > any app

**To Reproduce**
1. Go to Location settings in microG
2. Click on any app
3. See crash

**Expected behavior**
Info about app and location it has accessed is shown. 

**Screenshots**
![Screenshot_20240326-091102_Usługi microG.png](https://github.com/microg/GmsCore/assets/104674625/57c32029-1f0e-4b6b-9365-a55bff301bd1)

**System**
Android Version: 14
Custom ROM: crDroid 10.1

**Additional context**
Only happens after 0.3.1 update

**Comment by Wojtaz0w** [comment]
LOG: FATAL EXCEPTION: 
main
Process: com.google.android.gms:ui, PID: 14526
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__) - is the library loaded, e.g. System.loadLibrary?
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:44)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:100)
	at org.microg.gms.maps.mapbox.LiteGoogleMapImpl.onCreate(LiteGoogleMap.kt:209)
	at org.microg.gms.maps.mapbox.MapViewImpl.onCreate(MapView.kt:42)
	at org.microg.gms.maps.MapViewDelegate.onCreate(MapViewDelegate.java:45)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper$2.apply(DeferredLifecycleHelper.java:54)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.lambda$new$0$com-google-android-gms-dynamic-DeferredLifecycleHelper(DeferredLifecycleHelper.java:26)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper$$ExternalSyntheticLambda0.onDelegateCreated(Unknown Source:2)
	at org.microg.gms.maps.MapViewLifecycleHelper.createDelegate(MapViewLifecycleHelper.java:48)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.startStateOperation(DeferredLifecycleHelper.java:145)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(DeferredLifecycleHelper.java:51)
	at com.google.android.gms.maps.MapView.onCreate(MapView.java:83)
	at org.microg.gms.location.ui.LocationMapPreference.onBindViewHolder(LocationMapPreference.kt:63)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:422)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:49)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27149)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7010)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:27149)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9530)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by Wojtaz0w** [comment]
it seems I was right; reinstalling fixed this bug
