### ISSUE TITLE
microG services crash loop

### ISSUE THREAD

**Issue by Zeromus24** [microg/GmsCore#2267]
**Describe the bug**
The app keeps crashing on boot and doesn't start. Tried a clean install.

**To Reproduce**
1. Root
2. Install MicroG as system via MicroG Installer Revived
3. Reboot
4. Crashloop

**Expected behavior**
Before updating to the latest version, microG worked just fine, and it should work just fine now.

**System**
Android Version: 12.1
Custom ROM: LineageOS 19.1

**Additional context**
Log:
```FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 8767
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
    at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:279)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6661)
    at android.app.ActivityThread.access$1500(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)```

**Comment by mar-v-in** [comment]
This looks like some issue with your installation. Maybe check you have exactly followed the instructions of MicroG Installer Revived and have not tried to install microG independent of it.

**Comment by marcdw1289** [comment]
I have experienced this issue.
Fresh install of Project Sakura ROM (Android 10) On Motorola G5s Plus sanders. Using MinMicroG CI installer via TWRP-based recovery (Pitch Black). No Magisk installed yet.

ROM will not boot and eventually goes to TWRP. After a few failures I dirty flashed the previous MinMicroG zip with microG 0.3.0. ROM booted fine.

Then I tried to update via my F-Droid client but met with signature mismatch.

Also tried my manual method of direct replacement but that also causes ROM not to boot.

**Comment by ale5000-git** [comment]
@marcdw1289
Hi,
the new version have a new priv-app permissions: `<permission name="android.permission.START_ACTIVITIES_FROM_BACKGROUND" />`

It is normal to bootloop if the apk is updated but the xml is not updated.

**Comment by Zeromus24** [comment]
I fixed this by installing the latest .apk found in this repo. Now microG works correctly as a system application.

**Comment by marcdw1289** [comment]
@ale5000-git 
Thanks, that worked. I'll pass that on to the MinMicroG dev as that permission is not included in his latest build.
