### ISSUE TITLE
"microG Companion" (com.android.vending) in crash-loop due to Chomp SMS licence check

### ISSUE THREAD

**Issue by nabijaczleweli** [microg/GmsCore#2333]
**Describe the bug**
When Chomp SMS is open, "microG Companion stopped working" popup shows up sometimes.

**To Reproduce**
1. run Chomp SMS (com.p1.chompsms; I'm using 9.14 from the Play Store)
2. click around through the settings for a bit

**Expected behavior**
Nothing

**System**
Android Version: 14
Custom ROM: LineageOS 21

Using com.google.android.gms-223616054.apk (latest stable)
and com.android.vending-84022602.apk (latest tag)

**Screenshots**
![](https://github.com/microg/GmsCore/assets/6709544/c3614664-64fa-4fe9-be82-5cf0d8703929)

**Additional context**
logcat says:
```
04-21 17:17:23.926  6539  6539 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10182; state: DISABLED
04-21 17:17:23.938  6539  6539 E ActivityThread: Failed to find provider info for com.google.android.gms.microg.profile
04-21 17:17:23.938  6539  6539 E FakeLicenseService: profile provider not available
04-21 17:17:23.939  1431  2464 W ContentProviderHelper: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 D AndroidRuntime: Shutting down VM
04-21 17:17:23.940  6539  6539 E AndroidRuntime: FATAL EXCEPTION: main
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Process: com.android.vending, PID: 6539
04-21 17:17:23.940  6539  6539 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service com.android.vending.licensing.LicensingService@6d945f7 with Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending }: java.lang.SecurityException: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4910)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3166)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3149)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3091)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6006)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7637)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3690)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1213)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1161)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1117)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.vending.licensing.LicensingService.onBind(Unknown Source:83)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4895)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	... 9 more
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:706)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:306)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:148)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6878)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2806)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 
04-21 17:17:23.943  1431  6556 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-21 17:17:23.946  6539  6539 I Process : Sending signal. PID: 6539 SIG: 9
04-21 17:17:23.983  1431  2464 I ActivityManager: Process com.android.vending (pid 6539) has died: fg  BTOP
04-21 17:17:23.983  1431  1904 I libprocessgroup: Successfully killed process cgroup uid 10182 pid 6539 in 0ms
04-21 17:17:23.983   856   856 I Zygote  : Process 6539 exited due to signal 9 (Killed)
```
and
```
04-21 17:17:23.910  6539  6539 D nativeloader: Configuring clns-4 for other apk /data/app/~~auYFtAnUuYPt6zKFdIVh1Q==/com.android.vending-untO5NkZztTnYy4lkiVb4w==/base.apk. target_sdk_version=29, uses_libraries=, library_path=/data/app/~~auYFtAnUuYPt6zKFdIVh1Q==/com.android.vending-untO5NkZztTnYy4lkiVb4w==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.android.vending
04-21 17:17:23.920  6539  6539 V GraphicsEnvironment: Currently set values for:
04-21 17:17:23.920  6539  6539 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
04-21 17:17:23.920  6539  6539 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
04-21 17:17:23.920  6539  6539 V GraphicsEnvironment: Global.Settings values are invalid: number of packages: 0, number of values: 0
04-21 17:17:23.920  6539  6539 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
04-21 17:17:23.926  6539  6539 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10182; state: DISABLED
04-21 17:17:23.938  6539  6539 E ActivityThread: Failed to find provider info for com.google.android.gms.microg.profile
04-21 17:17:23.938  6539  6539 E FakeLicenseService: profile provider not available
04-21 17:17:23.939  1431  2464 W ContentProviderHelper: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 D AndroidRuntime: Shutting down VM
04-21 17:17:23.940  6539  6539 E AndroidRuntime: FATAL EXCEPTION: main
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Process: com.android.vending, PID: 6539
04-21 17:17:23.940  6539  6539 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service com.android.vending.licensing.LicensingService@6d945f7 with Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending }: java.lang.SecurityException: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4910)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider org.microg.gms.settings.SettingsProvider from ProcessRecord{e5f41c8 6539:com.android.vending/u0a182} (pid=6539, uid=10182) that is not exported from UID 10186
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3166)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3149)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3091)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6006)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7637)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3690)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1213)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1161)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1117)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.vending.licensing.LicensingService.onBind(Unknown Source:83)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4895)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	... 9 more
04-21 17:17:23.940  6539  6539 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:706)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:306)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:148)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6878)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2806)
04-21 17:17:23.940  6539  6539 E AndroidRuntime: 
04-21 17:17:23.943  1431  6556 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-21 17:17:23.946  6539  6539 I Process : Sending signal. PID: 6539 SIG: 9
04-21 17:17:23.983  1431  2464 I ActivityManager: Process com.android.vending (pid 6539) has died: fg  BTOP
04-21 17:17:23.983  1431  1904 I libprocessgroup: Successfully killed process cgroup uid 10182 pid 6539 in 0ms
04-21 17:17:23.983   856   856 I Zygote  : Process 6539 exited due to signal 9 (Killed)
04-21 17:17:23.984  1431  2464 W ActivityManager: Scheduling restart of crashed service com.android.vending/.licensing.LicensingService in 1800000ms for connection
04-21 17:17:23.985  1431  1873 D DisplayManagerService: Drop pending events for gone uid 10182
04-21 17:17:29.389  1431  2320 W InputReader: Received unexpected event (0x35, 0xfb) for slot 0 with tracking id 230
04-21 17:17:29.389  1431  2320 W InputReader: Received unexpected event (0x36, 0x8ed) for slot 0 with tracking id 230
04-21 17:17:29.392  2421  2421 I KeyButtonView: Back button event: ACTION_DOWN
04-21 17:17:29.394  1042  1042 E QTI PowerHAL: Failed process_boost for boost_handle
04-21 17:17:29.455  2421  2421 I KeyButtonView: Back button event: ACTION_UP
```

Full: [logcat.gz](https://github.com/microg/GmsCore/files/15052514/logcat.gz)

**Comment by nabijaczleweli** [comment]
The onBind -> query traceback points to https://github.com/microg/GmsCore/blob/827a8b914cb3ef970ad81897672f4539a423fdcc/vending-app/src/main/java/com/android/vending/licensing/LicensingService.java#L183-L196 which blames to 0d410519f8bde8bb1d3bb1fe0b58472b538e8cfd.

**Comment by ale5000-git** [comment]
I'm not sure if it is this problem but the latest microG Companion use "things" and new permissions from microG Services, so it need the following things:
1) Both microG Services and microG Companion need to be updated
2) Both microG Services and microG Companion need to have the same signature
3) You need to update microG Services BEFORE microG Companion, if you have done the opposite then the new permission will be probably not granted.

**Comment by nabijaczleweli** [comment]
I followed https://github.com/microg/GmsCore/wiki/Installation which still calls com.android.vending "FakeStore" (this was fun to figure out, especially since it links to https://github.com/microg/GmsCore/wiki/Downloads which links to https://github.com/microg/FakeStore/releases which is archived; everything on the wiki being called by some internal code-name instead of the package name that it's distributed as is also needlessly confusing) and doesn't mention version-matching it to anything else.

Unclear to me what you mean by "signature" here, the only signature they have that I see are the two `.asc`s which are naturally different for different files.

I hadn't updated anything before, this is a fresh install.
I now updated to com.google.android.gms-240913002.apk (same release as com.android.vending), and it doesn't look like it crashed yet.

**Comment by nabijaczleweli** [comment]
Updating com.google.android.gms to match com.android.vending worked, it hasn't crashed since yesterday.

**Comment by lucasmz-dev** [comment]
@ale5000-git 

> You need to update microG Services BEFORE microG Companion, if you have done the opposite then the new permissions will be probably not granted.

Hey, I see you referencing this issue a few times. Are there any plans to fix this? I could see this being a problem with automatic updates e.g. from F-Droid repo if it decides to update one app before the other

**Comment by ale5000-git** [comment]
@lucasmz-dev
It is an installation issue, not something that can be fixed by an app.
But I think that having an additional check in microG self check can make the problem more evident.
