### ISSUE TITLE
"MicroG Services keep stopping" error

### ISSUE THREAD

**Issue by BacchusVarg** [microg/GmsCore#2386]
**Describe the bug**
"MicroG Services keep stopping" error keeps popping even with location permission granted.

**To Reproduce**
1. Install LineageOS 21
2. Install Magisk 27.0
3. Install LSPosed 1.9.3 module
4. In LSPosed install FakeGapps
5. Install MicroG Installer revived 3.4.4 module
6. Reboot

**Expected behavior**
MicroG working normally on my device

**System**
Android Version: 14
Custom ROM: LineageOS 21
MicroG Services version: 0.3.2.240913

**Additional context**
I saw another bug report from march very similar to mine and in that case it was fixed by giving app the location permission, but in my case it didn't help

Logs:
`FATAL EXCEPTION: main
Process: com.google.android.gms:ui, PID: 6100
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7187)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)`

**Comment by Wojtaz0w** [comment]
Could you try, perhaps, clearing microG app data?

**Comment by mar-v-in** [comment]
Current LineageOS supports Signature Spoofing for microG, so you don't need Magisk/LSPosed/FakeGapps anymore to run and use microG. Can you try if the issue persists without those?

**Comment by BacchusVarg** [comment]
> Current LineageOS natively supports Signature Spoofing for microG, so you don't need Magisk/LSPosed/FakeGapps anymore to run and use microG. Can you try if the issue persists without those?

Unfortunately, no. I've switched back to LOS 20 with microG preinstalled because of SafetyNet problems with LOS 21 build that I was using

**Comment by ewired** [comment]
I am on Android 14, LOS 21-20240216-UNOFFICIAL-emerald. This bug is also happening for me after updating microG Installer Revived and Play Integrity Fix to the latest version, to try to fix Uber "we're having trouble with your device" and kicking me to the web version. microG Services app version is 0.3.2.240913. I am using a similar setup with LSPosed FakeGApps. I tried turning off FakeGApps, causing it to fail the signature spoofing check, so I assume my build of LOS provided by Teracube was not built with microG signature spoofing. microG Services is in a crash loop with the same log output provided earlier, but only when I have Play Integrity Fix enabled in Magisk. The same crash also happens in the settings UI activity when opening it. When I disable Play Integrity Fix, microG Services and settings works fine again, but of course it then fails SafetyNet and Play Integrity.

**Comment by timur-g** [comment]
Same issue. When I have Play Integrity Fix, MicroG installed keeps stopping. Noticed from 3.4 upgrade, also in 3.4.4 Installer
Same solutions. Noticed that Self-help options were not the same with original Magisk installed MicroG Installer Revived and after additional installing MicroG Services Gms apk (which should not be needed).
