### ISSUE TITLE
[com.aimoone.app] play-services-maps: Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by Venefilyn** [microg/GmsCore#2427]
**Affected app**
Name: [e.g. Aimo Park]
Package id: [e.g. com.aimoone.app]

**Describe the bug**
As soon as the app is booted it loads the map, which causes it to instantly crash. Seems related to React Native

**This also applies to** se.parkster.client.android Parkster when the map loads. (Also can't get EasyPark to work but that seems unrelated)

**To Reproduce**
1. Open and allow map GPS
2. Click on 'skip for now'
3. Crash, see traceback at the bottom

**Expected behavior**
Map displays properly. Can confirm that other services like OrganicMaps works

**System**
Android Version: 14
Custom ROM: crDroid v10.2

**microG**
microG Core version: 0.3.2.240913
microG Self-Check results: All checked 

**Additional context**

<details>
<summary>Traceback</summary>

```
time: 1719871385520
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader android.content.Context.getClassLoader()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader android.content.Context.getClassLoader()' on a null object reference
at com.google.android.gms.maps.internal.zzca.zza(com.google.android.gms:play-services-maps@@18.0.0:5)
at com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.0.0:4)
at com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.0.0:1)
at com.google.android.gms.maps.zzah.zzb(com.google.android.gms:play-services-maps@@18.0.0:2)
at com.google.android.gms.maps.zzah.createDelegate(com.google.android.gms:play-services-maps@@18.0.0:1)
at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.1.0:6)
at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.1.0:1)
at com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.0.0:4)
at com.rnmaps.maps.MapView.<init>(MapView.java:174)
at com.rnmaps.maps.MapManager.createViewInstance(MapManager.java:71)
at com.rnmaps.maps.MapManager.createViewInstance(MapManager.java:28)
at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:183)
at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
at android.view.Choreographer.doFrame(Choreographer.java:934)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8498)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```
</details>

**Comment by Venefilyn** [comment]
Reinstalling microG solved the issue for me
