### ISSUE TITLE
Minor chromecast ConcurrentModificationException

### ISSUE THREAD

**Issue by valerierx** [microg/GmsCore#2449]
**Describe the bug**
This bug may be related to MicroG not picking up any Chromecast devices

**To Reproduce**
1. Connect to a WiFi network with a Chromecast enabled device
2. This error gets picked up in logcat

**Expected behavior**

**System**
Android Version: 14
Custom ROM: LineageOS for MicroG

**Additional context**
```
FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 4352
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1574)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1602)
	at org.microg.gms.cast.CastMediaRouteProvider.publishRoutes(CastMediaRouteProvider.java:329)
	at org.microg.gms.cast.CastMediaRouteProvider.access$500(CastMediaRouteProvider.java:54)
	at org.microg.gms.cast.CastMediaRouteProvider$2.run(CastMediaRouteProvider.java:322)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by harpality** [comment]
Experiencing the same on Android 15, usually upon opening the Google Home app.

**Comment by shiv81** [comment]
Have the same issue. It is highly reproducible when opening the Google Home app. On a Pixel 9 Pro Android 15. A reinstall does not resolve it.
