### ISSUE TITLE
Crash when using location services with bluetooth turned on

### ISSUE THREAD

**Issue by titulebolide** [microg/GmsCore#2466]
**Describe the bug**
When using location services, for example when clicking on the location button on google maps, I received after a while a notification saying "MicroG keeps crashing"

**To Reproduce**
1. Go to Google Maps with Bluetooth enabled 
2. Click on the bottom left corner icon to request location
3. Wait for a bit
4. See the crash notification

**Expected behavior**
MicroG should not be crashing upon location request.

**Screenshots**

**System**
Android Version: 11
Custom ROM: /e/OS 2.2 R
Device: Samsung Galaxy S8 exynos
MicroG version: 0.3.2.240913-22 (43f9740)

**Additional context**
With foxlog I retrieved the crash log.
```
FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 2934
java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10089 nor current process has android.permission.BLUETOOTH.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.bluetooth.IBluetooth$Stub$Proxy.getState(IBluetooth.java:1811)
	at android.bluetooth.BluetoothAdapter$2.recompute(BluetoothAdapter.java:986)
	at android.bluetooth.BluetoothAdapter$2.recompute(BluetoothAdapter.java:982)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:438)
	at android.bluetooth.BluetoothAdapter.getStateInternal(BluetoothAdapter.java:1013)
	at android.bluetooth.BluetoothAdapter.getState(BluetoothAdapter.java:1040)
	at android.bluetooth.BluetoothAdapter.isEnabled(BluetoothAdapter.java:870)
	at org.microg.gms.location.settings.DetailedLocationSettingsStatesKt.getDetailedLocationSettingsStates(Unknown Source:169)
	at org.microg.gms.location.manager.LocationManagerInstance$requestLocationSettingsDialog$1.invokeSuspend(Unknown Source:20)
	at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)
	at z5.i.b(SourceFile:1)
	at a6.a.c(SourceFile:1)
	at a6.a.d(SourceFile:1)
	at u5.i.c(SourceFile:1)
	at u5.g.e(SourceFile:1)
	at androidx.lifecycle.i0$a.invokeSuspend(Unknown Source:72)
	at androidx.lifecycle.i0$a.invoke(SourceFile:2)
	at androidx.lifecycle.i0$a.invoke(SourceFile:1)
	at a6.b.b(SourceFile:1)
	at u5.i.c(SourceFile:1)
	at u5.g.e(SourceFile:1)
	at androidx.lifecycle.i0.d(SourceFile:1)
	at androidx.lifecycle.i0.c(SourceFile:1)
	at androidx.lifecycle.q$c.invokeSuspend(Unknown Source:36)
	at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)
	at u5.t0.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: z5.g: [e2{Cancelling}@dd06e24, Dispatchers.Main.immediate]
```

As it is complaining not having Bluetooth access, I tried granting it with `pm grant`, but it is saying the app did not requested this permission, hence I can't grant it.

Maybe it is only a matter of a missing permission in location's manifest?

An issue has also be filled on /e/OS gitlab : https://gitlab.e.foundation/e/backlog/-/issues/7998 but filling it here seems more appropriate. It seems strangely it affects only exynos devices on /e/OS

Thanks

**Comment by titulebolide** [comment]
I got no more crash if I install MicroG as provided in this repo, replacing the one embedded in /e/OS release. To do so I need to have enabled the microg installed on magisk (as microg needs to be installed as a system app): https://github.com/nift4/microg_installer_revived

Now I'm running microg version 0.3.2.240913 and Bluetooth permission is actually requested by the app and granted to it. Thus it is somehow related to /e/ repack of microg, as both the upstream MicroG and /e/ packaging have the same version.

Closing and pursuing the discussion on /e/ gitlab.
