### ISSUE TITLE
[com.techmash.playo] Playo app crashes while trying to open a venue for booking

### ISSUE THREAD

**Issue by transistxr** [microg/GmsCore#2526]
**Affected app**
Name: Playo
Package id: com.techmash.playo

**Describe the bug**
The Playo app crashes instantly after opening the booking menu and selecting a venue.

**To Reproduce**

(Prerequisite: You need either a phone number to login with an SMS OTP or an e-mail with an e-mail based OTP)
1. Open Playo app
2. Select Book from the Bottom Navigation Bar or the Book tile on the front page.
4. Choose any venue from the list of venues shown in your area.
5. App loads the venue page for roughly a second before crashing.

**Expected behavior**
App shouldn't crash after loading the venue page and should let you book the venue. **I also tried it on a phone with the traditional GApps and it worked as expected.**

**Screenshots**
Attaching a screen-recording of the process (some personal details blurred):

https://github.com/user-attachments/assets/e155c26a-52fe-47a9-a77c-9d63343774a0

**System**
Android Version:14
Custom ROM: CalyxOS 5.10.1

**microG**
microG Core version: 0.3.2.240913-19 (eeb1121)
microG Self-Check results: All ticked

**Additional context**
I ran a `adb logcat | grep gms` and this output could pinpoint what the problem might be:

```
09-04 17:03:12.997  4359 11112 D GmsGcmMcsSvc: Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.HEARTBEAT flg=0x4 cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }
09-04 17:03:14.467 28130 28130 W ContextImpl: Failed to ensure /data/user/10/com.google.android.gms/shared_prefs: mkdir failed: ENOENT (No such file or directory)
09-04 17:03:14.490 12998 12998 D GassService: onBind: Intent { act=com.google.android.gms.gass.START pkg=com.google.android.gms }
09-04 17:03:14.498 12998 13353 D ChimeraServiceProvider: serviceIntentCall: com.google.android.gms.appset.service.START -> Intent { act=com.google.android.gms.appset.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.appset.AppSetService }
09-04 17:03:14.502 12998 12998 D AppSetService: onBind: Intent { act=com.google.android.gms.appset.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.appset.AppSetService }
09-04 17:03:14.517 12998 12998 D AdRequestService: onBind: Intent { act=com.google.android.gms.ads.service.START pkg=com.google.android.gms }
09-04 17:03:14.518 12998 13353 D GassService: bound by: GetServiceRequest{serviceId=GASS, gmsVersion=12451000, packageName='com.techmash.playo', extras=Bundle[{}]}
09-04 17:03:14.525 12998 13017 D AppSetService: bound by: GetServiceRequest{serviceId=APP_SET, gmsVersion=12451000, packageName='com.techmash.playo', extras=Bundle[{}]}
09-04 17:03:14.528 12998 13017 D AdRequestService: bound by: GetServiceRequest{serviceId=ADREQUEST, gmsVersion=12451000, packageName='com.techmash.playo', extras=Bundle[{}]}
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 1 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 2 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 3 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 4 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 5 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 6 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 9 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 12 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:14.530 12998 13017 D SafeParcel: Unknown field id 13 in com.google.android.gms.ads.internal.NonagonRequestParcel, skipping.
09-04 17:03:15.522 12998 13017 D GassService: bound by: GetServiceRequest{serviceId=GASS, gmsVersion=12451000, packageName='com.techmash.playo', extras=Bundle[{}]}
09-04 17:03:17.936 12998 13353 D ChimeraServiceProvider: query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.measurement.dynamite?requestStartTime=350761394
09-04 17:03:17.956 28539 28558 D GmsDynamiteLoaderImpl: createModuleContext for com.google.android.gms.measurement.dynamite at version 98
09-04 17:03:17.964 28539 28574 W ContextImpl: Failed to ensure /data/user/10/com.google.android.gms/shared_prefs: mkdir failed: ENOENT (No such file or directory)
09-04 17:03:17.966 28539 28574 D GmsDynamiteLoaderImpl: createModuleContext for com.google.android.gms.ads.dynamite at version 230500001
09-04 17:03:17.973  4359  4359 D GmsGcmRegister: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
09-04 17:03:17.986 12998 13353 E FontsProvider: query: content://com.google.android.gms.fonts [_id, file_id, font_ttc_index, font_variation_settings, font_weight, font_italic, result_code] query = ? [Noto Color Emoji Compat]
09-04 17:03:17.989 12998 13353 D FontsProvider: openFile: content://com.google.android.gms.fonts/file/1337 mode: r
09-04 17:03:17.992 12998 12998 D GmsAnalyticsSvc: onBind: Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }
09-04 17:03:17.995 12998 13353 D FontsProvider: openFile: content://com.google.android.gms.fonts/file/1337 mode: r
09-04 17:03:18.047  4359  4359 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterServiceKt.ensureCheckinIsUpToDate(PushRegisterService.kt:32)
09-04 17:03:18.047  4359  4359 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterServiceKt.access$ensureCheckinIsUpToDate(PushRegisterService.kt:1)
09-04 17:03:18.047  4359  4359 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterHandler$handleMessage$1.invokeSuspend(PushRegisterService.kt:311)
```

It says  `/data/user/10/` because I am running it in a work profile. However, I do not think it is a profiles issue since I did the same thing on my personal profile and the exact same issue occurred.

**Comment by transistxr** [comment]
This seems to have been resolved by the app developer (since I can't reproduce the issue anymore) so closing this.
