### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager

### ISSUE THREAD

**Issue by bphd** [microg/GmsCore#2527]
time: 1725548826858
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication package com.google.android.gms: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1475)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7021)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.getAssets(LoadedApk.java:1362)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1452)
	... 11 more

**Affected app**
Name: [e.g. WhatsApp]
Package id: [e.g. com.whatsapp]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. LineageOS 17.1]

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: [e.g. All ticked]

**Additional context**

**Comment by ale5000-git** [comment]
@bphd 
Please complete all the details, they arenìt optional.

**Comment by bphd** [comment]
> @bphd Please complete all the details, they aren't optional.

It's gms who crashes on Android latest, latest MicroG and no results available because crash

**Comment by ale5000-git** [comment]
You stil have to say what app you have used, the version of Android (latest is relative) and the name of the ROM.

**Comment by ale5000-git** [comment]
Looking at your other tickets in other repos you are just a spammer.

**Comment by bphd** [comment]
> You stil have to say what app you have used, the version of microG (latest is relative), the version of Android (latest is relative) and the name of the ROM.

MicroG, Matrixx

**Comment by bphd** [comment]
> Looking at your other tickets in other repos you are just a spammer.

No, I'm posting to relevant places

**Comment by ale5000-git** [comment]
In the other repo where there is `Version` you wrote `version`, it is NOT what a valid user would write,

**Comment by bphd** [comment]
> For example, in the other repo where there is `Version` you wrote `version`, it is NOT what a valid user would write,

It's relevant places like I said, but quality of writing is another topic

**Comment by bphd** [comment]
There could be many reasons to crashing, globally not all applications installed, I haven't bothered to return here explaining when I remediate the situation unfortunately, but speaking further by deactivating `persist.sys.pixelprops.gapps` `persist.sys.pixelprops.gms` properties and resintalling vending/gsf/gms and spoofing build and provider (and btw using PIF module, or Osm0sis one when that one bother me) I achieve device integrity. I have difficulties achieving strong integrity but it's probably because my CROM throw `UnsupportedOperationException()` when DroidGuard ask for certificate chain, have to figure out how to patch from MagiSK, or LSP, or by replacing files
