### ISSUE TITLE
[Any app containing ads] Crash due to ads and AdWorker

### ISSUE THREAD

**Issue by MugoSquero** [microg/GmsCore#2666]
**Affected apps**
Name: AIDA64
Package id: com.finalwire.aida64
------
Name: CPU-Z
Package id: com.cpuid.cpu_z

**Describe the bug**
Any app (I only tested aforementioned ones) trying to show ads crash.

**To Reproduce**
Just install one of the apps I provided and try for yourself.

**Expected behavior**
I don't know what to expect really. Do microg block ads or just contacts the Google for ads? The only expected behavior is that apps-with-ads to not crash regardless.

**System**
Android Version: 14
Custom ROM: Samsung A35 5g/Magisk root/signature spoofing

**microG**
microG Core version: 0.3.4.240913 (240913008)
microG Self-Check results: All ticked

**Logcat output**
------
**AIDA64**:
```
FATAL EXCEPTION: AdWorker(Default) #3
Process: com.finalwire.aida64, PID: 20121
java.lang.SecurityException: Writable dex file '/data/user/0/com.finalwire.aida64/cache/1664557424545.jar' is not allowed.
	at dalvik.system.DexFile.openDexFileNative(Native Method)
	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
	at dalvik.system.DexFile.<init>(DexFile.java:128)
	at dalvik.system.DexFile.<init>(DexFile.java:101)
	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:55)
	at com.google.android.gms.internal.ads.zzaqj.zzg(com.google.android.gms:play-services-ads@@21.5.0:29)
	at com.google.android.gms.internal.ads.zzaph.zzj(com.google.android.gms:play-services-ads@@21.5.0:1)
	at com.google.android.gms.internal.ads.zzaph.zzq(com.google.android.gms:play-services-ads@@21.5.0:2)
	at com.google.android.gms.internal.ads.zzapi.zzt(com.google.android.gms:play-services-ads@@21.5.0:1)
	at com.google.android.gms.ads.internal.zzi.zzo(com.google.android.gms:play-services-ads@@21.5.0:3)
	at com.google.android.gms.ads.internal.zzi.run(com.google.android.gms:play-services-ads@@21.5.0:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```
------
**CPU-Z**
```
FATAL EXCEPTION: AdWorker(Default) #2
Process: com.cpuid.cpu_z, PID: 4499
java.lang.SecurityException: Writable dex file '/data/user/0/com.cpuid.cpu_z/cache/1658186039475.jar' is not allowed.
	at dalvik.system.DexFile.openDexFileNative(Native Method)
	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
	at dalvik.system.DexFile.<init>(DexFile.java:128)
	at dalvik.system.DexFile.<init>(DexFile.java:101)
	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:55)
	at com.google.android.gms.internal.ads.zzaqe.zzg(com.google.android.gms:play-services-ads@@21.3.0:29)
	at com.google.android.gms.internal.ads.zzapc.zzj(com.google.android.gms:play-services-ads@@21.3.0:1)
	at com.google.android.gms.internal.ads.zzapc.zzq(com.google.android.gms:play-services-ads@@21.3.0:2)
	at com.google.android.gms.internal.ads.zzapd.zzt(com.google.android.gms:play-services-ads@@21.3.0:1)
	at com.google.android.gms.ads.internal.zzi.zzo(com.google.android.gms:play-services-ads@@21.3.0:3)
	at com.google.android.gms.ads.internal.zzi.run(com.google.android.gms:play-services-ads@@21.3.0:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by MugoSquero** [comment]
Now, for some unknown reason, after a reboot, the AIDA64 app starts without problems, but the MicroG Companion app (vending) crashes.

Here is the exception log:
```
FATAL EXCEPTION: main
Process: com.android.vending, PID: 20679
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:288)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7566)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

------

CPU-Z is worse. Both the app and vending crash (similar/same exception output).

MicroG Companion app version: 0.3.4.40226 (84022608)

I installed MicroG with MinMicroG minimal package. All installed as system apps. Any other app workes without problems (e.g., RVX). Passing the integrity check (done the test through the MicroG app).

Can someone please test one of the apps on their phones and see if they are working as intended?
