### ISSUE TITLE
Crash while fetching network location from WIFIonICE moving wifi network

### ISSUE THREAD

**Issue by TimoWilken** [microg/GmsCore#2704]
**Describe the bug**

When on an ICE train in Germany and connected to the "WIFIonICE" network, I never get a network location from microG that is identical to the train's GPS location (as reported by the [API](https://iceportal.de/api1/rs/status)).

**To Reproduce**

1. Get on an ICE train (or stand next to on in a station?), connect to its WIFIonICE network and log into the network
2. Start a logcat app, e.g. "Logcat Reader", and start recording messages
3. Open any app that requests a location (e.g. a maps app)
5. See error in logcat: "Failed retrieving location for current moving wifi WIFIonICE: java.net.SocketException: Binding socket to network 101 failed: EPERM (Operation not permitted)" (see traceback below)

**Expected behavior**

I expect the maps app to show my location identical with the train's location almost immediately, with an appropriate accuracy (judging by microG code, that would be 100m).

**Screenshots**

N/A

**System**

Android Version: 14 (AP2A.240905.003)
Custom ROM: LineageOS 21-20241211-microG-FP4 (from [lineage.microg.org](https://download.lineage.microg.org/FP4/))

**Additional context**

```
Failed retrieving location for current moving wifi WIFIonICE
java.net.SocketException: Binding socket to network 101 failed: EPERM (Operation not permitted)
	at android.net.Network.bindSocket(Network.java:442)
	at android.net.Network.bindSocket(Network.java:409)
	at android.net.Network$NetworkBoundSocketFactory.createSocket(Network.java:269)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:114)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at org.microg.gms.location.network.wifi.MovingWifiHelper$retrieveMovingLocation$2.invokeSuspend(MovingWifiHelper.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: android.system.ErrnoException: Binding socket to network 101 failed: EPERM (Operation not permitted)
	at android.net.Network.bindSocket(Network.java:441)
	... 22 more
```

**Comment by mar-v-in** [comment]
microG tries to directly bind to the network interface of the wifi. This is so that if you are connected to a wifi hotspot and also mobile network, and Android decides to route regular traffic through the mobile network for any reason (e.g. because you did not sign in on the wifi hotspot's captive portal yet), microG would still route the request to the wifi so it can provide a response.

If you set up a VPN and force all connections to be routed through the VPN software (even if the VPN software decides to route the traffic not through the VPN but to the network directly), this binding to network interface fails.

As a work-around, we can try to detect this situation and then not bind to a specific interface.

**Comment by TimoWilken** [comment]
Indeed, the VPN seems to cause the issue - it works perfectly if I disable the WireGuard VPN.

It would still be nice if it worked even with the VPN enabled (since in my case, it still lets apps connect to the ICE portal etc, it only routes `10.0.0.*` private IPs through the VPN tunnel. Maybe MicroG could fall back to trying to fetch the location info even if binding to the interface fails?

**Comment by ligix** [comment]
I found this issue while trying to understand why my code threw that exception and I just wanted to add -- for any random people stumbling into this issue like me -- that it seems to always fail when binding to a mobile network, vpn or not.
