### ISSUE TITLE
DriveNow Apprcrash with MicroG Services Core 0.2.4-108

### ISSUE THREAD

**Issue by Flunkyball** [microg/GmsCore#489]
Hi,

I am using lineagos with microg on my Galaxy S7.
LineageOS Version is 14.1-2018021-herolte.
MicroG Services Core is 0.2.4-108.
DriveNow Version 4.8.1

DriveNow opens up just fine, geolocation works and cars are displayed. As soon as I select a car from the map the app crashes. 

Is this a known issue ? I found several older postings regarding that problem. However this articel suggests that it worked not so long ago: [](https://www.androidpit.de/android-ohne-google-wird-jetzt-erheblich-bequemer)

Cheers !

**Comment by eggercomputerchaos** [comment]
Same to me, using lineage with microg on Samsung S5 klte. May be it is a problem with SafetyNet?

**Comment by conrad-heimbold** [comment]
I can't see the link. Could you post it again? Could you post a logcat? Thanks!

**Comment by Flunkyball** [comment]
Sorry for the late response: 

Logcat reveals a null reference:
```

FATAL EXCEPTION: main
Process: com.dn.drivenow, PID: 1474
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
	at com.google.android.gms.dynamic.zzn.zzx(Unknown Source)
	at com.google.android.gms.maps.model.Marker.getTag(Unknown Source)
	at com.dn.drivenow.plugin.map.b.k.g(SourceFile:132)
	at com.dn.drivenow.plugin.map.c.g.a(SourceFile:530)
	at com.dn.drivenow.plugin.map.c.a$1.run(SourceFile:83)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by aktivkohle** [comment]
Can see someone [posted a similar issue here](https://github.com/microg/android_packages_apps_GmsCore/issues/388) about a year ago.

I have MicroG Services Core Version 0.2.4-111-gf1cdb48 on a phone with Android 4.1.2, Cyanogenmod 10. A few years ago car sharing apps used to work on it, well late 2016. Interestingly, the Emmy scooter app works on this phone, but DriveNow crashes within seconds. It did once work for 5 minutes or so, the maps, the car listings, but it is unstable. At any rate, the loading of map data is slow in the time till it crashes, maybe that causes something to time out? Here is some of my relevant logcat:
```

D/RPC     (  401): 3100008c:327681 sending RPC reply (XID 904)
D/RPC     (  401): 3000008c:00050000 received CALL.
D/RPC     (  401): 3000008c:00050000 dispatching RPC call (XID 905, xdr 0x321c98) for callback client 3100008c:00050001.
D/RPC     (  401): 3100008c:327681 sending RPC reply (XID 905)
E/AndroidRuntime( 1918): FATAL EXCEPTION: main
E/AndroidRuntime( 1918): java.lang.NullPointerException
E/AndroidRuntime( 1918): 	at com.google.android.gms.dynamic.zzn.zzy(Unknown Source)
E/AndroidRuntime( 1918): 	at com.google.android.gms.maps.model.Marker.getTag(Unknown Source)
E/AndroidRuntime( 1918): 	at com.dn.drivenow.plugin.map.b.k.g(SourceFile:132)
E/AndroidRuntime( 1918): 	at com.dn.drivenow.plugin.map.c.g.a(SourceFile:530)
E/AndroidRuntime( 1918): 	at com.dn.drivenow.plugin.map.c.a$1.run(SourceFile:83)
E/AndroidRuntime( 1918): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 1918): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1918): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1918): 	at android.app.ActivityThread.main(ActivityThread.java:4931)
E/AndroidRuntime( 1918): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1918): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1918): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 1918): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
E/AndroidRuntime( 1918): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  401):   Force finishing activity com.dn.drivenow/.MainActivity
W/ActivityManager(  401): Activity pause timeout for ActivityRecord{2bdc1880 com.dn.drivenow/.MainActivity}
D/RPC     (  401): 3000008c:00050000 received CALL.
D/RPC     (  401): 3000008c:00050000 dispatching RPC call (XID 907, xdr 0x321c98) for callback client 3100008c:00050001.
D/RPC     (  401): 3100008c:327681 sending RPC reply (XID 907)
D/RPC     (  401): 3000008c:00050000 received CALL.
D/RPC     (  401): 3000008c:00050000 sending call (XID 73).
D/RPC     (  401): 3000008c:00050000 dispatching RPC call (XID 908, xdr 0x321c98) for callback client 3100008c:00050001.
```

Is that helpful at all?

There is also this:
```
D/libloc  (  401): loc_eng_deferred_action_thread signalled
D/libloc  (  401): loc_eng_deferred_action_thread event 1
D/libloc  (  401): loc_eng_process_loc_event: 1
D/libloc  (  401): loc_eng_deferred_action_thread. waiting for events
D/RPC     (  401): 3100008c:327681 sending RPC reply (XID 991)
I/WindowState(  401): WIN DEATH: Window{2bff8ce0 com.dn.drivenow/com.dn.drivenow.MainActivity paused=false}
W/WindowManager(  401): Force-removing child win Window{2be31850 SurfaceView paused=false} from container Window{2bff8ce0 com.dn.drivenow/com.dn.drivenow.MainActivity paused=false}
I/ActivityManager(  401): Process com.dn.drivenow (pid 1918) has died.
W/ActivityManager(  401): Scheduling restart of crashed service com.dn.drivenow/com.salesforce.marketingcloud.MCService in 5000ms
W/WindowManager(  401): Failed looking up window
W/WindowManager(  401): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@2be316a0 does not exist
W/WindowManager(  401): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7675)
W/WindowManager(  401): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7666)
W/WindowManager(  401): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:854)
W/WindowManager(  401): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
W/WindowManager(  401): 	at dalvik.system.NativeStart.run(Native Method)
I/WindowState(  401): WIN DEATH: null
I/ContactDirectoryManager( 1848): deleted 0 stale rows which don't have any relevant directory
I/ContactDirectoryManager( 1848): Discovered 0 contact directories in 370ms
```
Would certainly be nice to have if it could be debugged somehow. Am thinking of trying to flash LineageOS and see how that goes, but most other things on this phone such as OsmAnd are stable, and the spoofing and UnifiedNLP are set up properly too. Then @eggercomputerchaos had no luck with LineageOS for this so will leave as it is and maybe there will be a fix one day.

**Comment by nExXxuS** [comment]
It is fixed on current version.
