### ISSUE TITLE
Phenotype.API is not available on this device

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#597]
```
[ 08-28 20:39:53.179  3602: 3719 E/PhenotypeFlagCommitter ]
Retrieving snapshot for com.google.android.gm failed
java.util.concurrent.ExecutionException: hpl: 17: API: Phenotype.API is not available on this device.
	at jbz.a(Unknown Source)
	at jbz.a(Unknown Source)
	at iyh.a(Unknown Source)
	at cwp.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: hpl: 17: API: Phenotype.API is not available on this device.
	at hvj.a(Unknown Source)
	at htb.a(Unknown Source)
	at hsz.a(Unknown Source)
	at hrm.a(Unknown Source)
	at hrm.a(Unknown Source)
	at hwd.a(Unknown Source)
	at hwj.a(Unknown Source)
	at hwb.a(Unknown Source)
	at hwe.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

[ 08-28 20:39:53.209  3272: 3292 D/GmsClearcutLogSvcImpl ]
log: LogEventParcelable[1, PlayLoggerContext[1, package=com.google.android.gm, packageVersionCode=60575153, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=true, logSourceName=GMAIL_ANDROID_PRIMES, isAnonymous=false, qosTier=0], LogEventBytes: [letters_and_numbers], AddPhenotypeExperimentTokens: true]
```

**Comment by patrickdrd** [comment]
same

```
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): Retrieving snapshot for com.google.android.dialer failed
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): java.util.concurrent.ExecutionException: hiw: 17: API: Phenotype.API is not available on this device. Connection failed with: hho{statusCode=CANCELED, resolution=null, message=null}
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at iej.a(PG:12)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at iej.a(PG:22)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hzt.a(PG:2)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hzt.a(PG:6)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at czu.call(PG:2)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at mzf.b(PG)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at myg.run(PG:7)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at mzg.run(PG:1)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at lnq.run(PG:3)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at java.lang.Thread.run(Thread.java:761)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): Caused by: hiw: 17: API: Phenotype.API is not available on this device. Connection failed with: hho{statusCode=CANCELED, resolution=null, message=null}
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at jte.a(PG:6)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hjt.a(PG:2)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hlw.a(PG:47)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hlw.a(PG:24)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hlw.a(PG:49)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hop.a(PG)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hny.a(PG:1)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hnq.c(PG:2)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hnt.handleMessage(PG:29)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at hvk.dispatchMessage(PG:1)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at android.os.Looper.loop(Looper.java:154)
11-06 12:21:56.610 E/PhenotypeFlagCommitter(29713): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-06 12:21:56.655 W/ActivityManager(1677): Unable to start service Intent { act=com.google.android.gms.telephonyspam.service.START pkg=com.google.android.gms } U=0: not found
11-06 12:21:56.655 W/ActivityManager(1677): Unbind failed: could not find connection for android.os.BinderProxy@4621a46
11-06 12:21:56.656 E/GmsClient(29713): unable to connect to service: com.google.android.gms.telephonyspam.service.START on com.google.android.gms
11-06 12:21:56.889 E/DialerSpamDatabaseUtils(29713): com.android.dialer.spam.inapp.SpamDatabaseUtils.getGlobalSpamListStatus:218 empty cursor returned
11-06 12:21:56.892 E/DialerSpamDatabaseUtils(29713): com.android.dialer.spam.inapp.SpamDatabaseUtils.getUserSpamListStatus:257 empty cursor returned

```

**Comment by Fxavier85** [comment]
Same too
`Unable to update local snapshot for com.google.android.gms.maps#com.google.android.gms, may result in stale flags.
                                                                                                    java.util.concurrent.ExecutionException: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                                    	at m.gua.s(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:21)
                                                                                                    	at m.gua.get(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
                                                                                                    	at m.gwy.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:2)
                                                                                                    	at m.gvt.h(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:10)
                                                                                                    	at m.fgk.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.fgr.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}`
