### ISSUE TITLE
xDrip+ sync not working

### ISSUE THREAD

**Issue by malloy139** [microg/GmsCore#610]
Hello,

I wanted to use the sync featute of xDrip+ (https://github.com/NightscoutFoundation/xDrip), which synchronises blood sugar levels to multiple devices via GCM. If I flash the Play Services to my phone everything works, if I flash the LineageOS version provided by the microg team sync does not work and I got a message "GCM token is null". In the logcat I see errors like:

GmsGcmRegisterSvc:

java.io.IOException: Bad Request
	at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:84)
	at org.microg.gms.gcm.RegisterRequest.getResponse(RegisterRequest.java:101)
	at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:232)
	at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:85)
	at org.microg.gms.gcm.PushRegisterService.registerAndReply(PushRegisterService.java:189)
	at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:167)
	at org.microg.gms.gcm.PushRegisterService.onHandleIntent(PushRegisterService.java:127)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

GmsGcmRegisterSvc:
register[res]: Intent { act=com.google.android.c2dm.intent.REGISTRATION (has extras) } extras=Bundle[{error=|ID|5|SERVICE_NOT_AVAILABLE}]

FirebaseInstanceId:
background sync failed: SERVICE_NOT_AVAILABLE, retry in 20s

This is a fresh install and the only app installes is xDrip. In the microg settings device registration and cloud messaging was enabled. I use a Xiaomi Redmi note 5 with the microg version of LineageOS 15.1.
Has this something to do with some other issues posted here related to firebase?

Thanks

**Comment by malloy139** [comment]
Since v0.2.11.202414 this is working.
