### ISSUE TITLE
chrome gcm notifications received, but not showed

### ISSUE THREAD

**Issue by patrickdrd** [microg/GmsCore#668]
it seems that chrome notifications are received, but not showed:

`11-25 13:02:00.302 D/GmsGcmMcsInput(2732): Incoming message: DataMessageStanza{id=4CBDA87A, from=34167562045, category=com.android.chrome, app_data=[AppData{key=alert, value=ΓΚΟΛ! - Φουενλαμπράδα 29 λεπ
11-25 13:02:00.312 D/GmsGcmMcsSvc(2732): Target: ResolveInfo{3449dc4 com.android.chrome/com.google.android.gms.gcm.GcmReceiver m=0x108000}
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): Received an invalid GCM Message
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): java.lang.IllegalArgumentException: Received push message with no subtype
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at bHz.<init>(SourceFile:8)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at boP.run(SourceFile:2)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at android.os.Handler.handleCallback(Handler.java:751)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at android.os.Looper.loop(Looper.java:154)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at java.lang.reflect.Method.invoke(Native Method)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
11-25 13:02:00.396 E/cr_ChromeGcmListener(8661): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
`
I'm posting to chrome issues too

I'm running latest offlicial microg

**Comment by Nanolx** [comment]
Looks more like an Xposed issue to me, try disabling modules or Xposed and see what happens.

**Comment by patrickdrd** [comment]
I did, same result

**Comment by patrickdrd** [comment]
I tried on another device,
with slimrom 5.1 and latest gmscore
(because I can install apk with different signatures on that one, 
I wish the module would work on nougat too),
and the result was the same,
can anyone try and tell us if it works for him?

**Comment by patrickdrd** [comment]
they replied in chrome post this:
[quote]
Correct. They would have to support subtypes and include this with the information they send to Chrome.[/quote]

https://bugs.chromium.org/p/chromium/issues/detail?id=908255&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

so, please fix

**Comment by patrickdrd** [comment]
and as peter said, this page is really good for your tests:
https://tests.peter.sh/push-message-generator/

**Comment by Nanolx** [comment]
Ah, I see, it's about "Notification Channels". You're right, microG does not (yet?) support them.

So you'll have to wait until @mar-v-in jumps in.

**Comment by voidstarstar** [comment]
Additional useful info for reference:

https://github.com/chromium/chromium/tree/master/chrome/android/java/src/org/chromium/chrome/browser/notifications/channels

**Comment by markwylde** [comment]
@mar-v-in is there any chance all we need to do to get this working is forward the `subtype` property from the fcm request?
