### ISSUE TITLE
Google Family Link may require special handling like Contacts

### ISSUE THREAD

**Issue by akorn** [microg/GmsCore#686]
Could be similar to #589.

Launching Google Family Link results in the app saying "Error while loading accounts. Tap to retry.". In `logcat`, I see

```
01-09 17:21:54.607  3045  6167 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.apps.kids.familylink/.prelaunch.PreLaunchActivity bnds=[25,1116][231,1435]} from uid 10032
01-09 17:21:54.726  6302  6442 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
01-09 17:21:54.727  6302  6442 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12525000, packageName='com.google.android.apps.kids.familylink', extras=Bundle[{}]}
01-09 17:21:54.752  6302  6322 W GmsAuthProvider: Not granting extended access to [com.google.android.apps.kids.familylink], signature: 88652b8464743e5ce80da0d4b890d13f9b1873df   
01-09 17:21:54.808  6302  6442 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@4b5e525, 16
01-09 17:21:54.817  6302  6302 D GmsPeopleSvc: onBind: Intent { act=com.google.android.gms.people.service.START pkg=com.google.android.gms }
01-09 17:21:54.834  6302  6322 W GmsAuthProvider: Not granting extended access to [com.google.android.apps.kids.familylink], signature: 88652b8464743e5ce80da0d4b890d13f9b1873df   
01-09 17:21:54.834  6302  6321 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@5b2597c, 16
01-09 17:21:54.836  6302  7581 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@ec49f4e, 16
01-09 17:21:54.842  6302  6442 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@5b2597c, 16
01-09 17:21:54.878  6302  6436 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
01-09 17:21:54.878  6302  6436 D GmsPeopleSvc: bound by: GetServiceRequest{serviceId=PEOPLE, gmsVersion=12525000, packageName='com.google.android.apps.kids.familylink', extras=Bundle[{support_new_image_callback=true, social_client_application_id=602, real_client_package_name=com.google.android.apps.kids.familylink}]}
01-09 17:21:54.887  6302  6322 D GmsPeopleSvcImpl: loadOwners: false, false, null, null, 0
01-09 17:21:54.897  6302  7581 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@5b2597c, 16
```
and then
```
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe: Load accounts failed.
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe: java.lang.SecurityException: Access denied, missing EXTENDED_ACCESS permission
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at android.os.Parcel.readException(Parcel.java:2013)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at android.os.Parcel.readException(Parcel.java:1959)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at idw.zzb(PG:16)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at iui.a(PG:9)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at iuk.a(PG:36)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at ick.a(PG:4)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at hdi.b(PG:7)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at had.b(PG:16)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at had.a(PG:4)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at hbb.a(PG:21)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at hat.a(PG:42)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at icj.a(PG:2)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at jtn.a(PG:10)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at nmb.a(Unknown Source:4)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at nwa.a(Unknown Source:2)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at nuw.a(PG:5)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at nut.a(Unknown Source:2)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at pur.a(PG:11)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at pum.a(PG:4)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at ptw.a(PG:5)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at ptv.run(PG:17)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at pww.run(PG:3)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at nvv.run(PG:3)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at ntn.run(PG:5)
01-09 17:21:55.072 17770 17770 E SelectAccountFragmentPe:       at java.lang.Thread.run(Thread.java:764)
```

Is there a way I could grant this `EXTENDED_ACCESS` without recompiling?

**Comment by ale5000-git** [comment]
@mar-v-in
I have the same problem:
`Not granting extended access to [com.google.android.apps.kids.familylink], signature: 88652b8464743e5ce80da0d4b890d13f9b1873df`

**Comment by mar-v-in** [comment]
Have you checked if granting contacts permission through system settings solves this issue?

**Comment by ale5000-git** [comment]
I have tried to disable and re-enable all permissions in the Android settings (including contacts), nothing change.

**Comment by overclock98** [comment]
Is there any fix for this?

**Comment by akorn** [comment]
> Could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and report back?

I'm sorry, I can't; I don't currently have a device to experiment with.

**Comment by ale5000-git** [comment]
I have tried it and it recognize the account correctly although I haven't tried all the configuration to the end.

**Comment by Pazu** [comment]
Somehow I have got this to work even before the patch in #1787. However, the location maps don't work. I'm on e/OS/ 1.5 with microG Core 0.2.24.223616-96 (f87cb98)-noen.

**Comment by ale5000-git** [comment]
The microG builds from e/OS/ are different (and not always in sync) so you can't be sure what commit they include.

**Comment by ale5000-git** [comment]
About the location maps please open a separate issue.
