### ISSUE TITLE
Signal crash on number signup

### ISSUE THREAD

**Issue by jedie** [microg/GmsCore#687]
Sony Xperia XA2 model H3113 with `lineage-15.1-20190108-microG-pioneer.zip`
Signal v4.31.6.437

adb logcat:
```
01-12 13:32:58.194  1288  3380 W ActivityManager: Background start not allowed: service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } to com.google.android.gms/org.microg.gms.gcm.PushRegisterService from pid=6438 uid=10087 pkg=org.thoughtcrime.securesms
--------- beginning of crash
01-12 13:32:58.228  6438  6560 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
01-12 13:32:58.228  6438  6560 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6438
01-12 13:32:58.228  6438  6560 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) }: app is in background uid UidRecord{8828a40 u0a13 TRNB idle change:uncached procs:1 seq(0,0,0)}
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zzai(Unknown Source:81)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:61)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:509)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:498)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-12 13:32:58.228  6438  6560 E AndroidRuntime: 	... 3 more
```

**Comment by jedie** [comment]
Now i flash normal LineageOS: lineage-15.1-20190111-nightly-pioneer-signed.zip and signal signup works fine.

**Comment by Hello71** [comment]
Make sure you have turned off Privacy Guard.

**Comment by Riamse** [comment]
I had the same issue (but I don't know if it was the same exception). I solved it by de-registering Signal from using GCM and reinstalling Signal.

**Comment by veloute** [comment]
having the same problem - tried multiple things and nothing has fixed the problem so far.

**Comment by Riamse** [comment]
give it permission to access contacts?

**Comment by veloute** [comment]
my problem was actually my own doing and (presumabli) has nothing to do with the other people's problems in this issue - my bad!

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
