### ISSUE TITLE
ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=10225, uid=10249 requires com.google.android.c2dm.permission.RECEIVE

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#742]
When I try to open the app "Mimi" it crash, like other apps like Discord, Slack, Telegram with the same error.

Related:
https://github.com/microg/android_packages_apps_UnifiedNlp/issues/87
https://github.com/microg/android_packages_apps_GmsCore/issues/64

Info:
![Screenshot_20190331-123401](https://user-images.githubusercontent.com/43121549/55291127-82c86a00-53b1-11e9-9f3b-e91eb7049add.png)
![Screenshot_20190331-123410](https://user-images.githubusercontent.com/43121549/55291128-83610080-53b1-11e9-998a-b1ff1755a71d.png)
![Screenshot_20190331-123416](https://user-images.githubusercontent.com/43121549/55291129-83610080-53b1-11e9-91cd-787ae3c238a7.png)
![Screenshot_20190331-123436](https://user-images.githubusercontent.com/43121549/55291130-83610080-53b1-11e9-8177-5757bfc79ad6.png)

Logcat:
```
03-31 12:27:30.508 10225 10225 V FA      : Deferring to Google Analytics for Firebase for event data collection. https://goo.gl/J1sWQy
03-31 12:27:30.513  3496  9790 D GmsChimeraSpoof: query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.ads.dynamite
03-31 12:27:30.514 10225 10241 W DynamiteModule: Failed to retrieve remote module version.
03-31 12:27:30.517  2039 10126 I EdXposed-Bridge: FakeGApps: caught the NullPointerException
03-31 12:27:30.517  2039 10126 I EdXposed-Bridge: FakeGApps: caught the NullPointerException
03-31 12:27:30.522 10225 10241 I roid.phone.mim: The ClassLoaderContext is a special shared library.
03-31 12:27:30.523 10225 10241 I roid.phone.mim: The ClassLoaderContext is a special shared library.
03-31 12:27:30.525   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.527 10225 10241 I XLua.Xposed: Loaded com.google.android.gms:10249
03-31 12:27:30.531 10225 10241 W DynamiteModule: IDynamite loader version < 2, falling back to getModuleVersion2
03-31 12:27:30.531 10225 10241 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.ads.dynamite
03-31 12:27:30.531 10225 10241 I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:310 and remote module com.google.android.gms.ads.dynamite:0
03-31 12:27:30.531 10225 10241 I DynamiteModule: Selected local version of com.google.android.gms.ads.dynamite
03-31 12:27:30.532 10225 10241 W Ads     : #007 Could not call remote method. @28
03-31 12:27:30.532 10225 10241 W Ads     : com.google.android.gms.internal.ads.nr: com.google.android.gms.dynamite.DynamiteModule$a: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.internal.ads.np.a(Unknown Source:3)
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.internal.ads.bee.a(Unknown Source:43)
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.internal.ads.bef.run(Unknown Source:4)
03-31 12:27:30.532 10225 10241 W Ads     : 	at java.lang.Thread.run(Thread.java:764)
03-31 12:27:30.532 10225 10241 W Ads     : Caused by: com.google.android.gms.dynamite.DynamiteModule$a: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:257)
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.internal.ads.np.a(Unknown Source:1)
03-31 12:27:30.532 10225 10241 W Ads     : 	... 3 more
03-31 12:27:30.532 10225 10241 W Ads     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.measurement.DynamiteMeasurementManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.emogoth.android.phone.mimi-MtbdIvg1osNufdTJJdafIQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.emogoth.android.phone.mimi-MtbdIvg1osNufdTJJdafIQ==/lib/arm64, /data/app/com.emogoth.android.phone.mimi-MtbdIvg1osNufdTJJdafIQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
03-31 12:27:30.532 10225 10241 W Ads     : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
03-31 12:27:30.532 10225 10241 W Ads     : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-31 12:27:30.532 10225 10241 W Ads     : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-31 12:27:30.532 10225 10241 W Ads     : 	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:254)
03-31 12:27:30.532 10225 10241 W Ads     : 	... 4 more
03-31 12:27:30.542   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.547 10225 10225 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
03-31 12:27:30.547 10225 10225 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
03-31 12:27:30.548 10225 10225 I FirebaseInitProvider: FirebaseApp initialization successful
03-31 12:27:30.558   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.562 10225 10245 I FA      : App measurement is starting up, version: 13001
03-31 12:27:30.562 10225 10245 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
03-31 12:27:30.562 10225 10245 I FA      : To enable faster debug mode event logging run:
03-31 12:27:30.562 10225 10245 I FA      :   adb shell setprop debug.firebase.analytics.app com.emogoth.android.phone.mimi
03-31 12:27:30.565 10225 10225 I MimiUtil: Set theme: id=0, resource=2131886613
03-31 12:27:30.565 10225 10225 I MimiUtil: Setting cache dir to internal storage
03-31 12:27:30.575   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.580  2039  9676 I EdXposed-Bridge: FakeGApps: caught the NullPointerException
03-31 12:27:30.583  2039 10126 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=10225, uid=10249 requires com.google.android.c2dm.permission.RECEIVE
03-31 12:27:30.584 10225 10251 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
03-31 12:27:30.584 10225 10251 E AndroidRuntime: Process: com.emogoth.android.phone.mimi, PID: 10225
03-31 12:27:30.584 10225 10251 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.android.gms.common.stats.a.a(Unknown Source:22)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.android.gms.common.stats.a.a(Unknown Source:24)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.g.a(Unknown Source:17)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.e.a(Unknown Source:15)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.e.a(Unknown Source:12)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.v.a(Unknown Source:80)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.as.a(Unknown Source:73)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at com.google.firebase.iid.at.run(Unknown Source:6)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-31 12:27:30.584 10225 10251 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
03-31 12:27:30.586  2039 10126 D ActivityManager: New dropbox entry: com.emogoth.android.phone.mimi, data_app_crash, 8d8888ca-96b0-41ea-a0c1-343f09de894e
03-31 12:27:30.587  2039 10126 W ActivityManager:   Force finishing activity com.emogoth.android.phone.mimi/.activity.StartupActivity
03-31 12:27:30.582  2039  9676 I chatty  : uid=1000(system) Binder:2039_1B identical 1 line
03-31 12:27:30.583  2039  9676 I EdXposed-Bridge: FakeGApps: caught the NullPointerException
03-31 12:27:30.592   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.596 10225 10251 I Process : Sending signal. PID: 10225 SIG: 9
03-31 12:27:30.598  1346  1346 I JavaDumper:main: dest_path: /data/system/log/jd_dropboxfiles/data_app_crash@1554046050598.txt
03-31 12:27:30.598  1346  1346 I JavaDumper:main: tot_read: 1241, tot_write: 1241
03-31 12:27:30.598  1346  1346 I JavaDumper:main: Successfully copied dropbox file to /data/system/log/jd_dropboxfiles/data_app_crash@1554046050598.txt 
03-31 12:27:30.598  1346  1346 D clmlib  : Got activities:0x00000008
03-31 12:27:30.598  1346  1346 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1554046050598.txt processName: com.emogoth.android.phone.mimi
03-31 12:27:30.598  1346  1395 I JavaDumper:JavaDumperThread: Event: data_app_crash@1554046050598.txt TimeStamp: 1554046050
03-31 12:27:30.599  2039  2063 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.sonyericsson.crashmonitor/.receiver.CrashMonitorServiceBroadcastReceiver
03-31 12:27:30.600   944   944 E lowmemorykiller: Error writing /proc/10225/oom_score_adj; errno=22
03-31 12:27:30.606  1346  1395 W JavaDumper:JavaDumper: Could not init dump dir: Unknown error -95
03-31 12:27:30.607  1346  1395 E JavaDumper:FW:  utils.c(263): mkdir (/data/crashdata) failed. File exists
03-31 12:27:30.607  1346  1395 W JavaDumper:FW:  utils.c(604): chmod failed : Operation not permitted
03-31 12:27:30.607  1346  1395 W JavaDumper:FW:  utils.c(608): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(636): chmod failed : Operation not permitted
03-31 12:27:30.608  1346  1395 W JavaDumper:FW:  utils.c(641): chown failed : Operation not permitted
03-31 12:27:30.608  1346  1395 E JavaDumper:FW:  ramdump_framework.c(361): fp is NULL
03-31 12:27:30.608  1346  1395 E JavaDumper:FW:  ramdump_framework.c(542): Read-only file system
03-31 12:27:30.608   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-31 12:27:30.613  2039 10126 I ActivityManager: Process com.emogoth.android.phone.mimi (pid 10225) has died: vis  +99TOP 
03-31 12:27:30.613  2039  2066 W libprocessgroup: kill(-10225, 9) failed: No such process
03-31 12:27:30.613  2039  2066 I libprocessgroup: Successfully killed process cgroup uid 10249 pid 10225 in 0ms
03-31 12:27:30.613  1338  1338 I Zygote  : Process 10225 exited due to signal (9)
03-31 12:27:30.615  1327  1778 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.emogoth.android.phone.mimi#0
03-31 12:27:30.615  1327  1778 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.emogoth.android.phone.mimi#0
03-31 12:27:30.617  2039  2119 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5545 com.android.server.wm.WindowManagerService.removeWindow:1660 com.android.server.wm.Session.remove:226 
03-31 12:27:30.626   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 3, app_layer_count: 2, gpu_target_index: 2, display type: 0
03-31 12:27:30.635  2039  9093 I InputDispatcher: Focus entered window: Window{c2e50 u0 com.sonymobile.home/com.sonymobile.home.HomeActivity}
03-31 12:27:30.637  2039  2071 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{b49f14 u0 com.sonymobile.home/.HomeActivity t2} time:451372 diff:16 start:warm|top-activity batt:48|2 mw:off|0 mem:1775768|0|58|5|24 cpu:[1,1,1,1,1,1,1,1],[1900,2457]
03-31 12:27:30.640  1346  1395 W JavaDumper:FW:  ramdump_framework.c(1952): crashinfo.done not created
03-31 12:27:30.640  1346  1395 I JavaDumper:JavaDumperThread: Deleted /data/system/log/jd_dropboxfiles/data_app_crash@1554046050598.txt
03-31 12:27:30.640  2039  2068 E ActivityManager: Sending non-protected broadcast com.sonymobile.crashmonitorsystemservice.DIR_UPDATED from system 2039:system/1000 pkg android
03-31 12:27:30.640  2039  2068 E ActivityManager: java.lang.Throwable
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21814)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at EdHooker60.hook(Unknown Source:207)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:22423)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22565)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1224)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1196)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:525)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at com.sonymobile.crashmonitor.system.service.DumpfileObserver.onEvent(DumpfileObserver.java:32)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:123)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.os.FileObserver$ObserverThread.observe(Native Method)
03-31 12:27:30.640  2039  2068 E ActivityManager: 	at android.os.FileObserver$ObserverThread.run(FileObserver.java:86)
03-31 12:27:30.642  2039  2068 D ActivityManager: New dropbox entry: system_server, system_server_wtf, 127bb0c5-abdf-49ae-8185-5d0b6502e460
03-31 12:27:30.642   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-31 12:27:30.648  8163  8163 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1531 android.content.ContextWrapper.startService:664 android.content.ContextWrapper.startService:664 com.sonyericsson.crashmonitor.receiver.CrashMonitorServiceBroadcastReceiver.onReceive:54 android.app.ActivityThread.handleReceiver:3386 
03-31 12:27:30.651  8187  8187 I RcaHandler: Forwarding intent: com.sonymobile.crashmonitorsystemservice.DIR_UPDATED
03-31 12:27:30.651  8187  8187 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1531 android.content.ContextWrapper.startService:664 android.content.ContextWrapper.startService:664 com.sonymobile.rcahandler.RcaHandlerReceiver.onReceive:42 android.app.ActivityThread.handleReceiver:3386 
03-31 12:27:30.653  2039  5041 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.sonyericsson.crashmonitor/.receiver.CrashMonitorServiceBroadcastReceiver
03-31 12:27:30.654  8187 10269 I RcaHandler: onHandleIntent: com.sonymobile.crashmonitorsystemservice.DIR_UPDATED
03-31 12:27:30.654  8187 10269 I RcaHandler: fileName = tlcore_java_00
03-31 12:27:30.656  8187 10269 I RcaHandler: Handle JAVA-dumpfile with UUID:8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1 from:JavaDumper named:/data/crashdata/tlcore_java_00
03-31 12:27:30.659   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-31 12:27:30.660   613   613 W AshmemAllocator: ashmem_create_region(36) returning hidl_memory(0x7e9da2c100, 36)
03-31 12:27:30.663   613   613 W AshmemAllocator: ashmem_create_region(9) returning hidl_memory(0x7e9da2c100, 9)
03-31 12:27:30.666   613   613 W AshmemAllocator: ashmem_create_region(9) returning hidl_memory(0x7e9da2c100, 9)
03-31 12:27:30.667   613   613 W AshmemAllocator: ashmem_create_region(1) returning hidl_memory(0x7e9da2c100, 1)
03-31 12:27:30.670   613   613 W AshmemAllocator: ashmem_create_region(1) returning hidl_memory(0x7e9da2c100, 1)
03-31 12:27:30.671   613   613 W AshmemAllocator: ashmem_create_region(8) returning hidl_memory(0x7e9da2c100, 8)
03-31 12:27:30.674   613   613 W AshmemAllocator: ashmem_create_region(8) returning hidl_memory(0x7e9da2c100, 8)
03-31 12:27:30.675   613   613 W AshmemAllocator: ashmem_create_region(36) returning hidl_memory(0x7e9da2c100, 36)
03-31 12:27:30.675   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-31 12:27:30.678   613   613 W AshmemAllocator: ashmem_create_region(36) returning hidl_memory(0x7e9da2c100, 36)
03-31 12:27:30.684  8187 10269 I RcaHandler: Add event started for crashId: 8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1, object size: 71 bytes
03-31 12:27:30.687  8187 10269 I RcaHandler: Time taken to add event 2 ms
03-31 12:27:30.687  8187 10269 I RcaHandler: Added event. Result: 0, crashId: 8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1, Probe: RcaInfoProbeExtended
03-31 12:27:30.687  8187 10269 I RcaHandler: Add event started for crashId: 8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1, object size: 70 bytes
03-31 12:27:30.689  8187 10269 I RcaHandler: Time taken to add event 2 ms
03-31 12:27:30.690  8187 10269 I RcaHandler: Added event. Result: 0, crashId: 8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1, Probe: RcaInfoProbeCompact
03-31 12:27:30.690  8187 10269 I RcaHandler: Saved JAVA_SYSTEM_APP (ID:06e8505b-ad3f-432d-bb45-8a5d635a084d) to IDD, crashId: 8475BCD4-8000-1C74-DA53-C95D0F0339C1-5F072CE1
03-31 12:27:30.690  8187 10269 I RcaHandler: Added entry JAVA to rca-list
03-31 12:27:30.692   874  1044 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-31 12:27:30.693  2039  5041 E ActivityManager: Sending non-protected broadcast com.sonymobile.crashmonitor.CRASH_STATUS from system 8163:com.sonyericsson.crashmonitor/1000 pkg com.sonyericsson.crashmonitor
03-31 12:27:30.693  2039  5041 E ActivityManager: java.lang.Throwable
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21814)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at EdHooker60.hook(Unknown Source:207)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:22423)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22565)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10169)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3416)
03-31 12:27:30.693  2039  5041 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:731)
03-31 12:27:30.694  2039  5041 D ActivityManager: New dropbox entry: system_server, system_server_wtf, 6aee81c1-a590-41d3-b987-9abeaba6aa59
```

**Comment by DPTJKKVH** [comment]
I'm sure this is related to #740

**Comment by Nanolx** [comment]
I'm not so sure, it catches a permission denial in `com.google.android.gms/org.microg.gms.gcm.PushRegisterService`.

Do you have GsfProxy installed? If not, installing it /may/ fix the issue, else try re-installing it.

**Comment by ben-dl** [comment]
Same issue here, also Android 9, same security patchlevel, with pretty much all apps (Whatsapp, Discord, some FCM notification tester app etc.). All APKs from the website installed, including GsfProxy. MicroG setting self check etc. is the same as in OP.
