### ISSUE TITLE
Mapbox causes "Address Lookup" to crash repeatedly

### ISSUE THREAD

**Issue by benwaffle** [microg/GmsCore#795]
Not sure if related:
```
05-30 21:23:50.337 11979 11979 D AndroidRuntime: Shutting down VM
05-30 21:23:50.339 11979 11979 E AndroidRuntime: FATAL EXCEPTION: main
05-30 21:23:50.339 11979 11979 E AndroidRuntime: Process: com.google.android.gms, PID: 11979
05-30 21:23:50.339 11979 11979 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider org.microg.gms.maps.vtm.data.SharedTileProvider: java.lang.ClassNotFoundException: Didn't find class "org.microg.gms.maps.vtm.data.SharedTileProvider" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/GmsCore/GmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/GmsCore/lib/arm64, /system/priv-app/GmsCore/GmsCore.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6445)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.microg.gms.maps.vtm.data.SharedTileProvider" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/GmsCore/GmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/GmsCore/lib/arm64, /system/priv-app/GmsCore/GmsCore.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.support.v4.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6429)
05-30 21:23:50.339 11979 11979 E AndroidRuntime: 	... 10 more
05-30 21:23:50.343  1314  4794 W ActivityManager:   Force finishing activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
05-30 21:23:50.346  1314  1369 I ActivityManager: Showing crash dialog for package com.google.android.gms u0
05-30 21:23:50.448  3529  3540 E droid.launcher: No package ID ff found for ID 0xffffffff.
05-30 21:23:50.448  3529  3540 E IconLoader: Could not find icon drawable from resource
05-30 21:23:50.448  3529  3540 E IconLoader: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
05-30 21:23:50.448  3529  3540 E IconLoader: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at android.content.res.Resources.getDrawable(Resources.java:827)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:325)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:188)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(RecentsModel.java:214)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:80)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
05-30 21:23:50.448  3529  3540 E IconLoader: 	at android.os.Binder.execTransact(Binder.java:731)
```

BTW, the mapbox maps look great. Uber and lyft show everything clearly.

**Comment by mar-v-in** [comment]
SharedTileProvider shouldn't be used anymore with the mapbox build. Can you check in the logs which app/component wants to access it (should be somewhere before this log)

**Comment by benwaffle** [comment]
cannot reproduce
