### ISSUE TITLE
gms.auth.api.credentials.PICKER crash

### ISSUE THREAD

**Issue by CFPrulez** [microg/GmsCore#844]
Is this a MicroG issue?

```
06-19 20:40:10.747 ActivityManager I  START u0 {act=com.google.android.gms.auth.api.credentials.PICKER (has extras)} from uid 10XXX
06-19 20:40:10.748 AndroidRuntime  D  Shutting down VM
06-19 20:40:10.749 AndroidRuntime  E  FATAL EXCEPTION: main
06-19 20:40:10.749 AndroidRuntime  E  Process: xxxxxxxx, PID: 26573
06-19 20:40:10.749 AndroidRuntime  E  android.content.ActivityNotFoundException: No Activity found to handle null
06-19 20:40:10.749 AndroidRuntime  E  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
06-19 20:40:10.749 AndroidRuntime  E  at android.app.Activity.startIntentSenderForResultInner(Activity.java:4846)
06-19 20:40:10.749 AndroidRuntime  E  at android.app.Activity.startIntentSenderForResult(Activity.java:4813)
06-19 20:40:10.749 AndroidRuntime  E  at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(SourceFile:6)
06-19 20:40:10.749 AndroidRuntime  E  at androidx.core.app.ActivityCompat.startIntentSenderForResult(SourceFile:2)
```

**Comment by mar-v-in** [comment]
Yes. This feature is not implemented yet. Which app are you using that causes the issue?

**Comment by CFPrulez** [comment]
I'm installing several apps to see which are broken in combination with the latest microG. Uber is already referenced, anonther one would be the SmsAuthActivity in Tinder.

**Comment by CyberShadow** [comment]
Yandex Taxi (ru.yandex.taxi) also [crashes](https://dump.thecybershadow.net/313479bd846a15bcec745bc34fd5ac1c/20%3A38%3A37-upload.txt) in this way when selecting the "How would you like to pay?" entry in the menu. (No purchase/order required to reproduce)

**Comment by parthnatu** [comment]
> I'm installing several apps to see which are broken in combination with the latest microG. Uber is already referenced, anonther one would be the SmsAuthActivity in Tinder.

Should I revert back to an older version for it to work?

**Comment by Timvde** [comment]
The Belgian BNP Paribas Fortis Easy Banking app also crashes with this signature right after first authentication.

**Comment by carlin-q-scott** [comment]
Meetup crashes with this error when I try to log in using my email address.
[meetup-crash.log](https://github.com/microg/android_packages_apps_GmsCore/files/4113072/meetup-crash.log)

**Comment by HugoPoi** [comment]
Pretty sure this is related

```
07-04 20:06:34.228  3169  5316 I ActivityManager: START u0 {cmp=com.tinder/.smsauth.ui.SmsAuthActivity} from uid 10162
07-04 20:06:34.250  8157  8157 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@3e4c5cc
07-04 20:06:34.508  8157  8169 I com.tinder: Background concurrent copying GC freed 35951(3MB) AllocSpace objects, 9(704KB) LOS objects, 49% free, 9MB/19MB, paused 161us total 111.414ms
07-04 20:06:34.591  6365 19241 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-04 20:06:34.591  6365 19241 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-04 20:06:34.591  6365 19241 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-04 20:06:34.591  6365 19241 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='com.tinder', extras=Bundle[{}]}
07-04 20:06:34.615  8157  8282 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-04 20:06:34.615  8157  8282 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
07-04 20:06:34.686  3169 21251 I ActivityManager: START u0 {act=com.google.android.gms.auth.api.credentials.PICKER (has extras)} from uid 10162
07-04 20:06:34.699  8157  8157 D AndroidRuntime: Shutting down VM
07-04 20:06:34.700  6365  6365 D GmsDummySvc: onBind: Intent { act=com.google.android.gms.auth.api.credentials.service.START pkg=com.google.android.gms }
07-04 20:06:34.701  8157  8157 E AndroidRuntime: FATAL EXCEPTION: main
07-04 20:06:34.701  8157  8157 E AndroidRuntime: Process: com.tinder, PID: 8157
07-04 20:06:34.701  8157  8157 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle null
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:4846)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResult(Activity.java:4813)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(SourceFile:6)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startIntentSenderForResult(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startIntentSenderFromFragment(SourceFile:6)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartIntentSenderFromFragment(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.Fragment.startIntentSenderForResult(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.PhoneNumberCollectionFragment.c(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.PhoneNumberCollectionFragment.access$requestPhoneNumberHint(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.PhoneNumberCollectionFragment$onActivityCreated$4.a(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.PhoneNumberCollectionFragment$onActivityCreated$4.onChanged(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData.considerNotify(SourceFile:6)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:5)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData$ObserverWrapper.a(SourceFile:10)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(SourceFile:3)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.a(SourceFile:3)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.b(SourceFile:17)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.c(SourceFile:10)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.b(SourceFile:5)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentViewLifecycleOwner.a(SourceFile:3)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(SourceFile:9)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.m(SourceFile:3)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.a(SourceFile:58)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.j(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.i(SourceFile:4)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.a(SourceFile:107)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.a(SourceFile:112)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.a(SourceFile:197)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.b(SourceFile:42)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.c(SourceFile:34)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.b(SourceFile:23)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitNow(SourceFile:2)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.SmsAuthActivity.a(SourceFile:7)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.SmsAuthActivity.access$navigateToFragment(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.SmsAuthActivity$onCreate$6.a(SourceFile:3)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.tinder.smsauth.ui.SmsAuthActivity$onCreate$6.onChanged(SourceFile:1)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData.considerNotify(SourceFile:6)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:8)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData.setValue(SourceFile:4)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at androidx.lifecycle.LiveData$1.run(SourceFile:5)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-04 20:06:34.701  8157  8157 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-04 20:06:34.843  3169  5012 W ActivityManager:   Force finishing activity com.tinder/.smsauth.ui.SmsAuthActivity
07-04 20:06:34.847  3169  5012 W ActivityManager:   Force finishing activity com.tinder/.activities.LoginActivity
07-04 20:06:34.855  3169  3810 I ActivityManager: Showing crash dialog for package com.tinder u0
```

**Comment by gnampf1** [comment]
de.wilhelmshavenerzeitung.areader (Brune-Mettcker ePaper) also crashes with this reason if you try to login and tap into the email field

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
