### ISSUE TITLE
GmsPhenotypeCfgProvider: unimplemented Method: onCreate

### ISSUE THREAD

**Issue by chris42** [microg/GmsCore#871]
Just found an "error" during closing of microg. Seems not to impact microg, but might be something to fix?
To reproduce: Completely close microg by flicking it up in the card view.

```
07-06 08:21:31.773   993  1348 I ActivityManager: Start proc 4867:com.google.android.gms/u0a23 for service com.google.android.gms/org.microg.nlp.geocode.GeocodeServiceV1
07-06 08:21:31.774  4867  4867 I Zygote  : seccomp disabled by setenforce 0
07-06 08:21:31.839  4867  4867 I gle.android.gm: The ClassLoaderContext is a special shared library.
07-06 08:21:31.868  4867  4867 I MultiDex: VM with version 2.1.0 has multidex support
07-06 08:21:31.869  4867  4867 I MultiDex: Installing application
07-06 08:21:31.869  4867  4867 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-06 08:21:31.875  4867  4867 D GmsApiAvailability: As we can't know right now if the later desired feature is available, we just pretend it to be.
07-06 08:21:31.894  4867  4867 D GmsPhenotypeCfgProvider: unimplemented Method: onCreate
07-06 08:21:31.930   993  1345 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
07-06 08:21:31.930   993  1345 W Binder  : java.lang.Throwable
07-06 08:21:31.930   993  1345 W Binder  : 	at android.os.BinderProxy.transact(Binder.java:1114)
07-06 08:21:31.930   993  1345 W Binder  : 	at com.android.internal.location.ILocationProvider$Stub$Proxy.getProperties(ILocationProvider.java:236)
07-06 08:21:31.930   993  1345 W Binder  : 	at com.android.server.location.LocationProviderProxy$1$1.run(LocationProviderProxy.java:117)
07-06 08:21:31.930   993  1345 W Binder  : 	at com.android.server.ServiceWatcher.runOnBinder(ServiceWatcher.java:425)
07-06 08:21:31.930   993  1345 W Binder  : 	at com.android.server.location.LocationProviderProxy$1.run(LocationProviderProxy.java:111)
07-06 08:21:31.930   993  1345 W Binder  : 	at android.os.Handler.handleCallback(Handler.java:873)
07-06 08:21:31.930   993  1345 W Binder  : 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-06 08:21:31.930   993  1345 W Binder  : 	at android.os.Looper.loop(Looper.java:193)
07-06 08:21:31.930   993  1345 W Binder  : 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by voidstarstar** [comment]
This looks like just a warning caused by a method stub in [ConfigurationProvider](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/phenotype/ConfigurationProvider.java).  I could be wrong, but I don't think this is necessary to implement or at least should have a low priority.

**Comment by chris42** [comment]
Yes, agree with the low priority, however wanted to note it down.

**Comment by chris42** [comment]
I just checked this. I still get the "unimplemented Method: onCreate" message, however no exception anymore. So it is, how it should be. Closing
