### ISSUE TITLE
Uber Azerbaijan crashes on startup

### ISSUE THREAD

**Issue by isthisme** [microg/GmsCore#873]
Uber's Azerbaijan taxi app crashes immediately upon starting up.  Here's the FATAL logcat:

`FATAL EXCEPTION: main
Process: com.mlubv.uber.az:passport, PID: 2095
android.content.ActivityNotFoundException: No Activity found to handle null
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
	at android.app.Activity.startIntentSenderForResultInner(Activity.java:4846)
	at android.app.Activity.startIntentSenderForResult(Activity.java:4813)
	at android.support.v4.app.BaseFragmentActivityApi16.startIntentSenderForResult(SourceFile:69)
	at android.support.v4.app.FragmentActivity.startIntentSenderForResult(SourceFile:68)
	at android.support.v4.app.ActivityCompat.a(SourceFile:270)
	at android.support.v4.app.FragmentActivity.startIntentSenderFromFragment(SourceFile:852)
	at android.support.v4.app.FragmentActivity$HostCallbacks.a(SourceFile:946)
	at android.support.v4.app.Fragment.startIntentSenderForResult(SourceFile:1034)
	at com.yandex.passport.internal.ui.domik.a.h.onResume(SourceFile:110)
	at android.support.v4.app.Fragment.performResume(SourceFile:2390)
	at android.support.v4.app.FragmentManagerImpl.a(SourceFile:1474)
	at android.support.v4.app.FragmentManagerImpl.b(SourceFile:1759)
	at android.support.v4.app.FragmentManagerImpl.a(SourceFile:1827)
	at android.support.v4.app.BackStackRecord.h(SourceFile:797)
	at android.support.v4.app.FragmentManagerImpl.b(SourceFile:2596)
	at android.support.v4.app.FragmentManagerImpl.a(SourceFile:2383)
	at android.support.v4.app.FragmentManagerImpl.b(SourceFile:2338)
	at android.support.v4.app.FragmentManagerImpl.i(SourceFile:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(SourceFile:703)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

You can get the app here on the Playstore: https://play.google.com/store/apps/details?id=com.mlubv.uber.az

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
