### ISSUE TITLE
Can't use some apps after microG update

### ISSUE THREAD

**Issue by lucker999** [microg/GmsCore#947]
Hello there,
I updated microG from version 0.2.6.13280 to the current with NanoDroid-microG from 22.4.20190811 and faced the problem. Garmin Connect app crashes when I try to open an activity and it get no activity list. The opening activity involved loading the map (I guess it's google map. With old version microG I have a error message written on the opened activity page where a map supposed to be: "Connect is having trouble with Google Play services. Please try again". With updated microG version no messages, the app just crashes. 

I guess the issue could lay in the way the microG works with requestes to the gapps and this was changed. Could you please provide the option what could and should I do in order to keep updeted microG and use the apps that try to connect through gaaps?

Thanks

**Comment by be-neth** [comment]
Hello,

Same behavior with garmin connect.

Here the logcat output :

`09-25 16:00:50.846  4409 25852 D GmsChimeraSpoof: query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.maps_dynamite
09-25 16:00:50.867  4138  4138 I s.connectmobil: The ClassLoaderContext is a special shared library.
09-25 16:00:50.877  4138  4138 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.maps_dynamite
09-25 16:00:50.882  4138  4138 D GmsMapCreator: initV2
09-25 16:00:50.896  4138  4138 D GmsMapView: onCreate: lat/lng: (0.0,0.0)
09-25 16:00:50.920  4138  4138 D GmsMultiArchLoader: Loading mapbox-gl from /data/user/0/com.garmin.android.apps.connectmobile/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so

09-25 16:00:50.980  4138  4138 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-25 16:00:51.089  4138  4138 I chatty  : uid=10159(com.garmin.android.apps.connectmobile) identical 4 lines
09-25 16:00:51.096  4138  4138 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-25 16:00:51.114   566   904 W ServiceManager: Permission failure: android.permission.ACCESS_SURFACE_FLINGER from uid=10159 pid=4138
09-25 16:00:51.114   566   904 D PermissionCache: checking android.permission.ACCESS_SURFACE_FLINGER for uid=10159 => denied (663 us)
09-25 16:00:51.129  4138 21209 I Mbgl-EGLConfigChooser: In emulator: false
09-25 16:00:51.149  4138 21209 I Mbgl    : {GLThread 2158}[General]: GPU Identifier: Adreno (TM) 530
09-25 16:00:51.167  4138  4138 D GmsMapBitmap: registerMap
09-25 16:00:51.178  4138  4138 D GmsMap  : Invoking 6 callbacks delayed, as map is initialized
09-25 16:00:51.183  4138  4138 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-25 16:00:51.184  4138  4138 I chatty  : uid=10159(com.garmin.android.apps.connectmobile) identical 1 line
09-25 16:00:51.185  4138  4138 D GmsMap  : Delay callback invocation, as map is not yet initialized
09-25 16:00:51.185  4138  4138 D AndroidRuntime: Shutting down VM
09-25 16:00:51.198  4138  4138 E AndroidRuntime: FATAL EXCEPTION: main
09-25 16:00:51.198  4138  4138 E AndroidRuntime: Process: com.garmin.android.apps.connectmobile, PID: 4138
09-25 16:00:51.198  4138  4138 E AndroidRuntime: java.util.ConcurrentModificationException
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at java.util.ArrayList$Itr.next(ArrayList.java:860)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:540)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at org.microg.gms.maps.mapbox.GoogleMapImpl.access$initMap(GoogleMap.kt:61)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:459)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:61)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at org.microg.gms.maps.mapbox.GoogleMapKt$sam$com_mapbox_mapboxsdk_maps_OnMapReadyCallback$0.onMapReady(Unknown Source:7)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:205)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:62)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:320)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-25 16:00:51.198  4138  4138 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-25 16:00:51.507  2326 14807 W ActivityManager:   Force finishing activity com.garmin.android.apps.connectmobile/.activities.stats.ActivityStatsActivity
09-25 16:00:51.516  4138  4138 I Process : Sending signal. PID: 4138 SIG: 9
`

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Same behaviour here.

**Comment by mar-v-in** [comment]
Is this still an issue with v0.2.9?

**Comment by be-neth** [comment]
Nop @mar-v-in, this is working fine now.
Thanks!

**Comment by tretkowski** [comment]
Works fine here since 0.2.14, I guess this issue could be closed.

**Comment by ale5000-git** [comment]
I'm closing it because it seems fixed, if you have the problem again just write here and I will reopen it.

**Comment by derMart** [comment]
same problem slightly different stack trace here in 0.2.24.214816
```
05-20 13:54:56.150 19494 19494 E AndroidRuntime: FATAL EXCEPTION: main
05-20 13:54:56.150 19494 19494 E AndroidRuntime: Process: com.google.android.gms, PID: 19494
05-20 13:54:56.150 19494 19494 E AndroidRuntime: java.util.ConcurrentModificationException
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at org.microg.nlp.service.LocationServiceImpl.reportLocation(LocationService.kt:319)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at org.microg.nlp.service.LocationFuser.updateLocation(LocationFuser.kt:101)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at org.microg.nlp.service.LocationFuser.update(LocationFuser.kt:87)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at org.microg.nlp.service.LocationFuser$update$1.invokeSuspend(Unknown Source:14)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:31)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:100)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-20 13:54:56.150 19494 19494 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```
cheers

**Comment by ale5000-git** [comment]
@derMart
You say the version of microG, but what about backend?

**Comment by derMart** [comment]
ah sorry, org.microg.nlp.backend.ichnaea version 1.5.0
I got apple wifi and mozilla location service installed but deactivated and only gsm location service active (org.fitchfamily.android.gsmlocation version 1.5.3)

**Comment by ale5000-git** [comment]
@derMart
Hi,
since you problem is different from the one fo this ticket, could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and then open a separate ticket with a new logcat?
